### ISSUE TITLE
Emit custom event with key/ values fails to load

### ISSUE THREAD

**Issue by yochay** [microsoft/BotFramework-Composer#1328]
## Version
be6b825e

## Describe the bug
When using Emit custom event and adding any keys to Event Value - bot doesn't load and seeing error message in Composer. 

If the event doesnt have any Event values, no exception is thrown and bot works as expected. 

The bot runtime throws exception related to the key value. See trace 

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.Exception: C:\Data\repos\BotFramework-Composer\BotProject\CSharp\bin\Debug\netcoreapp2.1\tmp\4498814a60364d698ebca6f8629c32d3\Main\Main.dialog error: Error reading string. Unexpected token: StartObject. Path 'eventValue', line 32, position 25.

   at Microsoft.Bot.Builder.Dialogs.Declarative.DeclarativeTypeLoader.LoadAsync[T](IResource resource, ResourceExplorer resourceExplorer, ISourceMap sourceMap)
   at Microsoft.Bot.Builder.Dialogs.Declarative.DeclarativeTypeLoader.Load[T](IResource resource, ResourceExplorer resourceExplorer, ISourceMap sourceMap)
   at Microsoft.Bot.Builder.ComposerBot.json.ComposerBot.LoadRootDialogAsync() in C:\Data\repos\BotFramework-Composer\BotProject\CSharp\ComposerBot.cs:line 59
   at Microsoft.Bot.Builder.ComposerBot.json.ComposerBot..ctor(String rootDialogFile, ConversationState conversationState, UserState userState, ResourceExplorer resourceExplorer, ISourceMap sourceMap) in C:\Data\repos\BotFramework-Composer\BotProject\CSharp\ComposerBot.cs:line 53
   at Microsoft.Bot.Builder.ComposerBot.json.BotManager.SetCurrent(String botDir) in C:\Data\repos\BotFramework-Composer\BotProject\CSharp\BotManager.cs:line 89
   at Microsoft.Bot.Builder.ComposerBot.json.BotManager.SetCurrent(Stream fileStream, String endpointKey, String appPwd) in C:\Data\repos\BotFramework-Composer\BotProject\CSharp\BotManager.cs:line 103
   at Microsoft.Bot.Builder.ComposerBot.json.BotAdminController.PostAsync(IFormFile file, String endpointKey, String microsoftAppPassword) in C:\Data\repos\BotFramework-Composer\BotProject\CSharp\Controllers\BotAdminController.cs:line 37
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 37.3877ms 500 text/html; charset=utf-8
```

## To Reproduce
1. Create a new bot 
2. Add Emit custom event in the Update Conversation Handler 
3. No error
4. Go back to the custom event and add values (in any form of keys and values)
5. restart the bot --> see above exception

## Expected behavior
Give a clear and concise description of what you expected to happen.

**Comment by luhan2017** [comment]
Fixed in the SDK side, will resolve this after a package update.
