### ISSUE TITLE
Publish LUIS bot failure

### ISSUE THREAD

**Issue by nitroin** [microsoft/BotFramework-Composer#4527]
## Describe the bug

Unable to deploy a LUIS bot.

## Version

Various versions:
- Release: 1.1.1.
- `git main` checkout ``

## Browser

- [x] Electron distribution
- [x] Chrome
- [ ] Safari
- [x] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [x] Ubuntu

## To Reproduce

Steps to reproduce the behavior: https://docs.microsoft.com/en-us/composer/how-to-publish-bot

Our config:
- `ToDoBotWithLuisSample` without any changes
- Azure Resources in `westeurope` 

## Expected behavior

Deploy bot succesfully.

## Screenshots

![Screenshot from 2020-10-21 16-41-14](https://user-images.githubusercontent.com/14164969/96735892-52458800-13bc-11eb-916b-7a62080e9688.png)

## Additional context

```
{
  "status": "DEPLOY_INFO",
  "message": "start publish luis"
}
{
  "status": "DEPLOY_ERROR",
  "message": "{\"name\":\"StatusCodeError\",\"statusCode\":429,\"message\":\"429 - \\\"{\\\\\\\"error\\\\\\\":{\\\\\\\"code\\\\\\\":\\\\\\\"429\\\\\\\",\\\\\\\"message\\\\\\\": \\\\\\\"Requests to the user - Get LUIS azure accounts Operation under LUIS Programmatic APIs v2.0 have exceeded rate limit of your current LUIS.Authoring F0 pricing tier. Please retry after 1 second. To increase your rate limit switch to a paid tier.\\\\\\\"}}\\\"\",\"error\":\"{\\\"error\\\":{\\\"code\\\":\\\"429\\\",\\\"message\\\": \\\"Requests to the user - Get LUIS azure accounts Operation under LUIS Programmatic APIs v2.0 have exceeded rate limit of your current LUIS.Authoring F0 pricing tier. Please retry after 1 second. To increase your rate limit switch to a paid tier.\\\"}}\",\"options\":{},\"response\":{\"statusCode\":429},\"stack\":\"StatusCodeError: 429 - \\\"{\\\\\\\"error\\\\\\\":{\\\\\\\"code\\\\\\\":\\\\\\\"429\\\\\\\",\\\\\\\"message\\\\\\\": \\\\\\\"Requests to the user - Get LUIS azure accounts Operation under LUIS Programmatic APIs v2.0 have exceeded rate limit of your current LUIS.Authoring F0 pricing tier. Please retry after 1 second. To increase your rate limit switch to a paid tier.\\\\\\\"}}\\\"\\n    at new StatusCodeError (/var/home/kunta/Work/fts/BotFramework-Composer/extensions/azurePublish/node_modules/request-promise-core/lib/errors.js:32:15)\\n    at Request.plumbing.callback (/var/home/kunta/Work/fts/BotFramework-Composer/extensions/azurePublish/node_modules/request-promise-core/lib/plumbing.js:104:33)\\n    at Request.RP$callback [as _callback] (/var/home/kunta/Work/fts/BotFramework-Composer/extensions/azurePublish/node_modules/request-promise-core/lib/plumbing.js:46:31)\\n    at Request.self.callback (/var/home/kunta/Work/fts/BotFramework-Composer/extensions/azurePublish/node_modules/request/request.js:185:22)\\n    at Request.emit (events.js:315:20)\\n    at Request.<anonymous> (/var/home/kunta/Work/fts/BotFramework-Composer/extensions/azurePublish/node_modules/request/request.js:1154:10)\\n    at Request.emit (events.js:315:20)\\n    at IncomingMessage.<anonymous> (/var/home/kunta/Work/fts/BotFramework-Composer/extensions/azurePublish/node_modules/request/request.js:1076:12)\\n    at Object.onceWrapper (events.js:421:28)\\n    at IncomingMessage.emit (events.js:327:22)\\n    at endReadableNT (_stream_readable.js:1220:12)\\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)\"}"
}
```

Closed related issues [#4392](https://github.com/microsoft/BotFramework-Composer/issues/4392).

**Comment by mdrichardson** [comment]
@nitroin How many LUIS resources are on the entire Azure subscription that you're using? How many in the free and how many in the paid tiers?

Also, what deployment method are you attempting?

Also, it should be noted that there are two types of resources in LUIS:

* Authoring - can only be F0 tier
* Prediction Endpoint - Can be F0 or S0

If you don't assign/create a Prediction Endpoint resource, LUIS just uses the Authoring one. To check, go to LUIS > Your App > Manage > Azure Resources. If you don't have a prediction resource assigned, it will look like:

![image](https://user-images.githubusercontent.com/40401643/90562076-800d1700-e156-11ea-9cfb-b8efbc008a6a.png)

If you do, you can go into Azure and change the pricing tier.

**Comment by nitroin** [comment]
> How many LUIS resources are on the entire Azure subscription that you're using?

This is the only bot we have on the entire subscription. All the resources are created with the provided [bot script](https://docs.microsoft.com/en-us/composer/how-to-publish-bot#create-azure-resources).

By script default (I assuming) both Authoring and Prediction are created. With F0 and S0 pricing tier respectively.

![Screenshot from 2020-10-27 10-04-37](https://user-images.githubusercontent.com/14164969/97279914-dde76a80-183b-11eb-8d12-3a581635b6fc.png)

> Also, what deployment method are you attempting?

We're trying to deploy into _Azure Web App_.

Please take note that our bot has a couple of Luis app mapped, since many prediction models are created from one Composer bot. In this moment in time (30% develpment) we have the following:

![Screenshot from 2020-10-27 10-08-59](https://user-images.githubusercontent.com/14164969/97280512-aaf1a680-183c-11eb-9d8b-62b12a70be23.png)

Are Luis app number limited in any way?

Now, after a couple of tries (removing all the created resources and resource group), bot apparently deployed succesfully:

![Screenshot from 2020-10-27 10-10-24](https://user-images.githubusercontent.com/14164969/97280571-be047680-183c-11eb-840f-363c7fcc1e98.png)

But the bot is not working nontheless with the `/api/messages` returning:

```
 HTTP Error 500.31 - ANCM Failed to Find Native Dependencies
Common solutions to this issue:
The specified version of Microsoft.NetCore.App or Microsoft.AspNetCore.App was not found.
Troubleshooting steps:

    Check the system event log for error messages
    Enable logging the application process' stdout messages
    Attach a debugger to the application process and inspect
```

That being said, within Composer + Emulator. All is working fine.

We have no clue how to resolve this issue.

**Comment by cwhitten** [comment]
@nitroin the activity you have available to you in LUIS is governed by your pricing tier. the TodoWithLuis bot includes multiple LUIS applications that get created when you publish, and is better suited to use a paid pricing tier (and associated authoring keys) for general use.

**Comment by nitroin** [comment]
> @nitroin the activity you have available to you in LUIS is governed by your pricing tier. the TodoWithLuis bot includes multiple LUIS applications that get created when you publish, and is better suited to use a paid pricing tier (and associated authoring keys) for general use.

Yep, I understand, but please take note that this is exactly our scenario.

By default the provision script deploy 2 LUIS resources:

1. Authoring endpoint (free tier, the only available)
2. Non-authoring endpoint (I think we can call it prediction endpoint? - S0 pay as you go tier)

When clicking _Publish_ from Composer (using the app manifest from the [provision steps](https://docs.microsoft.com/en-us/composer/how-to-publish-bot#create-azure-resources)) we cannot select which endpoint to call, thus the 429 rate limit error.

Sometimes purging the entire LUIS authoring resource seems to allow us to successfully deploy the bot, but this looks impractical, and not reliable since we are facing 429 errors also from an empty LUIS account sometimes.

Since the Composer is hitting 429, will be great if the scripts that interface with LUIS implements some kind of retry logic to minimize those errors users are facing (and that we cannot fix).

I'll be open to try experimenting with a PR if minimal hints are provided.

**Comment by cwhitten** [comment]
Thank you @nitroin - @luhan2017 can you take a look at this?

**Comment by luhan2017** [comment]
@nitroin , According to this doc, https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-how-to-azure-subscription
There is only one pricing tier available for the LUIS authoring resource:
* Free F0 Authoring resource which gives you 1M Free authoring transactions and 1000 free testing prediction endpoint requests monthly, 5 transactions per second.
We already have the retry logic(default retry once) for 429 limit, @feich-ms to add more detail on how to configure the retry times in composer.

**Comment by feich-ms** [comment]
I did some investigations and have a branch to enable retry count configuration. But from the error message above, the request `Get LUIS azure accounts Operation` is not from luis build so the failure didn't come from luis build call, actually it's more like azure deployment failure. Maybe @zidaneymar has more insights about this request?

**Comment by mrivera-ms** [comment]
@zidaneymar, do you have any updates for this issue? @luhan2017

**Comment by zidaneymar** [comment]
Hi, @nitroin, for  HTTP Error 500.31 issue, could you please download your webapp source code from your kudu service portal and dotnet run your runtime locally to view more details? I think the dotnet runtime of your bot is broken, maybe you could try merge the latest main branch and try again.

**Comment by nitroin** [comment]
@zidaneymar sorry I forget to provide you the details you requested, but I was unable to repro the 500.31 error with the latest Bot Composer version (1.2.1).

The 429 error, however, still exists.

**Comment by luhan2017** [comment]
@nitroin sorry for the late response, could you please paste the publish log here when you see 429 error?

Just select the publish item and click see log 
![image](https://user-images.githubusercontent.com/32191031/100719458-a39f5900-33f7-11eb-8cc4-9f718ec5b00b.png)

**Comment by nitroin** [comment]
Of course, thank you @luhan2017.

See here:

```
Publish starting...
{
  "status": "DEPLOY_INFO",
  "message": "/Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/interruption/3-first-visit.it-it.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "/Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/interruption/3_1-first-visit_accomodation.it-it.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "/Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/interruption/3_2-first-visit_nav.it-it.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "/Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/interruption/3_2-first_visit_where.it-it.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "/Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/interruption/3_3-first-visit_have.it-it.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "/Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/interruption/4-stroke-center-infos.it-it.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "/Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/interruption/5-waiting-for.it-it.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "/Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/interruption/6-centers-map.it-it.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "/Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/interruption/8-nutrition.it-it.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "/Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/interruption/ScenarioList.it-it.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "/Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/interruption/SportActivities.it-it.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "/Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/interruption/SportTeam.it-it.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "/Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/interruption/UserProfile.it-it.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "/Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/interruption/Welcome.it-it.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "/Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/interruption/fts-bot-tom.it-it.lu loaded\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "/Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/interruption/ScenarioList.it-it.lu no changes\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "/Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/interruption/SportTeam.it-it.lu no changes\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "/Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/interruption/UserProfile.it-it.lu no changes\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "/Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/interruption/SportActivities.it-it.lu no changes\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "/Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/interruption/fts-bot-tom.it-it.lu no changes\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to /Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/ScenarioList.it-it.lu.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to /Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/SportActivities.it-it.lu.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to /Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/SportTeam.it-it.lu.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to /Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/UserProfile.it-it.lu.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to /Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/fts-bot-tom.it-it.lu.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to /Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/ScenarioList.lu.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to /Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/SportActivities.lu.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to /Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/SportTeam.lu.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to /Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/UserProfile.lu.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to /Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/fts-bot-tom.lu.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to /Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/3-first-visit.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to /Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/3_1-first-visit_accomodation.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to /Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/3_2-first-visit_nav.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to /Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/3_2-first_visit_where.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to /Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/3_3-first-visit_have.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to /Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/4-stroke-center-infos.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to /Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/5-waiting-for.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to /Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/6-centers-map.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to /Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/8-nutrition.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to /Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/ScenarioList.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to /Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/SportActivities.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to /Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/SportTeam.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to /Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/UserProfile.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to /Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/Welcome.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to /Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/fts-bot-tom.lu.qna.dialog\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "Writing to /Users/redacted/BotFrameworkComposer/publishBots/87b4a0ada1c721a252f817e75bb0f88f/azurewebapp/ComposerDialogs/generated/luis.settings.dev.westeurope.json\n"
}
{
  "status": "DEPLOY_INFO",
  "message": "lubuild succeed"
}
{
  "status": "DEPLOY_INFO",
  "message": "start publish luis"
}
{
  "status": "DEPLOY_ERROR",
  "message": "{\"name\":\"StatusCodeError\",\"statusCode\":429,\"message\":\"429 - \\\"{\\\\\\\"error\\\\\\\":{\\\\\\\"code\\\\\\\":\\\\\\\"429\\\\\\\",\\\\\\\"message\\\\\\\": \\\\\\\"Requests to the user - Get LUIS azure accounts Operation under LUIS Programmatic APIs v2.0 have exceeded rate limit of your current LUIS.Authoring F0 pricing tier. Please retry after 1 second. To increase your rate limit switch to a paid tier.\\\\\\\"}}\\\"\",\"error\":\"{\\\"error\\\":{\\\"code\\\":\\\"429\\\",\\\"message\\\": \\\"Requests to the user - Get LUIS azure accounts Operation under LUIS Programmatic APIs v2.0 have exceeded rate limit of your current LUIS.Authoring F0 pricing tier. Please retry after 1 second. To increase your rate limit switch to a paid tier.\\\"}}\",\"options\":{},\"response\":{\"statusCode\":429},\"stack\":\"StatusCodeError: 429 - \\\"{\\\\\\\"error\\\\\\\":{\\\\\\\"code\\\\\\\":\\\\\\\"429\\\\\\\",\\\\\\\"message\\\\\\\": \\\\\\\"Requests to the user - Get LUIS azure accounts Operation under LUIS Programmatic APIs v2.0 have exceeded rate limit of your current LUIS.Authoring F0 pricing tier. Please retry after 1 second. To increase your rate limit switch to a paid tier.\\\\\\\"}}\\\"\\n    at new r (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/lib/index.js:2:3724051)\\n    at q.callback (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/lib/index.js:2:3726040)\\n    at q.e.callback.t.callback [as _callback] (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/lib/index.js:2:3725088)\\n    at q.t._callback.t.callback.t.callback (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/lib/index.js:2:3755134)\\n    at q.emit (events.js:210:5)\\n    at q.<anonymous> (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/lib/index.js:2:3767714)\\n    at q.emit (events.js:210:5)\\n    at IncomingMessage.<anonymous> (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/lib/index.js:2:3766546)\\n    at Object.onceWrapper (events.js:299:28)\\n    at IncomingMessage.emit (events.js:215:7)\\n    at endReadableNT (_stream_readable.js:1183:12)\\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\"}"
}
429 - "{\"error\":{\"code\":\"429\",\"message\": \"Requests to the user - Get LUIS azure accounts Operation under LUIS Programmatic APIs v2.0 have exceeded rate limit of your current LUIS.Authoring F0 pricing tier. Please retry after 1 second. To increase your rate limit switch to a paid tier.\"}}"

And for reference, our princings configurations (defaults):

![image](https://user-images.githubusercontent.com/14164969/100857641-363e0780-348d-11eb-9c03-6d465fbadb3d.png)

![image](https://user-images.githubusercontent.com/14164969/100857664-41913300-348d-11eb-8a4d-61a203c9447b.png)

```
