### ISSUE TITLE
bug: when ejecting the js runtime, I get a gyp error 

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Composer#5137]
## Describe the bug

During the ejection of the js runtime, it runs npm install and npm build in the background

This causes a gyp error, and something in the process fails.  If running composer with DEBUG=*, you will see:

```
 composer:extensions:plugin-runtimes npm WARN deprecated @types/moment-timezone@0.5.30: This is a stub types definition. moment-timezone provides its own type definitions, so you do not need this installed.
  composer:extensions:plugin-runtimes No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
  composer:extensions:plugin-runtimes
  composer:extensions:plugin-runtimes No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
  composer:extensions:plugin-runtimes
  composer:extensions:plugin-runtimes No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
  composer:extensions:plugin-runtimes
  composer:extensions:plugin-runtimes gyp: No Xcode or CLT version detected!
  composer:extensions:plugin-runtimes gyp ERR! configure error
  composer:extensions:plugin-runtimes gyp ERR! stack Error: `gyp` failed with exit code: 1
  composer:extensions:plugin-runtimes gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
  composer:extensions:plugin-runtimes gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
  composer:extensions:plugin-runtimes gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
  composer:extensions:plugin-runtimes gyp ERR! System Darwin 19.6.0
  composer:extensions:plugin-runtimes gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
  composer:extensions:plugin-runtimes gyp ERR! cwd /Users/benbrown/Desktop/EmptyBot-3/runtime/node_modules/dtrace-provider
  composer:extensions:plugin-runtimes gyp ERR! node -v v14.15.0
  composer:extensions:plugin-runtimes gyp ERR! node-gyp -v v5.1.0
  composer:extensions:plugin-runtimes gyp ERR! not ok
  composer:extensions:plugin-runtimes npm WARN node-runtime@1.0.0 No repository field.
  composer:extensions:plugin-runtimes
```

## Version

`main`

## Browser

- [x] Chrome

## OS

- [x] macOS

## To Reproduce

1. Run composer using DEBUG=* yarn start
2. Create a new bot
3. eject the runtime, select JS
4. Look at the output as Composer attempts to build the application for the first time...
5. this error does not cause an alert in the composer UI... and does not seem to impact the ability to start the bot.

**Comment by benbrown** [comment]
This may have been a problem with my system, it seems to have resolved after I followed these instructions:

https://medium.com/flawless-app-stories/gyp-no-xcode-or-clt-version-detected-macos-catalina-anansewaa-38b536389e8d
