### ISSUE TITLE
Bot fails to start after update to v1.3.0

### ISSUE THREAD

**Issue by ysnoek2** [microsoft/BotFramework-Composer#5390]
## Describe the bug

After updating to v1.3.0 the bot does not start in the emulator. 
![image](https://user-images.githubusercontent.com/76207835/102606407-fd599000-4126-11eb-8d75-0a49e292b15e.png)

Publishing to azure is still going fine
![image](https://user-images.githubusercontent.com/76207835/102606351-e74bcf80-4126-11eb-9f2b-38964e576d56.png)

## Version

1.3.0

## Browser

- [ ] Electron distribution
- Chrome
- [ ] Safari
- [ ] Firefox
- Edge

## OS

- [ ] macOS
- Windows
- [ ] Ubuntu

## To Reproduce

1. Open bot
2. Click on start bot or restart bot

## Expected behavior

Bot opens in emulator

**Comment by JohnRobertGreen** [comment]
Having the same problem. Cannot find any logs that might help solve the problem. Has ground the project to a halt.

**Comment by luhan2017** [comment]
@ysnoek2 @JohnRobertGreen Could you help try the following steps to get more logs?

1. go to the project settings page and toggle "Use custom runtime"
![image](https://user-images.githubusercontent.com/32191031/102838314-d4900e00-4438-11eb-96c6-b0fae04cf90a.png)
F
2. after the runtime is placed in your bot folder, go to that folder and run "dotnet build" in cmd tool. For example:
C:\Users\luhan\EchoBot-19\runtime>dotnet run --project azurewebapp

And then paste the error messages here. Thanks a lot!

**Comment by JohnRobertGreen** [comment]
Apologies but I've downgrade to Composer 1.21 to keep my project moving. I'll try to re-produce the issue in the next or so.

**Comment by EricDahlvang** [comment]
Have you tried exporting the runtime, and running the solution from Visual Studio?  (when I've seen this exception, i've been able to gather more information via running from Visual Studio)

**Comment by ysnoek2** [comment]
@luhan2017 I followed your steps and tried connecting manually with the emulator and got this exeption:

PS C:\Users\snoekya\Desktop\Stage\BotComposer_project\Isabot\runtime> dotnet run --project azurewebapp
C:\Users\snoekya\Desktop\Stage\BotComposer_project\Isabot\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj : warning
 NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2
, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the 
project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
C:\Users\snoekya\Desktop\Stage\BotComposer_project\Isabot\runtime\core\Microsoft.BotFramework.Composer.Core.csproj : warning NU1701: 
Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFra
mework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project t
arget framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project. [C:\Users\snoekya\Desktop\St
age\BotComposer_project\Isabot\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\Users\snoekya\Desktop\Stage\BotComposer_project\Isabot\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj : warning
 NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2
, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the 
project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
C:\Users\snoekya\Desktop\Stage\BotComposer_project\Isabot\runtime\core\Microsoft.BotFramework.Composer.Core.csproj : warning NU1701: 
Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFra
mework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project t
arget framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:3979
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\snoekya\Desktop\Stage\BotComposer_project\Isabot\runtime\azurewebapp
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://localhost:3979/api/messages application/json 626
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Microsoft.BotFramework.Composer.WebAppTemplates.Controllers.BotController.PostAsync (Microsoft.BotFramework
.Composer.WebApp)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "Post", controller = "Bot"}. Executing controller action with signature System.Threading.Tasks.Tas
k PostAsync() on controller Microsoft.BotFramework.Composer.WebAppTemplates.Controllers.BotController (Microsoft.BotFramework.Compose
r.WebApp).
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Executing action method Microsoft.BotFramework.Composer.WebAppTemplates.Controllers.BotController.PostAsync (Microsoft.BotFrame
work.Composer.WebApp) - Validation state: Valid
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action Microsoft.BotFramework.Composer.WebAppTemplates.Controllers.BotController.PostAsync (Microsoft.BotFramework.Com
poser.WebApp) in 922.6087ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Microsoft.BotFramework.Composer.WebAppTemplates.Controllers.BotController.PostAsync (Microsoft.BotFramework.
Composer.WebApp)'
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM5BT3PP82NS", Request id "0HM5BT3PP82NS:00000001": An unhandled exception was thrown by the application.
System.ArgumentNullException: Value cannot be null. (Parameter 'clientSecret')
   at Microsoft.IdentityModel.Clients.ActiveDirectory.ClientCredential..ctor(String clientId, String clientSecret)
   at Microsoft.Bot.Connector.Authentication.MicrosoftAppCredentials.<BuildAuthenticator>b__14_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Bot.Connector.Authentication.AppCredentials.<BuildIAuthenticator>b__36_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Bot.Connector.Authentication.AppCredentials.GetTokenAsync(Boolean forceRefresh)
   at Microsoft.Bot.Connector.Authentication.AppCredentials.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken can
cellationToken)
   at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity a
ctivity, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String a
ctivityId, Activity activity, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotFrameworkAdapter.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToke
n cancellationToken)
   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass30_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(String textReplyToSend, String speak, String inputHint, CancellationToken c
ancellationToken)
   at Microsoft.BotFramework.Composer.WebAppTemplates.Startup.<>c__DisplayClass12_0.<<GetBotAdapter>b__0>d.MoveNext() in C:\Users\sno
ekya\Desktop\Stage\BotComposer_project\Isabot\runtime\azurewebapp\Startup.cs:line 122
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken canc
ellationToken)
   at Microsoft.Bot.Builder.BotFrameworkAdapter.ProcessActivityAsync(ClaimsIdentity claimsIdentity, Activity activity, BotCallbackHan
dler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotFrameworkAdapter.ProcessActivityAsync(String authHeader, Activity activity, BotCallbackHandler callbac
k, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Integration.AspNet.Core.BotFrameworkHttpAdapter.ProcessAsync(HttpRequest httpRequest, HttpResponse httpRe
sponse, IBot bot, CancellationToken cancellationToken)
   at Microsoft.BotFramework.Composer.WebAppTemplates.Controllers.BotController.PostAsync() in C:\Users\snoekya\Desktop\Stage\BotComp
oser_project\Isabot\runtime\azurewebapp\Controllers\BotController.cs:line 38
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, Ob
jectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker
 invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionIn
voker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompl
eted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker
 invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Tas
k lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger lo
gger)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 1010.8007ms 500

**Comment by ysnoek2** [comment]
Downloading the 3.1 .NET Core sdk did the trick for my project!

https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-3.1.404-windows-x64-installer

**Comment by tonyanziano** [comment]
.NET sdk 3.1 is a requirement, so that is expected, however, the `[object object]` error message appears to be a potential bug.

**Comment by MPCoreDeveloper** [comment]
> .NET sdk 3.1 is a requirement, so that is expected, however, the `[object object]` error message appears to be a potential bug.

According to the MSFT Bot documentation only the runtime is required note there are 2 separate downloads https://dotnet.microsoft.com/download

Create a bot with .Net:   https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-sdk-quickstart?view=azure-bot-service-4.0

Prerequisites
ASP.NET Core Runtime 3.1
Bot Framework Emulator
Knowledge of ASP.NET Core and asynchronous programming in C#

Maybe it would be a good idea to change it there to the SDK?
ASP.NET Core Runtime 3.1 SDK

**Comment by luhan2017** [comment]
@VanyLaw , could you help check the error log logic in the local publish extension? we should show meaningful error log instead of [object object].
