### ISSUE TITLE
 Error: https://registry.yarnpkg.com/@bfc%2feslint-plugin-bfcomposer: Not found

### ISSUE THREAD

**Issue by Heinzfb** [microsoft/BotFramework-Composer#5478]
Hi there,

do you know how to solve this? 
My Steps:
>Download Composer as .zip from Resp
>unpack
>Open in VS
>run yarn install
>error

Thanks for your help!

Yarn version: 
  1.22.10

Node version: 
  14.15.4

Platform: 
  win32 x64

Trace: 
  Error: https://registry.yarnpkg.com/@bfc%2feslint-plugin-bfcomposer: Not found
      at Request.params.callback [as _callback] (C:\Users\)
      at Request.self.callback (C:\Users\)
      at Request.emit (events.js:315:20)
      at Request.<anonymous> (C:\Users\)
      at Request.emit (events.js:315:20)
      at IncomingMessage.<anonymous> (C:\Users\)
      at Object.onceWrapper (events.js:421:28)
      at IncomingMessage.emit (events.js:327:22)
      at endReadableNT (internal/streams/readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by GeoffCoxMSFT** [comment]
@Heinzfb - On windows if you download as zip, sometimes the zip is marked as blocked.  Could you verify that you have unblocked the zip file before unzipping.  You can bring up properties and see if there is a checkbox for unblocking.

![image](https://user-images.githubusercontent.com/28762486/104352187-359c8600-54bb-11eb-8e5c-607fbc73404e.png)

**Comment by Heinzfb** [comment]
Hey there,

thanks for the quick answer. I do not have the win10 Pro version. - gpedit.msc - is not intalled by default. So I can't check by bringing this property up. But no Problem, I will get it via clone.  :)
