### ISSUE TITLE
Couldn't Start Composer under Linux Environment

### ISSUE THREAD

**Issue by zidaneymar** [microsoft/BotFramework-Composer#5510]
## Describe the bug
yarn start fails under linux environment
```
$ yarn start
$ cross-env NODE_ENV=production PORT=3000 yarn start:server
$ yarn workspace @bfc/server start
$ node build/init.js
internal/modules/cjs/loader.js:1122
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: libgomp.so.1: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/azureuser/BotFramework-Composer/Composer/node_modules/@microsoft/bf-orchestrator/lib/labelresolver.js:12:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/bin/node
Arguments: /home/azureuser/.npm-global/lib/node_modules/yarn/lib/cli.js start
Directory: /home/azureuser/BotFramework-Composer/Composer/packages/server
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
<!-- Give a clear and concise description of what the bug is. -->
```
## Version
Linux: 18.04
Node: v14.15.4
NPM: 6.14.10
yarn: 1.22.10

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [x] Ubuntu

## To Reproduce

1. Go to Composer folder
2. Execute "yarn && yarn build && yarn start"
3. Would fail at yarn start

## Expected behavior
yarn start should work properly

**Comment by zidaneymar** [comment]
Fixed with:
```
sudo apt-get install libgomp1
```
