### ISSUE TITLE
Error when publishing CREATE_QNA_ERROR 

### ISSUE THREAD

**Issue by tiagonmas** [microsoft/BotFramework-Composer#5663]
## Describe the bug
Receiving a "Provision failure" error when publishing a bot.
CREATE_QNA_ERROR - Error - The network connectivity issue encountered for 'Microsoft.Search'; cannot fulfill the request. detail message can see provision.tiagoandazure.log in your bot folder

logfile
```
{
  "profileName": "tiagoandazure",
  "jobId": "66e9445e-1963-4a4e-8b42-499dec2e140b",
  "projectId": "39162.04744549128",
  "time": "2021-01-31T18:05:37.618Z",
  "log": [
    "Creating Azure resources...",
    "Checking the Existence of the Resource Group ...",
    "Creating Resource Group ...",
    "> Creating App Registration ...",
    "Start to add password for App, Id : XXXXa24-01d6-4147-b522-9828dde87585",
    "> Create App Registration Success! ID: XXXXX5a24-01d6-4147-b522-9828dde87585",
    "Deploying Web App Resource ...",
    "Deploying Bot Resource ...",
    "Deploying Application Insights Resource ...",
    "> Linking Application Insights settings to Bot Service ...",
    "> AppInsights AppId: XXXXX-afa7-4b14-b7a7-a642de8e00a9 ...",
    "> AppInsights InstrumentationKey: XXXXXa-810f-4dcc-a4a2-aba851d026ab ...",
    "> AppInsights ApiKey: XXXXXXp37msvdncbyista1zr3ztved44cscvhvrf6 ...",
    "> Linking Application Insights settings to Bot Service Success!",
    "Deploying Blob Storage Resource ...",
    "Deploying Luis Authoring Resource ...",
    "Deploying Luis Resource ...",
    "Deploying QnA Resource ...",
    "{\"stack\":\"Error: The network connectivity issue encountered for 'Microsoft.Search'; cannot fulfill the request.\\n    at new t (C:\\\\Users\\\\tiagoand\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:479:306948)\\n    at C:\\\\Users\\\\tiagoand\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:479:320285\",\"message\":\"The network connectivity issue encountered for 'Microsoft.Search'; cannot fulfill the request.\",\"code\":\"BadGatewayConnection\",\"statusCode\":502,\"request\":{\"body\":\"{\\\"location\\\":\\\"westus\\\",\\\"properties\\\":{\\\"replicaCount\\\":1,\\\"partitionCount\\\":1,\\\"hostingMode\\\":\\\"default\\\"},\\\"sku\\\":{\\\"name\\\":\\\"standard\\\"}}\"},\"response\":{\"body\":\"{\\\"error\\\":{\\\"code\\\":\\\"BadGatewayConnection\\\",\\\"message\\\":\\\"The network connectivity issue encountered for 'Microsoft.Search'; cannot fulfill the request.\\\"}}\"},\"body\":{\"message\":\"The network connectivity issue encountered for 'Microsoft.Search'; cannot fulfill the request.\",\"code\":\"BadGatewayConnection\"},\"innerError\":{\"stack\":\"Error: The network connectivity issue encountered for 'Microsoft.Search'; cannot fulfill the request.\\n    at new t (C:\\\\Users\\\\tiagoand\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:479:306948)\\n    at C:\\\\Users\\\\tiagoand\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:479:320285\",\"message\":\"The network connectivity issue encountered for 'Microsoft.Search'; cannot fulfill the request.\",\"code\":\"BadGatewayConnection\",\"statusCode\":502,\"request\":{\"body\":\"{\\\"location\\\":\\\"westus\\\",\\\"properties\\\":{\\\"replicaCount\\\":1,\\\"partitionCount\\\":1,\\\"hostingMode\\\":\\\"default\\\"},\\\"sku\\\":{\\\"name\\\":\\\"standard\\\"}}\"},\"response\":{\"body\":\"{\\\"error\\\":{\\\"code\\\":\\\"BadGatewayConnection\\\",\\\"message\\\":\\\"The network connectivity issue encountered for 'Microsoft.Search'; cannot fulfill the request.\\\"}}\"},\"body\":{\"message\":\"The network connectivity issue encountered for 'Microsoft.Search'; cannot fulfill the request.\",\"code\":\"BadGatewayConnection\"},\"innerError\":{\"stack\":\"Error: The network connectivity issue encountered for 'Microsoft.Search'; cannot fulfill the request.\\n    at new t (C:\\\\Users\\\\tiagoand\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:479:306948)\\n    at C:\\\\Users\\\\tiagoand\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:479:320285\",\"message\":\"The network connectivity issue encountered for 'Microsoft.Search'; cannot fulfill the request.\",\"code\":\"BadGatewayConnection\",\"statusCode\":502,\"request\":{\"body\":\"{\\\"location\\\":\\\"westus\\\",\\\"properties\\\":{\\\"replicaCount\\\":1,\\\"partitionCount\\\":1,\\\"hostingMode\\\":\\\"default\\\"},\\\"sku\\\":{\\\"name\\\":\\\"standard\\\"}}\"},\"response\":{\"body\":\"{\\\"error\\\":{\\\"code\\\":\\\"BadGatewayConnection\\\",\\\"message\\\":\\\"The network connectivity issue encountered for 'Microsoft.Search'; cannot fulfill the request.\\\"}}\"},\"body\":{\"message\":\"The network connectivity issue encountered for 'Microsoft.Search'; cannot fulfill the request.\",\"code\":\"BadGatewayConnection\"}}}}",
    "{\"name\":\"CREATE_QNA_ERROR\",\"message\":\"Error - The network connectivity issue encountered for 'Microsoft.Search'; cannot fulfill the request.\",\"stack\":\"Error\\n    at new n (C:\\\\Users\\\\tiagoand\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:18:97996)\\n    at Object.t.createCustomizeError (C:\\\\Users\\\\tiagoand\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:18:98326)\\n    at e.<anonymous> (C:\\\\Users\\\\tiagoand\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:479:21360)\\n    at C:\\\\Users\\\\tiagoand\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:479:12347\\n    at Object.throw (C:\\\\Users\\\\tiagoand\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:479:12452)\\n    at s (C:\\\\Users\\\\tiagoand\\\\AppData\\\\Local\\\\Programs\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\lib\\\\node\\\\index.js:479:11217)\"}",
    "CREATE_QNA_ERROR - Error - The network connectivity issue encountered for 'Microsoft.Search'; cannot fulfill the request.\n        detail message can see provision.tiagoandazure.log in your bot folder"
  ]
}

```

## Version

v1.3.1-nightly 204049.df53a98

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a new Bot from a sample
2. Create a publish profile that includes QNA maker

**Comment by cwhitten** [comment]
@tiagonmas could there have been a network interruption when you tried this? Can you try again?

**Comment by tiagonmas** [comment]
I've received the same error on 2 different ocassions. Will try again with logging enabled.

**Comment by tiagonmas** [comment]
Tried again and saw the same error. I'm only able to provision things if i remove QNA option.
The error seems to be "Cannot provision service 'tiagonmashomeassistant-qna-search' because a service with this name is already in use, or another request to provision a service with this name is still in progress RequestId: f021334f-5da1-4cc7-9e52-14f604dadbc9\n" +"

here are the command line logs (I started composer from a powershell)
[botcomposerlog.txt](https://github.com/microsoft/BotFramework-Composer/files/5925119/botcomposerlog.txt)

Composer UI error:
CREATE_QNA_ERROR - Error - Cannot provision service 'tiagonmashomeassistant-qna-search' because a service with this name is already in use, or another request to provision a service with this name is still in progress RequestId: f021334f-5da1-4cc7-9e52-14f604dadbc9 detail message can see provision.tiagoandazure2.log in your bot folder

All other resources were createad without issues
![image](https://user-images.githubusercontent.com/42462/106882222-6a74b500-66d6-11eb-869c-0d7ed1041f50.png)

**Comment by cwhitten** [comment]
Hello @tiagonmas - I've forwarded this issue to the QnA Maker team for additional troubleshooting.

**Comment by pchoudhari** [comment]
@tiagonmas , as the error says, can you confirm that another search service with the same name doesn't exist? Can you change the name of the azure search and try again?

**Comment by tiagonmas** [comment]
This is a deployment to a new resurce group that is created by Composer. Everything is new. QNA is the only one that fails ... and tried multiple times, with multiple names. I guess the issue might not be with QNA but the actual deployment script that the composer is running.
