### ISSUE TITLE
Node 14 warnings

### ISSUE THREAD

**Issue by hatpick** [microsoft/BotFramework-Composer#5833]
After updating the dev environment to use node v14.15.5 yarn build throws a long list of warnings related to shelljs dependency used by eslint version that format-message-cli is using.

(node:12043) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:650:11)
    at Object.get (internal/modules/cjs/loader.js:664:5)
    at Object._register [as register] (/Users/sorgh/Documents/github/BotFramework-Composer/Composer/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/Users/sorgh/Documents/github/BotFramework-Composer/Composer/node_modules/shelljs/src/cat.js:4:8)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
(node:12043) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:650:11)
    at Object.get (internal/modules/cjs/loader.js:664:5)
    at Object._register [as register] (/Users/sorgh/Documents/github/BotFramework-Composer/Composer/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/Users/sorgh/Documents/github/BotFramework-Composer/Composer/node_modules/shelljs/src/cd.js:4:8)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
(node:12043) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:650:11)
    at Object.get (internal/modules/cjs/loader.js:664:5)
    at Object._register [as register] (/Users/sorgh/Documents/github/BotFramework-Composer/Composer/node_modules/shelljs/src/common.js:455:12)
    at Object.<anonymous> (/Users/sorgh/Documents/github/BotFramework-Composer/Composer/node_modules/shelljs/src/chmod.js:32:8)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
....
.... truncated by @hatpick 
....

**Comment by cwhitten** [comment]
No longer necessary as the change to 14 was backed out
