### ISSUE TITLE
hand off to azure admin

### ISSUE THREAD

**Issue by JaskeeratBedi-cmk** [microsoft/BotFramework-Composer#6907]
The Copy needs to be updated based on design. Several problems with the copy ( see attached screenshots)

![Frame 61662](https://user-images.githubusercontent.com/67944302/114604366-a6d00e80-9c4d-11eb-9987-0bc20a171ac8.png)

**Comment by GeoffCoxMSFT** [comment]
@Dewain27 Since you and Ben revisited the copy for this dialog, could you reconcile the text from Jas with your text?

**Comment by JonathanFingold** [comment]
@Dewain27 This is actually a P0 in terms of an admin being able to complete this process.

**Comment by JonathanFingold** [comment]
```powershell
PS C:\Windows\System32> az account set --subscription "FUSE Temporary"
PS C:\Windows\System32> node provisionComposer.js --subscriptionId "FUSE Temporary" --name v-jofin-bot-1 --appPassword=At_Least16-characters!!! --location=westus --resourceGroup=v-jofin-0426 --createLuisResource=false --createLuisAuthoringResource=false --createCosmosDb=false --createStorage=false --createAppInsights=false --createQnAResource=false
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module 'C:\Windows\System32\provisionComposer.js'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:686:27)←[39m
←[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)←[39m
←[90m    at internal/main/run_main_module.js:17:11←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
```

**Comment by mareekuh** [comment]
Added UX copy to spreadsheet (provisioning and publishing tab).
Will propose copy asap.
