### ISSUE TITLE
Ejected runtime errors during build dur to SetSpeakMiddleware error (CS0104)

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#6918]
Tried to run a skill that worked just fine prior to the last nighly build update.
During Orchestrator installation, it required ejecting the skill so I did.
Tried to build and hit the following:

```
Error occurred building the bot

Message:
Command failed: dotnet build
Command:
dotnet build
Stack Trace:
Error: Command failed: dotnet build

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
Output:
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project. [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\ComposerRuntime.sln]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\core\Microsoft.BotFramework.Composer.Core.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project. [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\ComposerRuntime.sln]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\tests\Microsoft.BotFramework.Composer.Tests.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project. [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\ComposerRuntime.sln]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurefunctions\Microsoft.BotFramework.Composer.Functions.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project. [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\ComposerRuntime.sln]
  Restored C:\workspace\botroot\TEMPPLAY\SkillB\runtime\customaction\Microsoft.BotFramework.Composer.CustomAction.csproj (in 2.19 sec).
  Restored C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurefunctions\Microsoft.BotFramework.Composer.Functions.csproj (in 2.29 sec).
  Restored C:\workspace\botroot\TEMPPLAY\SkillB\runtime\core\Microsoft.BotFramework.Composer.Core.csproj (in 2.28 sec).
  Restored C:\workspace\botroot\TEMPPLAY\SkillB\runtime\tests\Microsoft.BotFramework.Composer.Tests.csproj (in 2.28 sec).
  1 of 5 projects are up-to-date for restore.
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\core\Microsoft.BotFramework.Composer.Core.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\tests\Microsoft.BotFramework.Composer.Tests.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurefunctions\Microsoft.BotFramework.Composer.Functions.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
  Microsoft.BotFramework.Composer.Core -> C:\workspace\botroot\TEMPPLAY\SkillB\runtime\core\bin\Debug\netcoreapp3.1\Microsoft.BotFramework.Composer.Core.dll
  Microsoft.BotFramework.Composer.CustomAction -> C:\workspace\botroot\TEMPPLAY\SkillB\runtime\customaction\bin\Debug\netcoreapp3.1\Microsoft.BotFramework.Composer.CustomAction.dll
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(74,33): error CS0104: 'SetSpeakMiddleware' is an ambiguous reference between 'Microsoft.Bot.Builder.SetSpeakMiddleware' and 'Microsoft.BotFramework.Composer.Core.SetSpeakMiddleware' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(149,97): error CS0104: 'AllowedCallersClaimsValidator' is an ambiguous reference between 'Microsoft.BotFramework.Composer.WebAppTemplates.Authorization.AllowedCallersClaimsValidator' and 'Microsoft.Bot.Connector.Authentication.AllowedCallersClaimsValidator' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(152,13): warning CS0618: 'ComponentRegistration' is obsolete: 'Use `BotComponent` for new components.' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(152,13): warning CS0618: 'ComponentRegistration.Add(ComponentRegistration)' is obsolete: 'Use resource explorer' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(153,13): warning CS0618: 'ComponentRegistration' is obsolete: 'Use `BotComponent` for new components.' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(153,43): warning CS0618: 'DeclarativeComponentRegistration' is obsolete: 'Use `DeclarativeBotComponent`.' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(153,13): warning CS0618: 'ComponentRegistration.Add(ComponentRegistration)' is obsolete: 'Use resource explorer' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(154,13): warning CS0618: 'ComponentRegistration' is obsolete: 'Use `BotComponent` for new components.' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(154,43): warning CS0618: 'AdaptiveComponentRegistration' is obsolete: 'Use `AdaptiveBotComponent` instead.' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(154,13): warning CS0618: 'ComponentRegistration.Add(ComponentRegistration)' is obsolete: 'Use resource explorer' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(155,13): warning CS0618: 'ComponentRegistration' is obsolete: 'Use `BotComponent` for new components.' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(155,13): warning CS0618: 'ComponentRegistration.Add(ComponentRegistration)' is obsolete: 'Use resource explorer' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(156,13): warning CS0618: 'ComponentRegistration' is obsolete: 'Use `BotComponent` for new components.' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(156,13): warning CS0618: 'ComponentRegistration.Add(ComponentRegistration)' is obsolete: 'Use resource explorer' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(157,13): warning CS0618: 'ComponentRegistration' is obsolete: 'Use `BotComponent` for new components.' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(157,13): warning CS0618: 'ComponentRegistration.Add(ComponentRegistration)' is obsolete: 'Use resource explorer' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(163,67): error CS0104: 'SkillConversationIdFactory' is an ambiguous reference between 'Microsoft.BotFramework.Composer.Core.SkillConversationIdFactory' and 'Microsoft.Bot.Builder.Skills.SkillConversationIdFactory' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
  Microsoft.BotFramework.Composer.Functions -> C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurefunctions\bin\Debug\netcoreapp3.1\bin\Microsoft.BotFramework.Composer.Functions.dll

Build FAILED.

C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project. [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\ComposerRuntime.sln]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\core\Microsoft.BotFramework.Composer.Core.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project. [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\ComposerRuntime.sln]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\tests\Microsoft.BotFramework.Composer.Tests.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project. [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\ComposerRuntime.sln]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurefunctions\Microsoft.BotFramework.Composer.Functions.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project. [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\ComposerRuntime.sln]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\core\Microsoft.BotFramework.Composer.Core.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\tests\Microsoft.BotFramework.Composer.Tests.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurefunctions\Microsoft.BotFramework.Composer.Functions.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(152,13): warning CS0618: 'ComponentRegistration' is obsolete: 'Use `BotComponent` for new components.' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(152,13): warning CS0618: 'ComponentRegistration.Add(ComponentRegistration)' is obsolete: 'Use resource explorer' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(153,13): warning CS0618: 'ComponentRegistration' is obsolete: 'Use `BotComponent` for new components.' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(153,43): warning CS0618: 'DeclarativeComponentRegistration' is obsolete: 'Use `DeclarativeBotComponent`.' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(153,13): warning CS0618: 'ComponentRegistration.Add(ComponentRegistration)' is obsolete: 'Use resource explorer' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(154,13): warning CS0618: 'ComponentRegistration' is obsolete: 'Use `BotComponent` for new components.' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(154,43): warning CS0618: 'AdaptiveComponentRegistration' is obsolete: 'Use `AdaptiveBotComponent` instead.' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(154,13): warning CS0618: 'ComponentRegistration.Add(ComponentRegistration)' is obsolete: 'Use resource explorer' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(155,13): warning CS0618: 'ComponentRegistration' is obsolete: 'Use `BotComponent` for new components.' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(155,13): warning CS0618: 'ComponentRegistration.Add(ComponentRegistration)' is obsolete: 'Use resource explorer' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(156,13): warning CS0618: 'ComponentRegistration' is obsolete: 'Use `BotComponent` for new components.' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(156,13): warning CS0618: 'ComponentRegistration.Add(ComponentRegistration)' is obsolete: 'Use resource explorer' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(157,13): warning CS0618: 'ComponentRegistration' is obsolete: 'Use `BotComponent` for new components.' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(157,13): warning CS0618: 'ComponentRegistration.Add(ComponentRegistration)' is obsolete: 'Use resource explorer' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(74,33): error CS0104: 'SetSpeakMiddleware' is an ambiguous reference between 'Microsoft.Bot.Builder.SetSpeakMiddleware' and 'Microsoft.BotFramework.Composer.Core.SetSpeakMiddleware' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(149,97): error CS0104: 'AllowedCallersClaimsValidator' is an ambiguous reference between 'Microsoft.BotFramework.Composer.WebAppTemplates.Authorization.AllowedCallersClaimsValidator' and 'Microsoft.Bot.Connector.Authentication.AllowedCallersClaimsValidator' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Startup.cs(163,67): error CS0104: 'SkillConversationIdFactory' is an ambiguous reference between 'Microsoft.BotFramework.Composer.Core.SkillConversationIdFactory' and 'Microsoft.Bot.Builder.Skills.SkillConversationIdFactory' [C:\workspace\botroot\TEMPPLAY\SkillB\runtime\azurewebapp\Microsoft.BotFramework.Composer.WebApp.csproj]
    22 Warning(s)
    3 Error(s)

Time Elapsed 00:00:32.10
Killed:
Code:
1
```

**Comment by cwhitten** [comment]
@scheyal we don't be fixing bugs in the existing runtime template, but I would encourage you to verify that your scenarios work on the new runtime template
