### ISSUE TITLE
Export fails: .csproj is missing from destination

### ISSUE THREAD

**Issue by scheyal** [microsoft/BotFramework-Composer#7231]
## Repro
1. Create a bot project (in my case with qna/luis/remote-skill)
2. Export
3. Extract .zip
4. Restart Composer
5. Navigate to new location
6. Try to build
7. Error: No .csproj: ```Command failed : The project file '...\OrchestratorDispatch\OrchestratorDispatch.csproj'  does not exist.```

## Build Error
```
Error occurred building the bot

Message:
Command failed: dotnet user-secrets init --project OrchestratorDispatch.csproj
Command failed : The project file 'c:\workspace\botroot\sdk\Orchestrator\Samples\Composer\OrchestratorDispatch\OrchestratorDispatch.csproj' does not exist.
Command:
dotnet user-secrets init --project OrchestratorDispatch.csproj
Stack Trace:
Error: Command failed: dotnet user-secrets init --project OrchestratorDispatch.csproj
Command failed : The project file 'c:\workspace\botroot\sdk\Orchestrator\Samples\Composer\OrchestratorDispatch\OrchestratorDispatch.csproj' does not exist.

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
Output:
System.IO.FileNotFoundException: The project file 'c:\workspace\botroot\sdk\Orchestrator\Samples\Composer\OrchestratorDispatch\OrchestratorDispatch.csproj' does not exist.
   at Microsoft.Extensions.SecretManager.Tools.Internal.MsBuildProjectFinder.FindMsBuildProject(String project)
   at Microsoft.Extensions.SecretManager.Tools.Internal.InitCommand.ResolveProjectPath(String name, String path)
   at Microsoft.Extensions.SecretManager.Tools.Internal.InitCommand.Execute(CommandContext context)
   at Microsoft.Extensions.SecretManager.Tools.Internal.InitCommand.Execute(CommandContext context, String workingDirectory)
   at Microsoft.Extensions.SecretManager.Tools.Internal.InitCommandFactory.Execute(CommandContext context, String workingDirectory)
   at Microsoft.Extensions.SecretManager.Tools.Program.RunInternal(String[] args)
   at Microsoft.Extensions.SecretManager.Tools.Program.TryRun(String[] args, Int32& returnCode)
Killed:
Code:
1
Stderr:
Command failed : The project file 'c:\workspace\botroot\sdk\Orchestrator\Samples\Composer\OrchestratorDispatc
```

**Comment by cwhitten** [comment]
We need to update the export functionality to include the new project shape. Needs to _not_ include `obj` or `bin` directories.

**Comment by scheyal** [comment]
Reprioritized to P0. Justification:
If you expose an export button, you must be able to use the exported project. The export functionality is completely broken without this fix. I'm not aware of a workaround (other than copying the entire project, which is not export anymore).

**Comment by cwhitten** [comment]
@scheyal the workaround is to simply navigate to the directory outside of composer and archive it. 

Don't worry, a fix is being reviewed and will make it in R13.
