### ISSUE TITLE
[Bug Bash 04/22] Auth fails if you are not logged into Azure in Edge

### ISSUE THREAD

**Issue by rsullivan00** [microsoft/BotFramework-Composer#7276]
**Repro**

- Make a Azure Bot resource in Azure in a private Edge window
- Click "Open in Composer" in Azure to open Composer desktop
- Create a bot from the Responding with cards sample
- Click "Publish"
- Select the bot, select "Publish selected bots"
- On auth popup, put in email from the Azure account
- MFA with MS Authenticator

Expected:
- Publish succeeds using the account you just authenticated with

Actual:
- Auth errors

![image](https://user-images.githubusercontent.com/3654176/115789355-de3f6900-a379-11eb-99ee-4697e82048ef.png)

Console
![image](https://user-images.githubusercontent.com/3654176/115789335-d4b60100-a379-11eb-86f7-97b5e57b021b.png)

Text from a retry:

```
11.a570a28e.chunk.js:1025 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: Thu Apr 22 2021 14:24:30 GMT-0700 (Pacific Daylight Time), _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (http://localhost:5000/static/js/11.a570a28e.chunk.js:1028:3)
    at Si (http://localhost:5000/static/js/11.a570a28e.chunk.js:1028:26090)
    at ha (http://localhost:5000/static/js/11.a570a28e.chunk.js:1028:30229)
    at Do (http://localhost:5000/static/js/11.a570a28e.chunk.js:1028:30083)
    at Po (http://localhost:5000/static/js/11.a570a28e.chunk.js:1028:29772)
    at dt (http://localhost:5000/static/js/11.a570a28e.chunk.js:1028:30635)
    at Lt (http://localhost:5000/static/js/11.a570a28e.chunk.js:1028:30674)
    at r (http://localhost:5000/static/js/11.a570a28e.chunk.js:1025:89)
    at O (http://localhost:5000/static/js/main.706dddfc.chunk.js:600:20550)
    at onRender (http://localhost:5000/static/js/19.77c3906d.chunk.js:259:2263)
D @ 11.a570a28e.chunk.js:1025
:5000/api/publish/95985.89974507908/status/default:1 Failed to load resource: the server responded with a status of 404 (Not Found)
main.706dddfc.chunk.js:611 Could not find language import file RespondingWithCardsSample-0
N @ main.706dddfc.chunk.js:611
:5000/api/auth/getARMTokenForTenant?tenantId=771c292f-a335-4f42-b122-21701de5a6b9:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
main.706dddfc.chunk.js:202 Error: Recieved an error from AAD. Code: 'invalid_grant' description: '(pii)' correlation id: '52588e35-66d9-410b-8865-3e9b2c48c47b' suberror: 'basic_action'
    at Object.<anonymous> (main.706dddfc.chunk.js:724)
    at Generator.next (<anonymous>)
    at j (main.706dddfc.chunk.js:724)
unhandledrejectionHandler @ main.706dddfc.chunk.js:202
main.706dddfc.chunk.js:623 Error: {"summary":"Something went wrong!"}
```

This is my first time installing/using desktop Composer, so possibly missing some existing state that others have.

**Comment by rsullivan00** [comment]
After messing around a bit more, this works if I log into the Azure account in Edge--previously I was using a private Edge window to create the Azure resources, and my non-private edge was not authenticated into Azure.

This may mean that users using non-Edge would also experience this issue.

**Comment by cwhitten** [comment]
Hey @rsullivan00 it looks like you aren't using the preview build of Composer. Can you navigate to the Settings page in Composer and turn on "Early adopters", then Help -> Check for updates from the application menu. 

After this please try again

**Comment by rsullivan00** [comment]
Auth works on the preview build. Thanks @cwhitten , closing
