### ISSUE TITLE
Errors converting bot from 1.4 to adaptive runtime

### ISSUE THREAD

**Issue by mewa1024** [microsoft/BotFramework-Composer#7373]
## Describe the bug

I was testing the part of the Composer 1.4 to Composer 2.0 migration in which the user opens a bot created in 1.4 in 2.0 and chooses to convert to the new format. (Using a build created for testing this flow--not one of the regular nightlies)

3 issues:
- (minor, but unexpected) In the "Create a bot project" modal, the Name field should be autopopulated with the name of the old bot. Intstead it is a lowercase version of the old bot.
- (already reported in #7091) In the "Create a bot project" modal, the "Runtime" field is empty, and the dropdown menu does not open
- converting was unsuccessful and I got an error (shown below)
- the folder intended for the converted bot was left on disk - related to closed item #6726 ?

## Version

Using Frankenbuild from Chris, Friday 4/23:

Version:  1.4.0
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [x] macOS
- [ ] Windows
- [ ] Ubuntu

## To Reproduce

1. Open the new build of Composer. 
2. Select a 1.4 bot .
3. In the "Convert your project to the latest format" modal, select "Convert."
4. In the "Create a bot project", the name is autopopulated with the original name, but the uppercase has been changed to lowercase, as shown here (my 1.4 bot was "ActionsSample-0":
![image](https://user-images.githubusercontent.com/39317542/116136273-f15a7d80-a686-11eb-8f53-dd3d8c5bbd9d.png)

It's a common pattern when duplicating a file for the UI to autopopulate with the new name, so that part is expected. But the changing the case is not expected.

5. The "Runtime type" field is empty and opening the dropdown menu (click on the down arrow), does nothing:
![image](https://user-images.githubusercontent.com/39317542/116136487-38e10980-a687-11eb-808c-d4430a369b46.png)

6. Click OK.

7. The progress indicators appear are working fine:
![image](https://user-images.githubusercontent.com/39317542/116136575-531ae780-a687-11eb-9717-f1b1bcf8ba47.png)

8. until this error:
![image](https://user-images.githubusercontent.com/39317542/116136603-5b732280-a687-11eb-8ea6-db94b5b98f3f.png)

Expanded:
![image](https://user-images.githubusercontent.com/39317542/116136629-6332c700-a687-11eb-9677-c5c31dbcc8ab.png)

I think I do have node installed: 
![image](https://user-images.githubusercontent.com/39317542/116136715-8493b300-a687-11eb-9e38-a23b9ef2fb62.png)

9. Click OK and return to the home menu. The converted bot project does not appear in the MRU, but it does appear in the Finder:
![image](https://user-images.githubusercontent.com/39317542/116136872-c0c71380-a687-11eb-9225-2e2266d8a979.png)

Had the same errors with the Actions Sample bot and the ToDoWithLUIS bot samples from 1.4.

## Expected behavior

- for the project name, the only change is not to lowercase the project name
- if conversion fails, unused folder should be removed

**Comment by benbrown** [comment]
I am also seeing some new issues:

- [ ] The webapp/functions dropdown is blank
- [ ] Instead of the previous project name, the default name is now `undefined`
- [ ] Missing a change to choose JS or .NET
- [ ] for some reason a bot with an ejected runtime fails #7398

**Comment by sgellock** [comment]
Shiproom - please use this as the tracking but for all migration issues.

**Comment by srinaath** [comment]
Adding another issue seen on the runtime migration branch. The window.isElectron variable is not set due to preload.js script not loading (closely related [fix: refactor way we get COMPOSER\_VERSION by a-b-r-o-w-n · Pull Request #7326 · microsoft/BotFramework-Composer (github.com)](https://github.com/microsoft/BotFramework-Composer/pull/7326)

Any features that need to be enabled specifically in the Electron context are not working on the branch. For ex settings to fetch the latest nightly

![](https://user-images.githubusercontent.com/13004779/116479168-12ac9c80-a834-11eb-862d-409d4be266aa.png)

**Comment by JonathanFingold** [comment]
In Version:  2.0.0-nightly.241421.a3f796f I tried:
- opening https://github.com/tomlm/iciclecreek.bot/tree/master/source/Bots/RepoBot
- Go to the Package Manager view.
- Composer showed me a weird screen and is now mostly locked up, I can't access most of the UI.

![image](https://user-images.githubusercontent.com/35047199/116761855-92ba3a00-a9cd-11eb-89c7-99f6fe980036.png)

**Comment by JonathanFingold** [comment]
Getting very similar behavior in the "Frankenbuild", which still claims to be Version:  2.0.0-nightly.241421.a3f796f.

However, here's output up to this point from the terminal (Windows):

```
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
Fri, 30 Apr 2021 23:22:32 GMT express-session deprecated undefined resave option; provide resave option at resources\app.asar\node_modules\@bfc\server\build\server.js:56:17
Fri, 30 Apr 2021 23:22:32 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at resources\app.asar\node_modules\@bfc\server\build\server.js:56:17
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.


Composer now running at:

http://localhost:5000

GET / 200 8.651 ms - 898
Checking for update
Update for version 2.0.0-nightly.241421.a3f796f is not available (latest version: 2.0.0-nightly.241421.a3f796f, downgrade is disallowed).
GET /api/extensions 304 2.753 ms - -
GET /api/extensions/settings?_all 304 2.970 ms - -
GET /api/featureFlags 304 4.091 ms - -
GET /api/assets/locales/en-US.json 200 55.826 ms - -
GET /api/utilities/checkNode 304 157.265 ms - -
GET /api/storages 304 0.747 ms - -
GET /api/storages/default/blobs?path=C%253A%252FUsers%252Fv-jofin%252Fsource%252Frepos%252Fother%252Ficiclecreek.bot%252Fsource%252FBots%252FRepoBot 304 21.051 ms - -
POST /api/v2/assets/projectTemplates 200 87.378 ms - -
GET /api/projects/recent 304 11.693 ms - -
GET /api/projects/feed 304 944.758 ms - -
POST /api/telemetry/events 200 2.984 ms - 2
PUT /api/projects/open 200 152.306 ms - -
GET /api/publish/27727.480736587328/status/default 404 52.440 ms - 66
GET /conversations/ws/port 200 13.569 ms - 39
GET /api/publish/runtimeLogUrl/27727.480736587328 304 25.423 ms - -
GET /conversations/ws/port 200 0.465 ms - 40
PUT /api/projects/27727.480736587328/files/Dialogs.botproj 200 115.153 ms - 76
PUT /api/projects/27727.480736587328/files/appsettings.json 200 116.605 ms - 34
GET /api/storages 304 0.921 ms - -
GET /api/storages/default/blobs?path=C%253A%252FUsers%252Fv-jofin%252Fsource%252Frepos%252Fother%252Ficiclecreek.bot%252Fsource%252FBots%252FRepoBot 304 13.510 ms - -
GET /api/storages/default/blobs?path=C%253A%252FUsers%252Fv-jofin%252Fsource%252Frepos%252Fother%252Ficiclecreek.bot%252Fsource%252FBots%252FRepoBot 304 5.543 ms - -
POST /api/telemetry/events 200 2.824 ms - 2
D pid(10332) tid(31196) 16:27:45 EdgeSnapFeature::PostExitSizeMove: WM_TWINVIEW_SHOW_GRIDLINES -> off
GET /plugin-host.html 200 4.244 ms - 997
GET /api/extensions/package-manager/package-manager 304 8.553 ms - -
Translation for "nuget" in "en" is missing
Translation for "npm" in "en" is missing
POST /api/telemetry/events 200 4.514 ms - 2
```

**Comment by mewa1024** [comment]
Tested on 4/30:
- Used Frankenbuild from [https://fuselabs.visualstudio.com/Composer/_build/results?buildId=241078&view=results](url).
- opened an EchoBot with the sample custom action (MultiplyDialog) added
- Followed the instructions in the Composer R13 - Mock Composer Upgrade Test:

1. Open “Terminal” and run this command : export GH_TOKEN= _tokenValue_ 
1. Go to Composer's install location (ex Applications) 
1. Drag the Composer icon to Terminal and you should see the path. 
2. Append open in front of the path. For ex (open /Applications/Bot\ Framework\ Composer.app) 

This time I did not get the flow of updating from 1.4, but instead Composer opened 2.0.


### **Issues**
Found 4 more issues after converting the bot with custom actions:

- I did not get a modal warning me that I had exported runtime and that any custom actions would have to be rebuilt. Can we added a second paragraph when we detect the bot has exported runtime?

  > If you have created custom components, you might need to rebuild them. Learn more about custom components.

  The Learn more should link to the document about custom actions.

  Screen shot:
  ![image](https://user-images.githubusercontent.com/39317542/116766086-78885800-a9dd-11eb-8017-579da82a79bc.png)

- After conversion, can we should in the Getting Started menu that your bots custom actions were deactivated? The text should open the Problems page. Here is an example wirefram from the design:[https://www.figma.com/file/4kfahZUjBdrxdDGZih7PVP/Composer-1.5-E2E-flows?node-id=677%3A1114](url):
  
  ![image](https://user-images.githubusercontent.com/39317542/116766635-5ba15400-a9e0-11eb-9fce-aec8c1ce8fcd.png)

- The text in the problems pane should say:

  > **Deactivated action.** Components of $kind “MultiplyDialog” are not supported. Replace with a different 
component or create a custom component. Learn more about custom actions.

  where "MultiplyDialog" is the name of the custom action. "Learn more about custom actions" links to the doc about custom actions.

  Screenshot from the design:
  
  ![image](https://user-images.githubusercontent.com/39317542/116766394-234d4600-a9df-11eb-9998-7ea76d89790f.png)

- The errors should be warnings (nonblocking). As errors, I had to delete the node to enable the Start Bot button, even though the custom action was disabled. 

  ![image](https://user-images.githubusercontent.com/39317542/116766848-86d87300-a9e1-11eb-8ba5-a82acf2f95c9.png)

**Comment by sgellock** [comment]
Shiproom - once we push 1.4.x out, we can test further.

**Comment by mewa1024** [comment]
related: #7600
