### ISSUE TITLE
Removing local skill from parent bricks the parent bot project

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/BotFramework-Composer#7456]
## Describe the bug
If you remove a local skill from the parent project the `restart bot` button is disabled and the error doesn't direct you to any where to manually resolve the issue.

## Version
Version:  2.0.0-nightly.240366.4a6ec2c
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create, provision, and share as a skill an echo bot
2. Create a parent bot
3. Add the app ids/pw to the parent & skill
4. update parent app settings to have `["*"]` in the allowed callers list
5. Add the skill to the parent 
6. start the bots
7. Remove the skill from the project

## Expected behavior
The skill should be removed and any other things that should automatically happen to fully remove the skill should happen. Alternatively the error should tell you where to go to resolve the error

## Screenshots
![image](https://user-images.githubusercontent.com/50158775/116452619-c2711280-a812-11eb-8795-ad8a5e017982.png)
![image](https://user-images.githubusercontent.com/50158775/116452649-c9982080-a812-11eb-84f4-193c6371f5de.png)

## Additional context
Restarting composer doesn't clear the issue so it doesn't appear to be a caching issue.

**Comment by sgellock** [comment]
Shiproom: @cwhitten, route to stc-a?

**Comment by Virtual-Josh** [comment]
Note: This appears to only affect local skills. You can add and remove remote skills just fine. My guess would be due to the new UI for adding local skills some assumption somewhere is no longer true. 

Here's an error that showed up when I tried to start the parent bot with the same skill added as a remote skill. MAYBE this is the smoking gun, it's also entirely possible it's a massive red herring. 

```
Error occurred building the bot

Message:
Command failed: dotnet build DotnetParentWA428.csproj
Command:
dotnet build DotnetParentWA428.csproj
Stack Trace:
Error: Command failed: dotnet build DotnetParentWA428.csproj

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
Output:
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\DotnetParentWA428.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
  Restored C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\DotnetParentWA428.csproj (in 1.34 sec).
C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\DotnetParentWA428.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\DotnetParentWA428.exe". Beginning retry 1 in 1000ms. The process cannot access the file 'C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\bin\Debug\netcoreapp3.1\DotnetParentWA428.exe' because it is being used by another process.  [C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\DotnetParentWA428.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\DotnetParentWA428.exe". Beginning retry 2 in 1000ms. The process cannot access the file 'C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\bin\Debug\netcoreapp3.1\DotnetParentWA428.exe' because it is being used by another process.  [C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\DotnetParentWA428.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\DotnetParentWA428.exe". Beginning retry 3 in 1000ms. The process cannot access the file 'C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\bin\Debug\netcoreapp3.1\DotnetParentWA428.exe' because it is being used by another process.  [C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\DotnetParentWA428.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\DotnetParentWA428.exe". Beginning retry 4 in 1000ms. The process cannot access the file 'C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\bin\Debug\netcoreapp3.1\DotnetParentWA428.exe' because it is being used by another process.  [C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\DotnetParentWA428.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\DotnetParentWA428.exe". Beginning retry 5 in 1000ms. The process cannot access the file 'C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\bin\Debug\netcoreapp3.1\DotnetParentWA428.exe' because it is being used by another process.  [C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\DotnetParentWA428.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\DotnetParentWA428.exe". Beginning retry 6 in 1000ms. The process cannot access the file 'C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\bin\Debug\netcoreapp3.1\DotnetParentWA428.exe' because it is being used by another process.  [C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\DotnetParentWA428.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\DotnetParentWA428.exe". Beginning retry 7 in 1000ms. The process cannot access the file 'C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\bin\Debug\netcoreapp3.1\DotnetParentWA428.exe' because it is being used by another process.  [C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\DotnetParentWA428.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\DotnetParentWA428.exe". Beginning retry 8 in 1000ms. The process cannot access the file 'C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\bin\Debug\netcoreapp3.1\DotnetParentWA428.exe' because it is being used by another process.  [C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\DotnetParentWA428.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\DotnetParentWA428.exe". Beginning retry 9 in 1000ms. The process cannot access the file 'C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\bin\Debug\netcoreapp3.1\DotnetParentWA428.exe' because it is being used by another process.  [C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\DotnetParentWA428.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\DotnetParentWA428.exe". Beginning retry 10 in 1000ms. The process cannot access the file 'C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\bin\Debug\netcoreapp3.1\DotnetParentWA428.exe' because it is being used by another process.  [C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\DotnetParentWA428.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): error MSB3027: Could not copy "C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\DotnetParentWA428.exe". Exceeded retry count of 10. Failed.  [C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\DotnetParentWA428.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): error MSB3021: Unable to copy file "C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\DotnetParentWA428.exe". The process cannot access the file 'C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\bin\Debug\netcoreapp3.1\DotnetParentWA428.exe' because it is being used by another process. [C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\DotnetParentWA428.csproj]

Build FAILED.

C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\DotnetParentWA428.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\DotnetParentWA428.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\DotnetParentWA428.exe". Beginning retry 1 in 1000ms. The process cannot access the file 'C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\bin\Debug\netcoreapp3.1\DotnetParentWA428.exe' because it is being used by another process.  [C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\DotnetParentWA428.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\DotnetParentWA428.exe". Beginning retry 2 in 1000ms. The process cannot access the file 'C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\bin\Debug\netcoreapp3.1\DotnetParentWA428.exe' because it is being used by another process.  [C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\DotnetParentWA428.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\DotnetParentWA428.exe". Beginning retry 3 in 1000ms. The process cannot access the file 'C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\bin\Debug\netcoreapp3.1\DotnetParentWA428.exe' because it is being used by another process.  [C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\DotnetParentWA428.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\DotnetParentWA428.exe". Beginning retry 4 in 1000ms. The process cannot access the file 'C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\bin\Debug\netcoreapp3.1\DotnetParentWA428.exe' because it is being used by another process.  [C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\DotnetParentWA428.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\DotnetParentWA428.exe". Beginning retry 5 in 1000ms. The process cannot access the file 'C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\bin\Debug\netcoreapp3.1\DotnetParentWA428.exe' because it is being used by another process.  [C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\DotnetParentWA428.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\DotnetParentWA428.exe". Beginning retry 6 in 1000ms. The process cannot access the file 'C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\bin\Debug\netcoreapp3.1\DotnetParentWA428.exe' because it is being used by another process.  [C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\DotnetParentWA428.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\DotnetParentWA428.exe". Beginning retry 7 in 1000ms. The process cannot access the file 'C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\bin\Debug\netcoreapp3.1\DotnetParentWA428.exe' because it is being used by another process.  [C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\DotnetParentWA428.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\DotnetParentWA428.exe". Beginning retry 8 in 1000ms. The process cannot access the file 'C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\bin\Debug\netcoreapp3.1\DotnetParentWA428.exe' because it is being used by another process.  [C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\DotnetParentWA428.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\DotnetParentWA428.exe". Beginning retry 9 in 1000ms. The process cannot access the file 'C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\bin\Debug\netcoreapp3.1\DotnetParentWA428.exe' because it is being used by another process.  [C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\DotnetParentWA428.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\DotnetParentWA428.exe". Beginning retry 10 in 1000ms. The process cannot access the file 'C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\bin\Debug\netcoreapp3.1\DotnetParentWA428.exe' because it is being used by another process.  [C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\DotnetParentWA428.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): error MSB3027: Could not copy "C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\DotnetParentWA428.exe". Exceeded retry count of 10. Failed.  [C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\DotnetParentWA428.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): error MSB3021: Unable to copy file "C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\DotnetParentWA428.exe". The process cannot access the file 'C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\bin\Debug\netcoreapp3.1\DotnetParentWA428.exe' because it is being used by another process. [C:\Users\joratlif\ComposerSkills\4_28\DotnetParentWA428\DotnetParentWA428\DotnetParentWA428.csproj]
    12 Warning(s)
    2 Error(s)

Time Elapsed 00:00:15.28
Killed:
Code:
1
```

**Comment by cwhitten** [comment]
@Virtual-Josh do you have any call-sites to the skill in the parent once you removed it from the project?

**Comment by Virtual-Josh** [comment]
After taking a 2nd look I did have 1 call site remaining. Removing it resolved the issue. 

So this is now the open question: Is the current error's implementation for what is effectively a null referenced skill a P-0 issue? 

@sgellock do you have an opinion here?

**Comment by cwhitten** [comment]
I've got the following to help clear this up:

<img width="1389" alt="Screen Shot 2021-04-29 at 6 12 20 AM" src="https://user-images.githubusercontent.com/1156704/116556083-f18a9100-a8b1-11eb-9382-23848387474f.png">
