### ISSUE TITLE
Got error when trying to start bots after updating root bot to call external skill

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotFramework-Composer#7493]
## Describe the bug

Got a JavaScript error after modifying my root bot and trying to restart all bots.

## Version

Version:  2.0.0-nightly.240913.4390cd8
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a root bot and local skill. (Mine is a simple echo skill.)
2. Publish the skill bot.
3. Modify the root bot to call the remote skill instead of the local one.
4. Error: try to start all bots.
  - Get JavaScript error.
  - The skill bot failed to start.
  - Composer still seems to think it's trying to start the root bot.

## Expected behavior

If there's an issue, Composer fails gracefully, though I'm not sure what the issue would be here.

## Screenshots

![imgpsh_mobile_save](https://user-images.githubusercontent.com/35047199/116601465-658f5e00-a8df-11eb-989f-e1a9935a3831.jpg)

![image](https://user-images.githubusercontent.com/35047199/116601516-73dd7a00-a8df-11eb-8d69-c76633d8aa4a.png)

## Additional context

From the **Output** pane:

```text
Error occurred building the bot

Message:
Command failed: dotnet build EchoSkill.csproj
Command:
dotnet build EchoSkill.csproj
Stack Trace:
Error: Command failed: dotnet build EchoSkill.csproj

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
Output:
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\EchoSkill.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
  Restored C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\EchoSkill.csproj (in 896 ms).
C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\EchoSkill.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\EchoSkill.exe". Beginning retry 1 in 1000ms. The process cannot access the file 'C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\bin\Debug\netcoreapp3.1\EchoSkill.exe' because it is being used by another process.  [C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\EchoSkill.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\EchoSkill.exe". Beginning retry 2 in 1000ms. The process cannot access the file 'C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\bin\Debug\netcoreapp3.1\EchoSkill.exe' because it is being used by another process.  [C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\EchoSkill.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\EchoSkill.exe". Beginning retry 3 in 1000ms. The process cannot access the file 'C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\bin\Debug\netcoreapp3.1\EchoSkill.exe' because it is being used by another process.  [C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\EchoSkill.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\EchoSkill.exe". Beginning retry 4 in 1000ms. The process cannot access the file 'C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\bin\Debug\netcoreapp3.1\EchoSkill.exe' because it is being used by another process.  [C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\EchoSkill.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\EchoSkill.exe". Beginning retry 5 in 1000ms. The process cannot access the file 'C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\bin\Debug\netcoreapp3.1\EchoSkill.exe' because it is being used by another process.  [C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\EchoSkill.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\EchoSkill.exe". Beginning retry 6 in 1000ms. The process cannot access the file 'C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\bin\Debug\netcoreapp3.1\EchoSkill.exe' because it is being used by another process.  [C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\EchoSkill.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\EchoSkill.exe". Beginning retry 7 in 1000ms. The process cannot access the file 'C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\bin\Debug\netcoreapp3.1\EchoSkill.exe' because it is being used by another process.  [C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\EchoSkill.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\EchoSkill.exe". Beginning retry 8 in 1000ms. The process cannot access the file 'C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\bin\Debug\netcoreapp3.1\EchoSkill.exe' because it is being used by another process.  [C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\EchoSkill.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\EchoSkill.exe". Beginning retry 9 in 1000ms. The process cannot access the file 'C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\bin\Debug\netcoreapp3.1\EchoSkill.exe' because it is being used by another process.  [C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\EchoSkill.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\EchoSkill.exe". Beginning retry 10 in 1000ms. The process cannot access the file 'C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\bin\Debug\netcoreapp3.1\EchoSkill.exe' because it is being used by another process.  [C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\EchoSkill.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): error MSB3027: Could not copy "C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\EchoSkill.exe". Exceeded retry count of 10. Failed.  [C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\EchoSkill.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): error MSB3021: Unable to copy file "C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\EchoSkill.exe". The process cannot access the file 'C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\bin\Debug\netcoreapp3.1\EchoSkill.exe' because it is being used by another process. [C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\EchoSkill.csproj]

Build FAILED.

C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\EchoSkill.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\EchoSkill.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\EchoSkill.exe". Beginning retry 1 in 1000ms. The process cannot access the file 'C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\bin\Debug\netcoreapp3.1\EchoSkill.exe' because it is being used by another process.  [C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\EchoSkill.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\EchoSkill.exe". Beginning retry 2 in 1000ms. The process cannot access the file 'C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\bin\Debug\netcoreapp3.1\EchoSkill.exe' because it is being used by another process.  [C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\EchoSkill.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\EchoSkill.exe". Beginning retry 3 in 1000ms. The process cannot access the file 'C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\bin\Debug\netcoreapp3.1\EchoSkill.exe' because it is being used by another process.  [C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\EchoSkill.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\EchoSkill.exe". Beginning retry 4 in 1000ms. The process cannot access the file 'C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\bin\Debug\netcoreapp3.1\EchoSkill.exe' because it is being used by another process.  [C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\EchoSkill.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\EchoSkill.exe". Beginning retry 5 in 1000ms. The process cannot access the file 'C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\bin\Debug\netcoreapp3.1\EchoSkill.exe' because it is being used by another process.  [C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\EchoSkill.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\EchoSkill.exe". Beginning retry 6 in 1000ms. The process cannot access the file 'C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\bin\Debug\netcoreapp3.1\EchoSkill.exe' because it is being used by another process.  [C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\EchoSkill.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\EchoSkill.exe". Beginning retry 7 in 1000ms. The process cannot access the file 'C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\bin\Debug\netcoreapp3.1\EchoSkill.exe' because it is being used by another process.  [C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\EchoSkill.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\EchoSkill.exe". Beginning retry 8 in 1000ms. The process cannot access the file 'C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\bin\Debug\netcoreapp3.1\EchoSkill.exe' because it is being used by another process.  [C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\EchoSkill.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\EchoSkill.exe". Beginning retry 9 in 1000ms. The process cannot access the file 'C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\bin\Debug\netcoreapp3.1\EchoSkill.exe' because it is being used by another process.  [C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\EchoSkill.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): warning MSB3026: Could not copy "C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\EchoSkill.exe". Beginning retry 10 in 1000ms. The process cannot access the file 'C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\bin\Debug\netcoreapp3.1\EchoSkill.exe' because it is being used by another process.  [C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\EchoSkill.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): error MSB3027: Could not copy "C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\EchoSkill.exe". Exceeded retry count of 10. Failed.  [C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\EchoSkill.csproj]
C:\Program Files\dotnet\sdk\5.0.202\Microsoft.Common.CurrentVersion.targets(4919,5): error MSB3021: Unable to copy file "C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\EchoSkill.exe". The process cannot access the file 'C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\bin\Debug\netcoreapp3.1\EchoSkill.exe' because it is being used by another process. [C:\Users\v-jofin\source\repos\myBots\composer\EchoSkill\EchoSkill\EchoSkill.csproj]
    12 Warning(s)
    2 Error(s)

Time Elapsed 00:00:13.86
Killed:
Code:
1
```

**Comment by JonathanFingold** [comment]
Looks like this is due to Composer failing to kill the old bot process for the skill bot. From when I tested things locally.

**Comment by JonathanFingold** [comment]
Killing the old process via Task Manager did not get Composer's launch bots widget out of its hanging state.

**Comment by cwhitten** [comment]
@JonathanFingold can you please attempt this on the latest nightly? The version you're on was a bad version

**Comment by JonathanFingold** [comment]
Did not repo with this latest build.
