### ISSUE TITLE
Node Function bots don't respond when testing in Azure

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/BotFramework-Composer#7501]
## Describe the bug
Function bots throw a 502 when you try to test them from web chat

## Version
Version:  2.0.0-nightly.241057.db66154
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a bot from the empty bot template
2. create a provisioning profile for the bot 
3. publish the bot
4. go to the azure portal, select web channel registration, test in webchat
5. Send the bot a message

## Expected behavior
The bot should respond

## Screenshots
![image](https://user-images.githubusercontent.com/50158775/116617880-3256ca00-a8f3-11eb-8588-7b3d26ad6db4.png)

**Comment by benbrown** [comment]
@joshgummersall Can you take a pass through the latest generators and check this out?

**Comment by joshgummersall** [comment]
@Virtual-Josh functions bots (especially JS) tend to take quite awhile to startup. `5XX` response codes, especially a `502`, tend to imply that a backend server did not respond. Did you see this soon after deploying your bot?

**Comment by Virtual-Josh** [comment]
@joshgummersall I did. However I also just poked it again since it should have had more time to sort itself out and it's still throwing the same error ~30 minutes later. Also I used a dotnet function bot.

**Comment by joshgummersall** [comment]
There is an issue where the NPM `~4.13.0-preview` resolved to older SDK release candidates. Locally, this actually yielded different versions of several `botbuilder-*` packages. Currently, we use some `instanceof` checks in the code, so the end result was exceptions due to `instanceof` failing due to conflicting versions loading at runtime. This issue will be fixed with the next RC of templates.

There appears to also be problems with how function apps are provisioned. I'm working on figuring that out now.

**Comment by Virtual-Josh** [comment]
@joshgummersall how long does it roughly take? I just poked the dotnet function bot that I haven't redeployed in 3 hours and it's still throwing 502s.

**Comment by joshgummersall** [comment]
If you didn't see my message on Teams, there's a manual fix you need to apply, then redeploy, then it should work.

**Comment by sgellock** [comment]
Shiproom - lets spike making linux the default OS for A Func

**Comment by Virtual-Josh** [comment]
I've done the update you recommended and the bot still isn't responding. This bot was deployed this morning over 3 hours ago. However there's a new error in the logs which might point to a different problem with the build process:

``` 
2021-04-30T21:45:08.232 [Error] ReferenceError: cosmosDbEndpoint for CosmosDB is required.at new CosmosDbPartitionedStorage (C:\home\site\wwwroot\node_modules\botbuilder-azure\lib\cosmosDbPartitionedStorage.js:83:19)at C:\home\site\wwwroot\node_modules\botbuilder-dialogs-adaptive-runtime\lib\index.js:127:24at factory (C:\home\site\wwwroot\node_modules\botbuilder-dialogs-adaptive-runtime-core\lib\serviceCollection.js:70:45)at C:\home\site\wwwroot\node_modules\botbuilder-dialogs-adaptive-runtime-core\lib\serviceCollection.js:129:67at Array.reduce (<anonymous>)at C:\home\site\wwwroot\node_modules\botbuilder-dialogs-adaptive-runtime-core\lib\serviceCollection.js:129:40at Array.reduce (<anonymous>)at ServiceCollection.buildNodes (C:\home\site\wwwroot\node_modules\botbuilder-dialogs-adaptive-runtime-core\lib\serviceCollection.js:114:32)at ServiceCollection.makeInstances (C:\home\site\wwwroot\node_modules\botbuilder-dialogs-adaptive-runtime-core\lib\serviceCollection.js:171:21)at ServiceCollection.mustMakeInstances (C:\home\site\wwwroot\node_modules\botbuilder-dialogs-adaptive-runtime-core\lib\serviceCollection.js:180:32)
2021-04-30T21:45:08.466 [Error] Executed 'Functions.messages' (Failed, Id=1662232e-845e-499e-bc9c-ee968a948898, Duration=153216ms)Result: FailureException: ReferenceError: cosmosDbEndpoint for CosmosDB is required.Stack: ReferenceError: cosmosDbEndpoint for CosmosDB is required.at new CosmosDbPartitionedStorage (C:\home\site\wwwroot\node_modules\botbuilder-azure\lib\cosmosDbPartitionedStorage.js:83:19)at C:\home\site\wwwroot\node_modules\botbuilder-dialogs-adaptive-runtime\lib\index.js:127:24at factory (C:\home\site\wwwroot\node_modules\botbuilder-dialogs-adaptive-runtime-core\lib\serviceCollection.js:70:45)at C:\home\site\wwwroot\node_modules\botbuilder-dialogs-adaptive-runtime-core\lib\serviceCollection.js:129:67at Array.reduce (<anonymous>)at C:\home\site\wwwroot\node_modules\botbuilder-dialogs-adaptive-runtime-core\lib\serviceCollection.js:129:40at Array.reduce (<anonymous>)at ServiceCollection.buildNodes (C:\home\site\wwwroot\node_modules\botbuilder-dialogs-adaptive-runtime-core\lib\serviceCollection.js:114:32)at ServiceCollection.makeInstances (C:\home\site\wwwroot\node_modules\botbuilder-dialogs-adaptive-runtime-core\lib\serviceCollection.js:171:21)at ServiceCollection.mustMakeInstances (C:\home\site\wwwroot\node_modules\botbuilder-dialogs-adaptive-runtime-core\lib\serviceCollection.js:180:32)
```

It seems like Composer isn't picking up some files/config/params that web apps do since I've never had it complain about missing/bad storage things.

**Comment by sgellock** [comment]
Shiproom - continue to investigate.  core scenario for R13

**Comment by joshgummersall** [comment]
@sgellock should be resolved via https://github.com/microsoft/botbuilder-js/pull/3643

**Comment by joshgummersall** [comment]
I verified a Cosmos DB deployment this morning using `4.14.0-preview.dev.6e311b9` which includes the fix from https://github.com/microsoft/botbuilder-js/pull/3643 and it worked.

**Comment by sgellock** [comment]
Shiproom - let's sit on this as it depends on an SDK update.  there's a debate about changing the defaults during C&C to reduce the blast zone

**Comment by sgellock** [comment]
Shiproom - 4.13.2 of JS SDK has been published.  this contains the cosmos DB fix that addresses this issue
