### ISSUE TITLE
Publishing not working

### ISSUE THREAD

**Issue by Clooney24** [microsoft/BotFramework-Composer#7545]
## Describe the bug

Publishing process stops with error  MSB1009: Die Projektdatei ist nicht vorhanden.\\r\\nSchalter: [...stripped path info..]\\\\runtime\\\\Microsoft.BotFramework.Composer.WebApp.csproj\\r\\n\",\"stderr\":\"\"}"

This project files lies in sub-folder "azurewebapp" - publishing process seems to require it in runtime main folder?

## Version

Version:  2.0.0-nightly.241799.f577409
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## OS

Windows

## To Reproduce

1. Try to publish bot to Azure WebApp
2. See error

## Additional context

full log:

---
"Accepted for publishing..."
---

---
"Abs settings incomplete, skip linking bot with webapp ..."
---

---
"appPasswordHint incomplete, return ..."
---

---
"Building the bot app..."
---

---
"Build succeeded!"
---

---
"start publish luis"
---

---
"Assigning to luis app id: xxxx [stripped]
---

---
"Luis Publish Success! ..."
---

---
"{\"stack\":\"Error: Command failed: dotnet publish \\\"[stripped path]\\\\runtime\\\\Microsoft.BotFramework.Composer.WebApp.csproj\\\" -c release -o \\\"[stripped path]\\\\runtime\\\\bin\\\\release\\\\publishTarget\\\" -v q --self-contained true -r win-x64\\n\\n    at ChildProcess.exithandler (child_process.js:308:12)\\n    at ChildProcess.emit (events.js:210:5)\\n    at maybeClose (internal/child_process.js:1021:16)\\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)\",\"message\":\"Command failed: dotnet publish \\\"[stripped path]\\\\runtime\\\\Microsoft.BotFramework.Composer.WebApp.csproj\\\" -c release -o \\\"[stripped path]\\\\runtime\\\\bin\\\\release\\\\publishTarget\\\" -v q --self-contained true -r win-x64\\n\",\"killed\":false,\"code\":1,\"signal\":null,\"cmd\":\"dotnet publish \\\"[stripped path]\\\\runtime\\\\Microsoft.BotFramework.Composer.WebApp.csproj\\\" -c release -o \\\"[stripped path]\\\\runtime\\\\bin\\\\release\\\\publishTarget\\\" -v q --self-contained true -r win-x64\",\"stdout\":\"Microsoft (R)-Build-Engine, Version 16.9.0+57a23d249 f�r .NET\\r\\nCopyright (C) Microsoft Corporation. Alle Rechte vorbehalten.\\r\\n\\r\\nMSBUILD : error MSB1009: Die Projektdatei ist nicht vorhanden.\\r\\nSchalter: [stripped path]\\\\runtime\\\\Microsoft.BotFramework.Composer.WebApp.csproj\\r\\n\",\"stderr\":\"\"}"
---

---
"Error - Command failed: dotnet publish \"[stripped path]\\runtime\\Microsoft.BotFramework.Composer.WebApp.csproj\" -c release -o \"[stripped path]\\runtime\\bin\\release\\publishTarget\" -v q --self-contained true -r win-x64\n"
---

**Comment by Clooney24** [comment]
On step before, publishing did not even start because folders "ComposerDialogs\generated" are missing in runtime. I created them manually, then this error happend.

**Comment by Clooney24** [comment]
This was due to breaking changes in experimental version as extractable runtime was removed there, my old project settings didn't match that new structure anymore. I fixed it manually using samples from a bot I freshly created with new version.
