### ISSUE TITLE
Publishing bot to Azure fails - "No directory ComposerDialogs/generated + csproj not found"

### ISSUE THREAD

**Issue by peta** [microsoft/BotFramework-Composer#7641]
## Describe the bug

I have a working bot created in BFC and want to publish it to Azure. Setting up the publishing profile did work, along with automatic provisioning of all required Azure ressources conducted by BFC. But when selecting the bot and pressing `Publish selected bots`, I immediately receive the error shown in the first screenshot below. When I manually create the folders `ComposerDialogs/generated` in the according program files app folder, the first error is solved. But then another one occurs -> see second screenshot and pased stack trace in context section below. 

## Version

Version:  2.0.0-nightly.242720.c3b8105
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## Expected behavior

Publishing a bot should succeed. Indeed it does succeed, when using the latest stable version 1.4 of BFC.

### First error (I could solve)

![image](https://user-images.githubusercontent.com/131624/117110614-b216e580-ad86-11eb-83eb-0e88caa81466.png)

### Second error 
![image](https://user-images.githubusercontent.com/131624/117111114-6f094200-ad87-11eb-8c19-f5edcabaad40.png)

### Error log of second error 

```
---
"Accepted for publishing..."
---

---
"Abs settings incomplete, skip linking bot with webapp ..."
---

---
"appPasswordHint incomplete, return ..."
---

---
"Building the bot app..."
---

---
"Build succeeded!"
---

---
"start publish luis"
---

---
"Assigning to luis app id: <SOMEGUID>"
---

---
"Assigning to luis app id: <SOMEGUID>"
---

---
"Luis Publish Success! ..."
---

---
"{\"stack\":\"Error: Command failed: dotnet publish \\\"Microsoft.BotFramework.Composer.WebApp.csproj\\\" -c release -o \\\"bin\\\\release\\\\publishTarget\\\" -v q --self-contained true -r win-x64\\n\\n    at ChildProcess.exithandler (child_process.js:308:12)\\n    at ChildProcess.emit (events.js:210:5)\\n    at maybeClose (internal/child_process.js:1021:16)\\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)\",\"message\":\"Command failed: dotnet publish \\\"Microsoft.BotFramework.Composer.WebApp.csproj\\\" -c release -o \\\"bin\\\\release\\\\publishTarget\\\" -v q --self-contained true -r win-x64\\n\",\"killed\":false,\"code\":1,\"signal\":null,\"cmd\":\"dotnet publish \\\"Microsoft.BotFramework.Composer.WebApp.csproj\\\" -c release -o \\\"bin\\\\release\\\\publishTarget\\\" -v q --self-contained true -r win-x64\",\"stdout\":\"Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core\\r\\nCopyright (C) Microsoft Corporation. All rights reserved.\\r\\n\\r\\nMSBUILD : error MSB1009: Project file does not exist.\\r\\nSwitch: Microsoft.BotFramework.Composer.WebApp.csproj\\r\\n\",\"stderr\":\"\"}"
---

---
"Error - Command failed: dotnet publish \"Microsoft.BotFramework.Composer.WebApp.csproj\" -c release -o \"bin\\release\\publishTarget\" -v q --self-contained true -r win-x64\n"
---

```

**Comment by dmvtech** [comment]
I can reproduce this. I'm not 100% sure, but my bot _might_ have been created with `1.4.0` release. @peta Do you know if yours was created with a nightly build or with `1.4.0`? 

I'm going to try by creating a brand new bot and try and publish again.

**Comment by dmvtech** [comment]
Created a new bot and was able to publish successfully. With:

```
Version:  2.0.0-nightly.242720.c3b8105
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0
```

So, _might_ have to do with creating bot in previous version.

**Comment by dmvtech** [comment]
I created a new publishing profile using `2.0.0-nightly.242720.c3b8105`, but still with my older bot. Error still happens. Provisioning works fine, but publishing fails.

**Comment by GeoffCoxMSFT** [comment]
I think @benbrown likely fixed this issue with this recent PR: https://github.com/microsoft/BotFramework-Composer/pull/7557

**Comment by benbrown** [comment]
No I don't think so @GeoffCoxMSFT since that was only related to functions.

This is likely due to the fact that pre-2.0 bots need to be migrated to the new runtime to work with the publishing system as it is in the nightly.  The migration tools will be included soon.
