### ISSUE TITLE
Node bots can't talk over skills locally

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/BotFramework-Composer#7766]
## Describe the bug
Node bots, regardless of configuration as the parent or the skill, or a function or web app can't talk over skills 

## Version
Version:  2.0.0-nightly.244572.8406071
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

This is a pick your own adventure. Pick any combination of node as the parent, node as the skill, or both. Start the bots, and have the parent call the child.

## Expected behavior
This should work

## Screenshots
In every scenario the bot throws the error

## Additional context
Here's the matrix of the test results:
Dotnet web app parent:
-	Dotnet web app - works
-	Dotnet function - works
-	Node web app – does not work
-	Node function - does not work

Dotnet function parent:
-	Dotnet web app - works 
-	Dotnet function - works
-	Node web app – 401s, no logs
-	Node function – 401s, no logs

Node web app parent:
-	Dotnet web app – doesn’t work, throws “bot encountered an error or bug”
-	Dotnet function – doesn’t work, throws “bot encountered an error or bug”
-	Node web app – doesn’t work, throws “bot encountered an error or bug”
-	Node function – doesn’t work, throws “bot encountered an error or bug”

Node function parent:
-	Dotnet web app – doesn’t work, throws “bot encountered an error or bug” 
-	Dotnet function– doesn’t work, throws “bot encountered an error or bug”
-	Node web app– doesn’t work, throws “bot encountered an error or bug”
-	Node function– doesn’t work, throws “bot encountered an error or bug”

############################################################

For context, I believe a new set of generators were going to be made to pick up a fix Ben did. I don't know if the generators are updated yet or if that even is an actual potential source of the issue. 

Here's some of the logs from the various tests I ran. It's a mash up from different attempts as I tried to talk to the various skills:

Azure Functions Core Tools
Core Tools Version:       3.0.3442 Commit hash: 6bfab24b2743f8421475d996402c398d2fe4a9e0  (64-bit)
Function Runtime Version: 3.0.15417.0

Functions:

	messages: [GET,POST] http://localhost:3987/api/{route}

	skills: [POST] http://localhost:3987/api/skills/v3/conversations/{conversationId}/activities/{activityId}

	static: [GET] http://localhost:3987/{*path}

For detailed output, run func with --verbose flag.
[2021-05-12T01:41:30.925Z] Worker process started and initialized.
[2021-05-12T01:41:35.700Z] Host lock lease acquired by instance ID '000000000000000000000000476DC267'.
[2021-05-12T01:42:53.546Z] Executing 'Functions.messages' (Reason='This function was programmatically called via the host APIs.', Id=5876fe29-17f7-4593-a331-7bd381a9e93c)
[2021-05-12T01:42:53.639Z] Messages endpoint triggered.
[2021-05-12T01:43:01.399Z] Executing 'Functions.messages' (Reason='This function was programmatically called via the host APIs.', Id=d4189c88-8f97-4cc0-8810-acf0abe16bf6)
[2021-05-12T01:43:04.378Z] Messages endpoint triggered.
[2021-05-12T01:43:06.506Z] [onTurnError] unhandled error Error: The clientSecret parameter is required.
[2021-05-12T01:43:06.507Z]     at Object.validateStringParameter (C:\Users\joratlif\ComposerSkills\5_11a\NodeFunctionParent511a\NodeFunctionParent511a\node_modules\adal-node\lib\argument.js:37:13)
[2021-05-12T01:43:06.507Z]     at AuthenticationContext.acquireTokenWithClientCredentials (C:\Users\joratlif\ComposerSkills\5_11a\NodeFunctionParent511a\NodeFunctionParent511a\node_modules\adal-node\lib\authentication-context.js:282:14)
[2021-05-12T01:43:06.507Z]     at C:\Users\joratlif\ComposerSkills\5_11a\NodeFunctionParent511a\NodeFunctionParent511a\node_modules\botframework-connector\lib\auth\microsoftAppCredentials.js:49:48
[2021-05-12T01:43:06.507Z]     at new Promise (<anonymous>)
[2021-05-12T01:43:06.507Z]     at MicrosoftAppCredentials.<anonymous> (C:\Users\joratlif\ComposerSkills\5_11a\NodeFunctionParent511a\NodeFunctionParent511a\node_modules\botframework-connector\lib\auth\microsoftAppCredentials.js:48:40)
[2021-05-12T01:43:06.508Z]     at Generator.next (<anonymous>)
[2021-05-12T01:43:06.508Z]     at C:\Users\joratlif\ComposerSkills\5_11a\NodeFunctionParent511a\NodeFunctionParent511a\node_modules\botframework-connector\lib\auth\microsoftAppCredentials.js:15:71
[2021-05-12T01:43:06.508Z]     at new Promise (<anonymous>)
[2021-05-12T01:43:06.508Z]     at __awaiter (C:\Users\joratlif\ComposerSkills\5_11a\NodeFunctionParent511a\NodeFunctionParent511a\node_modules\botframework-connector\lib\auth\microsoftAppCredentials.js:11:12)
[2021-05-12T01:43:06.508Z]     at MicrosoftAppCredentials.refreshToken (C:\Users\joratlif\ComposerSkills\5_11a\NodeFunctionParent511a\NodeFunctionParent511a\node_modules\botframework-connector\lib\auth\microsoftAppCredentials.js:46:16) {
[2021-05-12T01:43:06.509Z]   name: 'DialogContextError',
[2021-05-12T01:43:06.509Z]   dialogContext: {
[2021-05-12T01:43:06.509Z]     activeDialog: "BeginSkill['=settings.skill['dotnetFunctionEcho511A'].msAppId','']",
[2021-05-12T01:43:06.510Z]     parent: 'NodeFunctionParent511a',
[2021-05-12T01:43:06.510Z]     stack: [ [Object], [Object] ]
[2021-05-12T01:43:06.510Z]   }
[2021-05-12T01:43:06.510Z] }
[2021-05-12T01:43:08.280Z] Executed 'Functions.messages' (Succeeded, Id=5876fe29-17f7-4593-a331-7bd381a9e93c, Duration=14779ms)
[2021-05-12T01:43:08.298Z] Executed 'Functions.messages' (Succeeded, Id=d4189c88-8f97-4cc0-8810-acf0abe16bf6, Duration=6900ms)
[2021-05-12T01:43:13.753Z] Executing 'Functions.messages' (Reason='This function was programmatically called via the host APIs.', Id=dff768be-825d-4be1-a343-b77278609c07)
[2021-05-12T01:43:13.768Z] Messages endpoint triggered.
[2021-05-12T01:43:14.103Z] [onTurnError] unhandled error Error: The clientSecret parameter is required.
[2021-05-12T01:43:14.104Z]     at Object.validateStringParameter (C:\Users\joratlif\ComposerSkills\5_11a\NodeFunctionParent511a\NodeFunctionParent511a\node_modules\adal-node\lib\argument.js:37:13)
[2021-05-12T01:43:14.104Z]     at AuthenticationContext.acquireTokenWithClientCredentials (C:\Users\joratlif\ComposerSkills\5_11a\NodeFunctionParent511a\NodeFunctionParent511a\node_modules\adal-node\lib\authentication-context.js:282:14)
[2021-05-12T01:43:14.104Z]     at C:\Users\joratlif\ComposerSkills\5_11a\NodeFunctionParent511a\NodeFunctionParent511a\node_modules\botframework-connector\lib\auth\microsoftAppCredentials.js:49:48
[2021-05-12T01:43:14.105Z]     at new Promise (<anonymous>)
[2021-05-12T01:43:14.105Z]     at MicrosoftAppCredentials.<anonymous> (C:\Users\joratlif\ComposerSkills\5_11a\NodeFunctionParent511a\NodeFunctionParent511a\node_modules\botframework-connector\lib\auth\microsoftAppCredentials.js:48:40)
[2021-05-12T01:43:14.105Z]     at Generator.next (<anonymous>)
[2021-05-12T01:43:14.106Z]     at C:\Users\joratlif\ComposerSkills\5_11a\NodeFunctionParent511a\NodeFunctionParent511a\node_modules\botframework-connector\lib\auth\microsoftAppCredentials.js:15:71
[2021-05-12T01:43:14.106Z]     at new Promise (<anonymous>)
[2021-05-12T01:43:14.107Z]     at __awaiter (C:\Users\joratlif\ComposerSkills\5_11a\NodeFunctionParent511a\NodeFunctionParent511a\node_modules\botframework-connector\lib\auth\microsoftAppCredentials.js:11:12)
[2021-05-12T01:43:14.107Z]     at MicrosoftAppCredentials.refreshToken (C:\Users\joratlif\ComposerSkills\5_11a\NodeFunctionParent511a\NodeFunctionParent511a\node_modules\botframework-connector\lib\auth\microsoftAppCredentials.js:46:16) {
[2021-05-12T01:43:14.108Z]   name: 'DialogContextError',
[2021-05-12T01:43:14.108Z]   dialogContext: {
[2021-05-12T01:43:14.108Z]     activeDialog: "BeginSkill['=settings.skill['dotnetWebappFunctionEcho511A'].msAppId','']",
[2021-05-12T01:43:14.109Z]     parent: 'NodeFunctionParent511a',
[2021-05-12T01:43:14.109Z]     stack: [ [Object], [Object] ]
[2021-05-12T01:43:14.110Z]   }
[2021-05-12T01:43:14.110Z] }
[2021-05-12T01:43:14.151Z] Executed 'Functions.messages' (Succeeded, Id=dff768be-825d-4be1-a343-b77278609c07, Duration=401ms)
[2021-05-12T01:44:03.572Z] Executing 'Functions.messages' (Reason='This function was programmatically called via the host APIs.', Id=2a9e06e2-0c41-49fb-9ac3-bad9ac8e242b)
[2021-05-12T01:44:03.596Z] Messages endpoint triggered.
[2021-05-12T01:44:04.101Z] [onTurnError] unhandled error Error: The clientSecret parameter is required.
[2021-05-12T01:44:04.102Z]     at Object.validateStringParameter (C:\Users\joratlif\ComposerSkills\5_11a\NodeFunctionParent511a\NodeFunctionParent511a\node_modules\adal-node\lib\argument.js:37:13)
[2021-05-12T01:44:04.103Z]     at AuthenticationContext.acquireTokenWithClientCredentials (C:\Users\joratlif\ComposerSkills\5_11a\NodeFunctionParent511a\NodeFunctionParent511a\node_modules\adal-node\lib\authentication-context.js:282:14)
[2021-05-12T01:44:04.103Z]     at C:\Users\joratlif\ComposerSkills\5_11a\NodeFunctionParent511a\NodeFunctionParent511a\node_modules\botframework-connector\lib\auth\microsoftAppCredentials.js:49:48
[2021-05-12T01:44:04.104Z]     at new Promise (<anonymous>)
[2021-05-12T01:44:04.104Z]     at MicrosoftAppCredentials.<anonymous> (C:\Users\joratlif\ComposerSkills\5_11a\NodeFunctionParent511a\NodeFunctionParent511a\node_modules\botframework-connector\lib\auth\microsoftAppCredentials.js:48:40)
[2021-05-12T01:44:04.105Z]     at Generator.next (<anonymous>)
[2021-05-12T01:44:04.106Z]     at C:\Users\joratlif\ComposerSkills\5_11a\NodeFunctionParent511a\NodeFunctionParent511a\node_modules\botframework-connector\lib\auth\microsoftAppCredentials.js:15:71
[2021-05-12T01:44:04.106Z]     at new Promise (<anonymous>)
[2021-05-12T01:44:04.106Z]     at __awaiter (C:\Users\joratlif\ComposerSkills\5_11a\NodeFunctionParent511a\NodeFunctionParent511a\node_modules\botframework-connector\lib\auth\microsoftAppCredentials.js:11:12)
[2021-05-12T01:44:04.107Z]     at MicrosoftAppCredentials.refreshToken (C:\Users\joratlif\ComposerSkills\5_11a\NodeFunctionParent511a\NodeFunctionParent511a\node_modules\botframework-connector\lib\auth\microsoftAppCredentials.js:46:16) {
[2021-05-12T01:44:04.107Z]   name: 'DialogContextError',
[2021-05-12T01:44:04.108Z]   dialogContext: {
[2021-05-12T01:44:04.110Z]     activeDialog: "BeginSkill['=settings.skill['nodeWebapp511A'].msAppId','']",
[2021-05-12T01:44:04.110Z]     parent: 'NodeFunctionParent511a',
[2021-05-12T01:44:04.111Z]     stack: [ [Object], [Object] ]
[2021-05-12T01:44:04.111Z]   }
[2021-05-12T01:44:04.111Z] }
[2021-05-12T01:44:04.152Z] Executed 'Functions.messages' (Succeeded, Id=2a9e06e2-0c41-49fb-9ac3-bad9ac8e242b, Duration=587ms)
[2021-05-12T01:44:06.468Z] Executing 'Functions.messages' (Reason='This function was programmatically called via the host APIs.', Id=baf74197-5ccb-46f8-89e6-4d0591ce8648)
[2021-05-12T01:44:06.482Z] Messages endpoint triggered.
[2021-05-12T01:44:06.628Z] [onTurnError] unhandled error Error: The clientSecret parameter is required.
[2021-05-12T01:44:06.629Z]     at Object.validateStringParameter (C:\Users\joratlif\ComposerSkills\5_11a\NodeFunctionParent511a\NodeFunctionParent511a\node_modules\adal-node\lib\argument.js:37:13)
[2021-05-12T01:44:06.629Z]     at AuthenticationContext.acquireTokenWithClientCredentials (C:\Users\joratlif\ComposerSkills\5_11a\NodeFunctionParent511a\NodeFunctionParent511a\node_modules\adal-node\lib\authentication-context.js:282:14)
[2021-05-12T01:44:06.629Z]     at C:\Users\joratlif\ComposerSkills\5_11a\NodeFunctionParent511a\NodeFunctionParent511a\node_modules\botframework-connector\lib\auth\microsoftAppCredentials.js:49:48
[2021-05-12T01:44:06.629Z]     at new Promise (<anonymous>)
[2021-05-12T01:44:06.629Z]     at MicrosoftAppCredentials.<anonymous> (C:\Users\joratlif\ComposerSkills\5_11a\NodeFunctionParent511a\NodeFunctionParent511a\node_modules\botframework-connector\lib\auth\microsoftAppCredentials.js:48:40)
[2021-05-12T01:44:06.629Z]     at Generator.next (<anonymous>)
[2021-05-12T01:44:06.630Z]     at C:\Users\joratlif\ComposerSkills\5_11a\NodeFunctionParent511a\NodeFunctionParent511a\node_modules\botframework-connector\lib\auth\microsoftAppCredentials.js:15:71
[2021-05-12T01:44:06.630Z]     at new Promise (<anonymous>)
[2021-05-12T01:44:06.630Z]     at __awaiter (C:\Users\joratlif\ComposerSkills\5_11a\NodeFunctionParent511a\NodeFunctionParent511a\node_modules\botframework-connector\lib\auth\microsoftAppCredentials.js:11:12)
[2021-05-12T01:44:06.630Z]     at MicrosoftAppCredentials.refreshToken (C:\Users\joratlif\ComposerSkills\5_11a\NodeFunctionParent511a\NodeFunctionParent511a\node_modules\botframework-connector\lib\auth\microsoftAppCredentials.js:46:16) {
[2021-05-12T01:44:06.631Z]   name: 'DialogContextError',
[2021-05-12T01:44:06.631Z]   dialogContext: {
[2021-05-12T01:44:06.631Z]     activeDialog: "BeginSkill['=settings.skill['nodeFunctionEcho511A'].msAppId','']",
[2021-05-12T01:44:06.631Z]     parent: 'NodeFunctionParent511a',
[2021-05-12T01:44:06.631Z]     stack: [ [Object], [Object] ]
[2021-05-12T01:44:06.632Z]   }
[2021-05-12T01:44:06.632Z] }
[2021-05-12T01:44:06.674Z] Executed 'Functions.messages' (Succeeded, Id=baf74197-5ccb-46f8-89e6-4d0591ce8648, Duration=207ms)

**Comment by sgellock** [comment]
Shiproom - @Virtual-Josh which version of JS SDK are you running to repro this?

**Comment by joshgummersall** [comment]
JS issue was related to bad configuration passed to a skill credential provider (https://github.com/microsoft/botbuilder-js/issues/3674). I've got a fix ready.

**Comment by sgellock** [comment]
Shiproom - core P0 scenario - approved

**Comment by sgellock** [comment]
Shiproom - closing as the above PR resolves the issue
