### ISSUE TITLE
The application wont start after installing

### ISSUE THREAD

**Issue by deathblade89** [microsoft/BotFramework-Composer#8415]
## Describe the bug

Complete install wizard successfully

## Version

BotFramework-Composer-2.0.0-windows-setup

## Browser

Unknown, its the app installed, i assume is Electron.

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

Complete installation, the application hangs on starting server.

## Expected behavior

The application should start

## Screenshots

![image](https://user-images.githubusercontent.com/16613924/125808813-d39c8dbe-399a-4b2e-b59a-87a394367191.png)

## Additional context

Running in a terminal window provides the following:
```
./"Bot Framework Composer.exe"
PS C:\Users\Jason Werber\AppData\Local\Programs\Bot Framework Composer>
(node:5392) UnhandledPromiseRejectionWarning: Error: getBaseUrl() called before serverPort is defined.
    at getBaseUrl (C:\Users\Jason Werber\AppData\Local\Programs\Bot Framework Composer\resources\app.asar\build\main.js:42:15)
    at C:\Users\Jason Werber\AppData\Local\Programs\Bot Framework Composer\resources\app.asar\build\main.js:236:58
    at Generator.next (<anonymous>)
    at C:\Users\Jason Werber\AppData\Local\Programs\Bot Framework Composer\resources\app.asar\node_modules\tslib\tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\Jason Werber\AppData\Local\Programs\Bot Framework Composer\resources\app.asar\node_modules\tslib\tslib.js:110:16)
    at App.<anonymous> (C:\Users\Jason Werber\AppData\Local\Programs\Bot Framework Composer\resources\app.asar\build\main.js:228:71)
    at App.emit (events.js:210:5)
(node:5392) UnhandledPromiseRejectionWarning: Error: getBaseUrl() called before serverPort is defined.
    at getBaseUrl (C:\Users\Jason Werber\AppData\Local\Programs\Bot Framework Composer\resources\app.asar\build\main.js:42:15)
    at C:\Users\Jason Werber\AppData\Local\Programs\Bot Framework Composer\resources\app.asar\build\main.js:236:58
    at Generator.next (<anonymous>)
    at C:\Users\Jason Werber\AppData\Local\Programs\Bot Framework Composer\resources\app.asar\node_modules\tslib\tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\Jason Werber\AppData\Local\Programs\Bot Framework Composer\resources\app.asar\node_modules\tslib\tslib.js:110:16)
    at App.<anonymous> (C:\Users\Jason Werber\AppData\Local\Programs\Bot Framework Composer\resources\app.asar\build\main.js:228:71)
    at App.emit (events.js:210:5)
(node:5392) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:5392) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
(node:5392) UnhandledPromiseRejectionWarning: Error: getBaseUrl() called before serverPort is defined.
    at getBaseUrl (C:\Users\Jason Werber\AppData\Local\Programs\Bot Framework Composer\resources\app.asar\build\main.js:42:15)
    at C:\Users\Jason Werber\AppData\Local\Programs\Bot Framework Composer\resources\app.asar\build\main.js:236:58
    at Generator.next (<anonymous>)
    at C:\Users\Jason Werber\AppData\Local\Programs\Bot Framework Composer\resources\app.asar\node_modules\tslib\tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\Jason Werber\AppData\Local\Programs\Bot Framework Composer\resources\app.asar\node_modules\tslib\tslib.js:110:16)
    at App.<anonymous> (C:\Users\Jason Werber\AppData\Local\Programs\Bot Framework Composer\resources\app.asar\build\main.js:228:71)
    at App.emit (events.js:210:5)
(node:5392) UnhandledPromiseRejectionWarning: Error: getBaseUrl() called before serverPort is defined.
    at getBaseUrl (C:\Users\Jason Werber\AppData\Local\Programs\Bot Framework Composer\resources\app.asar\build\main.js:42:15)
    at C:\Users\Jason Werber\AppData\Local\Programs\Bot Framework Composer\resources\app.asar\build\main.js:236:58
    at Generator.next (<anonymous>)
    at C:\Users\Jason Werber\AppData\Local\Programs\Bot Framework Composer\resources\app.asar\node_modules\tslib\tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\Jason Werber\AppData\Local\Programs\Bot Framework Composer\resources\app.asar\node_modules\tslib\tslib.js:110:16)
    at App.<anonymous> (C:\Users\Jason Werber\AppData\Local\Programs\Bot Framework Composer\resources\app.asar\build\main.js:228:71)
    at App.emit (events.js:210:5)
(node:5392) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:5392) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

**Comment by srinaath** [comment]
@deathblade89 Could you help us by running the app with the debug flag on and paste the output here. Following are the steps.

Go to Composer's install location (mine is at C:\Users\{username}\AppData\Local\Programs\Bot Framework Composer)
Open a terminal here
run set DEBUG=composer*
run the executable from the terminal Ex. "Bot Framework Composer.exe"

**Comment by victorlamana** [comment]
Hello, I had the same issue and Microsoft helped me fixing it by installing vcredist. See https://github.com/microsoft/BotFramework-Composer/issues/7964

**Comment by deathblade89** [comment]
@srinaath The Bot Framework Composer updated last night and I repaired my vcredist installation.
Now the application opens using the command line with DEBUG=composer* and I can continue at this point.

**Comment by hatpick** [comment]
@deathblade89 you dont need that flag to run the app, we wanted to get full logs for your issue.
