### ISSUE TITLE
Not able to create new bot from Bot Framework Composer

### ISSUE THREAD

**Issue by myarycn** [microsoft/BotFramework-Composer#8729]
It shows error no matter what type of bot I picked:
Error calling npm to fetch template. Please ensure that node and npm are installed and available on your system. Full error message: Command failed with ENOENT: npm root -g --prefix C:\Users\yixinchen\AppData\Roaming\BotFrameworkComposer\.yo-repository --loglevel error spawnSync cmd.exe ENOENT

I'm able to get npm and node version:
node -v ==> v14.18.0
npm -v ==> 7.24.2
However this errors keeps pop up like always. I also uninstalled all and reinstall but still end up with no luck. Could you pls help??? Thank you!

**Comment by tonyanziano** [comment]
@myarycn and I hopped on a call and tried to debug the issue. We discovered that [this is the line that is throwing](https://github.com/microsoft/BotFramework-Composer/blob/main/Composer/packages/server-workers/src/workers/templateInstallation.worker.ts#L22) which eventually ends up at the npm library `execa` making a call to `childProcess.spawnSync()` with the command above that fails with `ENOENT`.

We tried to set a breakpoint at the call, but unfortunately since the template installation happens in a Node `worker_thread`, we cannot debug it.

She has no issue executing the command outside of Composer, but Composer can't seem to get past that command, which just generates a path to the templates directory.

@benbrown feel free to add anything if you have any ideas.

===

For now, there is a workaround -- you just need to have someone else create a bot via Composer and then send the generated bot folder to you. Then you should be able to open the bot inside of Composer and start authoring without any issues.

**Comment by rodalonts** [comment]
Hi, i have the same problem, i read the steps above but it didn´t work. This is my log: 

  ALLUSERSPROFILE: 'C:\\ProgramData',
  APPDATA: 'C:\\Users\\rtorress\\AppData\\Roaming',
  CommonProgramFiles: 'C:\\Program Files\\Common Files',
  'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
  CommonProgramW6432: 'C:\\Program Files\\Common Files',
  COMPUTERNAME: 'SJ11845-735570',
  ComSpec: 'C:\\Windows\\system32\\cmd.exe',
  DEBUG: 'composer*',
  DEFLOGDIR: 'C:\\ProgramData\\McAfee\\Endpoint Security\\Logs',
  DriverData: 'C:\\Windows\\System32\\Drivers\\DriverData',
  FPS_BROWSER_APP_PROFILE_STRING: 'Internet Explorer',
  FPS_BROWSER_USER_PROFILE_STRING: 'Default',
  HOMEDRIVE: 'C:',
  HOMEPATH: '\\Users\\rtorress',
  KeaAgent: '"C:\\Program Files (x86)\\Kaspersky Lab\\Endpoint Agent\\agent.exe"',
  LOCALAPPDATA: 'C:\\Users\\rtorress\\AppData\\Local',
  LOGONSERVER: '\\\\SJODCO11',
  NUMBER_OF_PROCESSORS: '12',
  OneDrive: 'C:\\Users\\rtorress\\OneDrive - Poder Judicial CR',
  OneDriveCommercial: 'C:\\Users\\rtorress\\OneDrive - Poder Judicial CR',
  OS: 'Windows_NT',
  Path: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\wbin;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Users\\rtorress\\AppData\\Roaming\\npm\\node_modules\\chromedriver\\lib\\chromedriver;C:\\Program Files\\nodejs;C:\\Program Files\\dotnet\\;C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\;C:\\Program Files\\Azure Data Studio\\bin;C:\\Program Files (x86)\\Microsoft SQL Server\\150\\DTS\\Binn\\;C:\\Program Files\\Docker\\Docker\\resources\\bin;C:\\ProgramData\\DockerDesktop\\version-bin;C:\\Program Files\\nodejs\\;C:\\Program Files (x86)\\Microsoft SQL Server\\160\\DTS\\Binn\\;C:\\Users\\rtorress\\AppData\\Local\\Programs\\Python\\Python38\\Scripts\\;C:\\Users\\rtorress\\AppData\\Local\\Programs\\Python\\Python38\\;C:\\Users\\rtorress\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.24.28314\\bin\\Hostx86\\x64;C:\\Program Files\\Azure Data Studio\\bin;C:\\Users\\rtorress\\.dotnet\\tools;C:\\Program Files\\Azure Data Studio\\bin;C:\\Program Files\\Azure Data Studio\\bin;C:\\Users\\rtorress\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\rtorress\\AppData\\Roaming\\npm;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;',
  PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
  PROCESSOR_ARCHITECTURE: 'AMD64',
  PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 158 Stepping 13, GenuineIntel',
  PROCESSOR_LEVEL: '6',
  PROCESSOR_REVISION: '9e0d',
  ProgramData: 'C:\\ProgramData',
  ProgramFiles: 'C:\\Program Files',
  'ProgramFiles(x86)': 'C:\\Program Files (x86)',
  ProgramW6432: 'C:\\Program Files',
  PROMPT: '$P$G',
  PSModulePath: 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules',
  PUBLIC: 'C:\\Users\\Public',
  SESSIONNAME: 'Console',
  SystemDrive: 'C:',
  SystemRoot: 'C:\\Windows',
  TEMP: 'C:\\Users\\rtorress\\AppData\\Local\\Temp',
  TMP: 'C:\\Users\\rtorress\\AppData\\Local\\Temp',
  UATDATA: 'C:\\Windows\\CCM\\UATData\\D9F8C395-CAB8-491d-B8AC-179A1FE1BE77',
  USERDNSDOMAIN: 'ORG.PODER-JUDICIAL.GO.CR',
  USERDOMAIN: 'PODER-JUDICIAL',
  USERDOMAIN_ROAMINGPROFILE: 'PODER-JUDICIAL',
  USERNAME: 'rtorress',
  USERPROFILE: 'C:\\Users\\rtorress',
  VBOX_MSI_INSTALL_PATH: 'C:\\Program Files\\Oracle\\VirtualBox\\',
  windir: 'C:\\Windows',
  ZES_ENABLE_SYSMAN: '1'
}
2022-06-28T21:14:07.223Z composer:electron production environment detected.
2022-06-28T21:14:07.225Z composer:electron Run completed
2022-06-28T21:14:07.257Z composer:electron App ready
2022-06-28T21:14:07.257Z composer:electron Loading latest known locale
2022-06-28T21:14:07.259Z composer:electron:electron-window Raw screen dimensions: 824 x 1536
2022-06-28T21:14:07.259Z composer:electron:electron-window Electron window dimensions: 741 x 988
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
2022-06-28T21:14:07.276Z composer:electron:electron-window Rendered Electron window dimensions:  [ 989, 743 ]
2022-06-28T21:14:07.857Z composer:electron Creating app data directory...
2022-06-28T21:14:07.857Z composer:electron creating composer app data path at:  C:\Users\rtorress\AppData\Roaming\BotFrameworkComposer
2022-06-28T21:14:07.858Z composer:electron creating local bot runtime publish path:  C:\Users\rtorress\AppData\Roaming\BotFrameworkComposer\hostedBots
2022-06-28T21:14:07.861Z composer:electron Created app data directory.
2022-06-28T21:14:07.861Z composer:electron Starting server...
'wmic' is not recognized as an internal or external command,
operable program or batch file.
Error: Command failed: wmic volume get name
'wmic' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:634:11)
    at Object.execSync (child_process.js:670:15)
    at Object.execSync (electron/js2c/asar.js:696:23)
    at Object.<anonymous> (C:\Users\rtorress\AppData\Local\Programs\Bot Framework Composer\resources\app.asar\node_modules\@bfc\server\build\settings\env.js:28:48)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 27 77 6d 69 63 27 20 69 73 20 6e 6f 74 20 72 65 63 6f 67 6e 69 7a 65 64 20 61 73 20 61 6e 20 69 6e 74 65 72 6e 61 6c 20 6f 72 20 65 78 74 65 72 6e 61 ... 45 more bytes>
  ],
  pid: 11296,
  stdout: <Buffer >,
  stderr: <Buffer 27 77 6d 69 63 27 20 69 73 20 6e 6f 74 20 72 65 63 6f 67 6e 69 7a 65 64 20 61 73 20 61 6e 20 69 6e 74 65 72 6e 61 6c 20 6f 72 20 65 78 74 65 72 6e 61 ... 45 more bytes>
}
2022-06-28T21:14:08.472Z composer App Settings: {
  botAdminEndpoint: 'http://localhost:3979',
  botEndpoint: 'http://localhost:3979',
  botsFolder: 'C:\\Users\\rtorress',
  runtimeFrameworkVersion: 'netcoreapp3.1',
  appDataPath: 'C:\\Users\\rtorress\\AppData\\Roaming\\BotFrameworkComposer\\data.json',
  platform: 'win32',
  diskNames: [],
  extensions: {
    manifestPath: 'C:\\Users\\rtorress\\AppData\\Roaming\\BotFrameworkComposer\\extensions.json',
    dataDir: 'C:\\Users\\rtorress\\AppData\\Roaming\\BotFrameworkComposer\\extension-data',
    builtinDir: 'C:\\Users\\rtorress\\AppData\\Local\\Programs\\Bot Framework Composer\\resources\\app.asar.unpacked\\extensions',
    remoteDir: 'C:\\Users\\rtorress\\AppData\\Roaming\\BotFrameworkComposer\\extensions',
    settingsPath: 'C:\\Users\\rtorress\\AppData\\Roaming\\BotFrameworkComposer\\extension-settings.json'
  }
}
2022-06-28T21:14:09.320Z composer:telemetry Setting up App Insights
2022-06-28T21:14:09.324Z composer:telemetry Starting Application Insights
2022-06-28T21:14:09.335Z composer:telemetry Started Application Insights
2022-06-28T21:14:09.443Z composer:electron-auth-provider Initialized.
2022-06-28T21:14:09.443Z composer:auth-service Initialized in Electron context.
2022-06-28T21:14:09.444Z composer:auth-service Production environment detected. Generating CSRF token.
Tue, 28 Jun 2022 21:14:09 GMT express-session deprecated undefined resave option; provide resave option at resources\app.asar\node_modules\@bfc\server\build\server.js:56:17
Tue, 28 Jun 2022 21:14:09 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at resources\app.asar\node_modules\@bfc\server\build\server.js:56:17
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
2022-06-28T21:14:09.552Z composer:extension-manager Loading extensions from C:\Users\rtorress\AppData\Local\Programs\Bot Framework Composer\resources\app.asar.unpacked\extensions
2022-06-28T21:14:09.998Z composer:extensions registering publish method azurePublish
2022-06-28T21:14:10.070Z composer:extensions registering publish method localpublish
(node:8552) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:8552) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
2022-06-28T21:14:10.556Z composer:extensions registering publish method azurePublishNew
2022-06-28T21:14:10.557Z composer:extensions:azure-publish-new Reading from store:
{ some: 'data' }
2022-06-28T21:14:10.557Z composer:extensions:azure-publish-new Reading from store:
{ some: 'data' }
2022-06-28T21:14:10.662Z composer:extensions registering publish method pva-publish-composer
2022-06-28T21:14:10.680Z composer:extension-manager Loading extensions from C:\Users\rtorress\AppData\Roaming\BotFrameworkComposer\extensions


Composer now running at:

http://localhost:5000

2022-06-28T21:14:10.694Z composer:electron Server started at port: 5000
2022-06-28T21:14:10.695Z composer:electron Rendering application...
GET / 200 7.536 ms - 953
2022-06-28T21:14:11.329Z composer:electron Initializing app updater...
2022-06-28T21:14:11.368Z composer:electron Initialized
2022-06-28T21:14:11.368Z composer:electron:app-updater Updates set to be retrieved from stable repo.
2022-06-28T21:14:11.374Z composer:electron:app-updater Updating from stable to stable. Not allowing downgrade.
Checking for update
2022-06-28T21:14:11.375Z composer:electron:app-updater Checking for updates...
2022-06-28T21:14:11.375Z composer:electron App updater initialized.
GET /api/extensions 304 1.490 ms - -
POST /api/settings 200 2.153 ms - 43
2022-06-28T21:14:11.968Z composer:extension-manager Including defaults in settings.
GET /api/extensions/settings?_all 304 2.661 ms - -
GET /api/featureFlags 304 1.894 ms - -
GET /api/assets/locales/en-US.json 200 54.331 ms - -
GET /api/utilities/checkNode 304 120.798 ms - -
GET /api/storages 304 0.763 ms - -
GET /api/storages/default/blobs?path=%252Fprueba 304 2.382 ms - -
GET /api/assets/templateFeedUrl 304 1.080 ms - -
GET /api/projects/recent 304 1.839 ms - -
2022-06-28T21:14:12.453Z composer:electron Rendered application.
2022-06-28T21:14:12.967Z composer:electron [Windows] Main window is now showing. Processing deep link if any.
GET /api/projects/feed 304 1257.602 ms - -
POST /api/assets/projectTemplates 200 1749.508 ms - -
Update for version 2.1.2 is not available (latest version: 2.1.2, downgrade is disallowed).
2022-06-28T21:14:14.041Z composer:electron:app-updater Update not available: {
  version: '2.1.2',
  releaseDate: '2022-02-03T18:15:30.576Z',
  githubArtifactName: 'BotFramework-Composer-2.1.2-windows-setup.exe',
  path: 'BotFramework-Composer-2.1.2-windows-setup.exe',
  sha512: 'N9I4LoVbyNcCZz4y8Fwk475tDho/5JLPd+K8htvmgs7jc/d+PKWMtZnJQf7iQfIjR1u3TaTKyRfFTelLAalXQQ==',
  releaseName: '2.1.2',
  releaseNotes: '<p>This is a STABLE release of Composer.</p>\n' +
    '<p><a href="https://github.com/microsoft/BotFramework-Composer/blob/main/releases/2.1.2.md">https://github.com/microsoft/BotFramework-Composer/blob/main/releases/2.1.2.md</a></p>'
}
2022-06-28T21:14:14.042Z composer:electron:app-updater Resetting to idle...
GET /api/assets/templateReadme?moduleName=%2540microsoft%252Fgenerator-bot-empty 304 1371.890 ms - -
GET /api/assets/templateReadme?moduleName=QnASample 304 642.432 ms - -
2022-06-28T21:14:26.877Z composer Attempting to create project at /prueba
POST /api/projects 202 0.585 ms - 48
2022-06-28T21:14:26.880Z composer About to create folder /prueba/CoreWithQnA
2022-06-28T21:14:27.475Z composer:worker:templateInstallation Getting Yeoman environment
2022-06-28T21:14:27.485Z composer Cleaning up failed project at  /prueba/CoreWithQnA
GET /api/status/d5f8f715-043d-4630-8fd5-78ea411f06e9 500 0.793 ms - -

**Comment by rahulmakwana92** [comment]
Any update on this ? I have exact same log while creating a bot in debug mode.

**Comment by mikeon** [comment]
Yeah me too
