### ISSUE TITLE
Renaming Dialogs

### ISSUE THREAD

**Issue by TylerDKnight** [microsoft/BotFramework-Composer#8736]
## Describe the bug

The Framework Composer seems to have issues building the project if you rename the top level dialog. This problem also exists for renaming child dialogs, but doing so only disrupts the UX if it is accessed during the conversation flow. I used the CoreWithLanguage template, made a few child dialogs, then attempted to change the name of CoreWithLanguage to MetricIntent. It did not build. When I then changed it back to CoreWithLanguage to revert the bug, the original name also failed to build. The words in the error message flip flop, suggesting there is something sluggish happening behind the scenes. Closing and 

## Version

Version: 2.1.1
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## OS

Windows 10

## To Reproduce

1. Create a CoreWithLanguage bot template (or any template I guess)
2. Edit the name of the dialog in the properties pane
3. Build the project
4. See error. Build failed.

## Expected behavior

I expected the Framework Composer to acknowledge the name change and propagate it automatically through the rest of the bot code and the LUIS backend.

## Additional context

Output trace (personal information censored):

Error occurred building the bot

Error: Resource MetricIntent.dialog not found. at ConfigurationResourceExporer.loadType (C:\Users\*****\*******************\CoreWithLanguage\CoreWithLanguage\node_modules\botbuilder-dialogs-declarative\lib\resources\resourceExplorer.js:195:19) at DialogExpressionConverter.convert (C:\Users\*****\*******************\CoreWithLanguage\CoreWithLanguage\node_modules\botbuilder-dialogs-adaptive\lib\converters\dialogExpressionConverter.js:34:55) at C:\Users\*****\*******************\CoreWithLanguage\CoreWithLanguage\node_modules\botbuilder-dialogs-declarative\lib\defaultLoader.js:37:48 at Array.reduce (<anonymous>) at DefaultLoader.load (C:\Users\*****\*******************\CoreWithLanguage\CoreWithLanguage\node_modules\botbuilder-dialogs-declarative\lib\defaultLoader.js:31:39) at ConfigurationResourceExporer.load (C:\Users\*****\*******************\CoreWithLanguage\CoreWithLanguage\node_modules\botbuilder-dialogs-declarative\lib\resources\resourceExplorer.js:240:23) at Array.<anonymous> (C:\Users\*****\*******************\CoreWithLanguage\CoreWithLanguage\node_modules\botbuilder-dialogs-declarative\lib\resources\resourceExplorer.js:214:25) at JSON.parse (<anonymous>) at ConfigurationResourceExporer.loadType (C:\Users\*****\*******************\CoreWithLanguage\CoreWithLanguage\node_modules\botbuilder-dialogs-declarative\lib\resources\resourceExplorer.js:203:36) at new CoreBot (C:\Users\*****\*******************\CoreWithLanguage\CoreWithLanguage\node_modules\botbuilder-dialogs-adaptive-runtime\lib\coreBot.js:22:45) npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! CoreWithLanguage@ dev: `cross-env NODE_ENV=dev node index.js "--port" "3981" "--urls" "http://0.0.0.0:3981" "--luis:endpointKey" "********************************" "--SkillHostEndpoint" "http://127.0.0.1:3981/api/skills"` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the CoreWithLanguage@ dev script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above. npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\*****\AppData\Roaming\npm-cache\_logs\2021-10-11T18_38_36_577Z-debug.log

**Comment by dmvtech** [comment]
Hi @TylerDKnight Any updates or further information you can share to help us reproduce or understand what might be going on?
