### ISSUE TITLE
Impossible to create and build new bot (uimportant)!

### ISSUE THREAD

**Issue by Levis0045** [microsoft/BotFramework-Composer#8871]
## Describe the bug

I have downloaded the last version of Bot Framework Composer (v2.0.0) running file image. When I want to create new bot, i have some errors on my node and npm version {"node":"8.10.0","npm":"3.5.2"}. 

whereas my current node version is v14.18.1 and npm is v6.14.15

## Version

V2.0.0

## Browser

- [ ] Electron distribution
- [ x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [x ] Ubuntu

## To Reproduce

1. Go to 'Home'
2. Click on 'Create new'
3. Complete bot info

Command failed: npm install && npm install --only=dev WARN engine cross-env@7.0.3: wanted: {"node":">=10.14","npm":">=6","yarn":">=1"} (current: {"node":"8.10.0","npm":"3.5.2"}) npm WARN deprecated uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details. WARN engine @xmldom/xmldom@0.7.5: wanted: {"node":">=10.0.0"} (current: {"node":"8.10.0","npm":"3.5.2"}) WARN engine @microsoft/recognizers-text-data-types-timex-expression@1.3.0: wanted: {"node":">=10.3.0"} (current: {"node":"8.10.0","npm":"3.5.2"}) WARN engine @azure/identity@2.0.0-beta.6: wanted: {"node":">=12.0.0"} (current: {"node":"8.10.0","npm":"3.5.2"}) WARN engine stoppable@1.1.0: wanted: {"node":">=4","npm":">=6"} (current: {"node":"8.10.0","npm":"3.5.2"}) WARN engine @azure/core-rest-pipeline@1.3.2: wanted: {"node":">=12.0.0"} (current: {"node":"8.10.0","npm":"3.5.2"}) WARN engine @azure/msal-node@1.4.0: wanted: {"node":"10 || 12 || 14 || 16"} (current: {"node":"8.10.0","npm":"3.5.2"}) WARN engine @azure/core-tracing@1.0.0-preview.13: wanted: {"node":">=12.0.0"} (current: {"node":"8.10.0","npm":"3.5.2"}) WARN engine @azure/core-client@1.3.3: wanted: {"node":">=12.0.0"} (current: {"node":"8.10.0","npm":"3.5.2"}) WARN engine @azure/core-auth@1.3.2: wanted: {"node":">=12.0.0"} (current: {"node":"8.10.0","npm":"3.5.2"}) WARN engine @azure/logger@1.0.3: wanted: {"node":">=12.0.0"} (current: {"node":"8.10.0","npm":"3.5.2"}) npm ERR! Linux 5.4.0-91-generic npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" npm ERR! node v8.10.0 npm ERR! npm v3.5.2 npm ERR! code EMISSINGARG npm ERR! typeerror Error: Missing required argument #1 npm ERR! typeerror at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3) npm ERR! typeerror at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22) npm ERR! typeerror at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12) npm ERR! typeerror at /usr/share/npm/lib/install/deps.js:457:7 npm ERR! typeerror at /usr/share/npm/node_modules/iferr/index.js:13:50 npm ERR! typeerror at /usr/share/npm/lib/fetch-package-metadata.js:37:12 npm ERR! typeerror at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5) npm ERR! typeerror at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7) npm ERR! typeerror at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20) npm ERR! typeerror at /usr/share/npm/node_modules/iferr/index.js:13:50 npm ERR! typeerror This is an error with npm itself. Please report this error at: npm ERR! typeerror <http://github.com/npm/npm/issues> npm ERR! Please include the following file with any support request: npm ERR! 

## Expected behavior

Just create new bot

## Screenshots

![image](https://user-images.githubusercontent.com/13846122/147083332-f619acd1-afde-42f9-8a25-c23b8cf2c541.png)

**Comment by anishprasad01** [comment]
Hi @Levis0045,

A few things here. 

First of all, the latest release of Composer is not `2.0.0`, it's `2.1.1`. `2.0.0` is two versions behind.

Secondly, I need more info from you before I can investigate.

- What kind of bot are you trying to make? C# or Node?
- Is your problem specific to one language? Can you make a bot in the other language?
- Are you using one of the sample template bots? If so, which one?
- Do you have the required .NET versions installed?
- How did you install Composer? Did you build from source or did you download and install a pre-complied release?
- Have you tried reinstalling Composer?
- Does it work if you upgrade Composer to version [2.1.1](https://github.com/microsoft/BotFramework-Composer/releases/tag/v2.1.1)?

**Comment by anishprasad01** [comment]
Closing this issue due to inactivity.

**Comment by Levis0045** [comment]
Hi @anishprasad01 ,

Please see my answers below:

What kind of bot are you trying to make? C# or **Node** ?
Is your problem specific to one language? **Yes** Can you make a bot in the other language? **No**
Are you using one of the sample template bots?  **No, i try to create new one with Composer** If so, which one? 
Do you have the required .NET versions installed? **Yes**
How did you install Composer? Did you build from source or did you **download and install a pre-complied release**? https://aka.ms/bf-composer-download-linux
Have you tried reinstalling Composer? **It is a pre-complied release**
Does it work if you upgrade Composer to version 2.1.1 **Yes** ?

![image](https://user-images.githubusercontent.com/13846122/147736006-13958efa-1a2e-4789-b101-2228bdcc4fa6.png)

**Comment by Levis0045** [comment]
> Closing this issue due to inactivity.

PLease, i send you somme details

**Comment by anishprasad01** [comment]
> Does it work if you upgrade Composer to version 2.1.1 Yes ?

So it works if you use Composer 2.1.1? Then why not just upgrade to that version?

**Comment by anishprasad01** [comment]
Just to be sure, I attempted to repro this on Ubuntu 20.04 LTS using Composer 2.1.1 and Node.js 14.18.2 LTS, and I was able to create and run an empty bot.

It appears that the links on the Composer install page are a bit out of date, and link to a download for version 2.0.0. You can download the latest version of Composer from the Composer repository [Releases page](https://github.com/microsoft/BotFramework-Composer/releases).

**Comment by Levis0045** [comment]
My problem is now resolved! The problem was that composer don't find the right version of my node js. The only use the system installation package in */usr/share/...* not in nvm in local user directory

Thanks for the support @anishprasad01
