### ISSUE TITLE
Cannot publish a bot from Bot Framework Composer to Azure. TypeError - Cannot Read property 'AzureSubscriptionId' of undefined

### ISSUE THREAD

**Issue by krassussofficial** [microsoft/BotFramework-Composer#9007]
## Describe the bug
I am unable to publish my bot from Composer to Azure. I'm getting:

**TypeError - Cannot Read property 'AzureSubscriptionId' of undefined**

The bot builds locally just fine.

In the publishing profile the subscription ID has been correctly specified.

## Version
2.1.2

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [x] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Expected behavior

Bot publishes to my Azure subscription.

## Additional context

I have been able to publish the bot previously but I had to change LUIS to a new one. After substituting the following variables in the publishing profile:

- "luisResource"
-  "luis""authoringKey"
-  "luis""endpointKey"

I am getting the error above.

**LOGS:**

`
"Accepted for publishing..."

"Abs settings incomplete, skip linking bot with webapp ..."

"appPasswordHint incomplete, return ..."

"Building the bot app..."

"Build succeeded!"

"start publish luis"

"Assigning to luis app id: 4667de23-fce7-4693-bfd6-dc2e02e694d4"

"{\n  \"stack\": \"Error: Request failed with status code 400\\n    at createError (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:105969:17)\\n    at settle (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:105983:14)\\n    at IncomingMessage.handleStreamEnd (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:106970:13)\\n    at IncomingMessage.emit (events.js:215:7)\\n    at endReadableNT (_stream_readable.js:1183:12)\\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\",\n  \"message\": \"Request failed with status code 400\",\n  \"config\": {}\n}"

"{\"stack\":\"TypeError: Cannot read property 'AzureSubscriptionId' of undefined\\n    at publishLuisToPrediction (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:276585:133)\",\"message\":\"Cannot read property 'AzureSubscriptionId' of undefined\"}"

"TypeError - Cannot read property 'AzureSubscriptionId' of undefined"
``
`

**Comment by 2-Ram** [comment]
Hi @krassussofficial -- I'm investigating this.

**Comment by ramfattah** [comment]
Hi @krassussofficial -- I'm investigating this.

**Comment by ramfattah** [comment]
Hi @krassussofficial, 

Have you tried to clear composer data/cache? 

In Composer: `View -> ToggleDeveloper Tools -> Application -> Clear storage -> Clear site data`
   <img src="https://i.gyazo.com/c4b516b64a956a1f5087586596d56c1c.png" width="500"/>

---

Also if the above step did not work, could you please check if you're in the correct azure directory using the Azure cli. [Commands in an Azure subscription](https://docs.microsoft.com/en-us/cli/azure/manage-azure-subscriptions-azure-cli#:~:text=the%20Azure%20CLI.-,Commands%20in%20an%20Azure%20subscription,-Many%20Azure%20CLI)

In Powershell, enter the following command: `az account list --output table`

Let me know if this helps.

**Comment by krassussofficial** [comment]
Hi @ramfattah 

thanks for your answer,
Unfortunately clearing the cache didn't help, also the Subscription ID in Powershell checks out with the one in publishing profile.
Do you have any other ideas how to address the issue?

Best Regards

**Comment by ramfattah** [comment]
Hey @krassussofficial 

Perhaps clearing any Azure related credentials in your Windows OS might help? Below are the steps

Clear Windows Credentials using "Credential Manager":
1) On your Windows OS, click start
2) Search for "Credential Manager"
     <img src="https://i.gyazo.com/da014923e5c5f7395d89e2de8016e788.png" width="500"/>
3) Click "Windows Credentials"
     <img src="https://i.gyazo.com/d4c15404ee004cb00de47d6ad3652300.png" width="700"/>
4) Clear azure related credentials

Try these steps and let me know if this works.

**Comment by krassussofficial** [comment]
Hi @ramfattah,

I have cleared the credentials, unfortunately I'm still getting the same error.

Additional thing I noticed is that People-skill from the same project publishes to the same Azure subscription without any problems.

**Comment by ramfattah** [comment]
Hi @krassussofficial 

Perhaps changing the Luis keys in the publishing profile is the cause of this issue. Can you create a new publishing profile with the "Import existing resources" option selected and provide all the correct info.

Provide info from your previous publishing profile
<img src="https://i.gyazo.com/997726f1088eec95289d39e871ff9c2c.png" width="700"/>

Let me know if this helps.

**Comment by ramfattah** [comment]
Closing due to inactivity, please feel free to re-open if you are still having issues.

**Comment by krassussofficial** [comment]
@ramfattah 

Thank you for you assistance! :)

**Comment by ramfattah** [comment]
@krassussofficial no problem. Glad to help!
