### ISSUE TITLE
Unable to sign into Bot Framework Composer - No Azure Directories were found

### ISSUE THREAD

**Issue by nickfrancis** [microsoft/BotFramework-Composer#9008]
## Describe the bug

I've got an Azure instance. Have successfully signed into Bot Emulator & Azure cli but cannot sign into Bot Composer at all - just get the error message "No Azure Directories were found"

Interestingly after I put in my e-mail address it is not asking me for a password, it just errors out.

## Version

Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [x ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ x] Windows
- [ ] Ubuntu

## Additional context

Found another post here which suggested getting the console log. The relevant bit of the console log is pasted below:

2022-02-22T15:17:44.454Z composer:electron:app-updater Resetting to idle...
POST /api/assets/projectTemplates 200 1219.000 ms - -
POST /api/telemetry/events 200 2.200 ms - 2
2022-02-22T15:18:25.141Z composer:electron:one-auth PII logging enabled: false
2022-02-22T15:18:25.142Z composer:electron:one-auth Attempting to load oneauth module from C:\Users\*****\AppData\Local\Programs\Bot Framework Composer\resources\app.asar.unpacked\oneauth.
2022-02-22T15:18:25.151Z composer:electron:one-auth Initializing...
2022-02-22T15:18:25.154Z composer:electron:one-auth Service initialized.
2022-02-22T15:18:25.154Z composer:electron:one-auth Logging user into ARM...
[OneAuth:Warning:9a8hm:e993a05e-b8e0-41ca-8c3f-9a5aefa91694] HTTP status: 403
[OneAuth:Warning:9a8hm:e993a05e-b8e0-41ca-8c3f-9a5aefa91694] HTTP status: 403
2022-02-22T15:18:26.168Z composer:electron:one-auth 3 [OneAuth:Warning:9a8hm:e993a05e-b8e0-41ca-8c3f-9a5aefa91694] HTTP status: 403
[OneAuth:Error:835v1:e993a05e-b8e0-41ca-8c3f-9a5aefa91694] (Code:2001) The resource is forbidden.
[OneAuth:Error:835v1:e993a05e-b8e0-41ca-8c3f-9a5aefa91694] (Code:2001) The resource is forbidden.
[OneAuth:Warning:96w1t:e993a05e-b8e0-41ca-8c3f-9a5aefa91694] Failed to get profile image from Graph
[OneAuth:Warning:96w1t:e993a05e-b8e0-41ca-8c3f-9a5aefa91694] Failed to get profile image from Graph
2022-02-22T15:18:26.169Z composer:electron:one-auth 2 [OneAuth:Error:835v1:e993a05e-b8e0-41ca-8c3f-9a5aefa91694] (Code:2001) The resource is forbidden.
2022-02-22T15:18:26.169Z composer:electron:one-auth 3 [OneAuth:Warning:96w1t:e993a05e-b8e0-41ca-8c3f-9a5aefa91694] Failed to get profile image from Graph
2022-02-22T15:18:33.891Z composer:electron:one-auth 3 [MSAL:0009]       WARNING TryReadUniversalStorage:343     Attempted to read cache with a non-normalized realm, access token and ID token reads will fail
2022-02-22T15:18:33.894Z composer:electron:one-auth 3 [MSAL:0009]       WARNING TryReadUniversalStorage:447     No id token found in the cache
2022-02-22T15:18:33.895Z composer:electron:one-auth 3 [MSAL:0009]       WARNING TryReadUniversalStorage:463     No access token found in the cache
[OneAuth:Warning:9a8hm:70049068-65f5-42e0-acbe-c7404bb4497f] HTTP status: 403
[OneAuth:Warning:9a8hm:70049068-65f5-42e0-acbe-c7404bb4497f] HTTP status: 403
[OneAuth:Error:835v1:70049068-65f5-42e0-acbe-c7404bb4497f] (Code:2001) The resource is fo```
rbidden.2022-02-22T15:18:34.290Z composer:electron:one-auth 3 [OneAuth:Warning:9a8hm:70049068-65f5-42e0-acbe-c7404bb4497f] HTTP status: 403

[OneAuth:Error:835v1:70049068-65f5-42e0-acbe-c7404bb4497f] (Code:2001) The resource is forbidden.
[OneAuth:Warning:96w1t:70049068-65f5-42e0-acbe-c7404bb4497f] Failed to get profile image from Graph2022-02-22T15:18:34.293Z composer:electron:one-auth 2 [OneAuth:Error:835v1:70049068-65f5-42e0-acbe-c7404bb4497f] (Code:2001) The resource is forbidden.

[OneAuth:Warning:96w1t:70049068-65f5-42e0-acbe-c7404bb4497f] Failed to get profile image from Graph
2022-02-22T15:18:34.295Z composer:electron:one-auth 3 [OneAuth:Warning:96w1t:70049068-65f5-42e0-acbe-c7404bb4497f] Failed to get profile image from Graph
2022-02-22T15:18:34.389Z composer:electron:one-auth There was an error trying to log the user into ARM: FetchError: request to https://management.azure.com/tenants?api-version=2020-01-01 failed, reason: self signed certificate in certificate chain
    at ClientRequest.<anonymous> (C:\Users\*****\AppData\Local\Programs\Bot Framework Composer\resources\app.asar\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  message: 'request to https://management.azure.com/tenants?api-version=2020-01-01 failed, reason: self signed certificate in certificate chain',
  type: 'system',
  errno: 'SELF_SIGNED_CERT_IN_CHAIN',
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
}
GET /api/auth/getTenants 500 9249.074 ms - 232
```

**Comment by dmvtech** [comment]
Hi @nickfrancis 

This appears to be an issue with the infrastructure between you and Azure. Specifically, there is a certificate being used somewhere along the way that is a _self-signed_ certificate.

> reason: self signed certificate in certificate chain

I'm not sure how to troubleshoot that, but I found this article which gives some simple steps to try (try hitting https://www.ssllabs.com/ssltest/analyze.html?d=management.azure.com and see if there are any certificate errors that show).

You may also want to clear the cache from Composer and restart and then try again (`Tools->Toggle Developer Tools->Application->Clear Storage`).

**Comment by ramfattah** [comment]
Hi @nickfrancis 

Similar issue open in composer. When attempting to login, after entering the email address, the password is not asked and automatically errors out. #8974 

If the suggestion given by @dmvtech did not work, could you please try to clear any Azure related credentials in your Windows OS? [Steps here](https://github.com/microsoft/BotFramework-Composer/issues/8974#issuecomment-1040668538)

also, have you checked Azure cli if you are in the correct subscription?
In Powershell, enter the following command: `az account list --output table` to show your current default subscription.

**Comment by nickfrancis** [comment]
Thank you both - was on leave last week - will run through the steps & update.

**Comment by nickfrancis** [comment]
So have cleared my cache on Bot Framework Composer & no joy.

Did look at the SSL labs & it seemed to run ok - interestingly there was one certificate that was showing as "In Trust Store - Self Signed" which I'm guessing is the trouble certificate.

Did a little bit more googling and wondering whether it's a tenant related security issue with regard to the certificate.

Am also in the process of installing bot composer on a separate machine & trying that to see if it's my machine that is the problem

**Comment by nickfrancis** [comment]
Tested on a different machine & it worked fine so it's a local issue - I'll do some work on my certificates to see if I can root it out & remove it.

**Comment by nickfrancis** [comment]
Resolved - it was Netskope running on local machine - need to find a work around within the company tenant....

**Comment by nickfrancis** [comment]
Yes - had to disable Netskope services on my machine before I could connect to Composer. Once disabled all works as it should.
