### ISSUE TITLE
CAN'T OPEN BOT FRAMEWORK COMPOSER V2.0

### ISSUE THREAD

**Issue by IcomeIleave** [microsoft/BotFramework-Composer#9111]
Hello! I'm working on a bot on Power Virtual Agents and can't open Bot Framework Composer.
OS :
windows 10
Screenshots:
![image](https://user-images.githubusercontent.com/44688750/162560475-6c06880b-a0d7-4d81-90b3-9e69449ca132.png)
debug log:

C:\Users\ctan83\AppData\Local\Programs\Bot Framework Composer>"Bot Framework Composer.exe"

C:\Users\ctan83\AppData\Local\Programs\Bot Framework Composer>
2022-04-09T06:36:29.772Z composer:electron:one-auth-shim Using OneAuth shim.
2022-04-09T06:36:29.772Z composer:electron:one-auth-shim To use genuine OneAuth library please read AUTH.md
2022-04-09T06:36:29.813Z composer:electron:env {
  ALLUSERSPROFILE: 'C:\\ProgramData',
  APPDATA: 'C:\\Users\\ctan83\\AppData\\Roaming',
  AUTH_TOKEN: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiY2h1bnppLnRhbkBkeGMuY29tIiwic3Bhbl9pZCI6IjQzODQ1NmY5LTk4YzAtNGYzZS1iNjY2LTgzNDlkM2Y4MWViMCIsImlhdCI6MTU5NjE4MTE3NH0.BznRWNGN79T1NZZYs9HOEs0R0NIEfmRqBw-xGIYtRlQ',
  ChocolateyInstall: 'C:\\ProgramData\\chocolatey',
  ChocolateyLastPathUpdate: '132357276273074679',
  CommonProgramFiles: 'C:\\Program Files\\Common Files',
  'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
  CommonProgramW6432: 'C:\\Program Files\\Common Files',
  COMPUTERNAME: 'CN-PF1B7DHL',
  ComSpec: 'C:\\WINDOWS\\system32\\cmd.exe',
  DEBUG: 'composer*',
  DriverData: 'C:\\Windows\\System32\\Drivers\\DriverData',
  FPS_BROWSER_APP_PROFILE_STRING: 'Internet Explorer',
  FPS_BROWSER_USER_PROFILE_STRING: 'Default',
  GDAL_DATA: 'C:\\Program Files\\PostgreSQL\\13\\gdal-data',
  HOMEDRIVE: 'C:',
  HOMEPATH: '\\Users\\ctan83',
  JAVA_HOME: 'C:\\Program Files\\Eclipse Adoptium\\jdk-11.0.13.8-hotspot',
  LOCALAPPDATA: 'C:\\Users\\ctan83\\AppData\\Local',
  LOGONSERVER: '\\\\CN-PF1B7DHL',
  MAVEN_HOME: 'C:\\apache-maven-3.6.3',
  NODE_ENV: 'development',
  NUMBER_OF_PROCESSORS: '8',
  NVTOOLSEXT_PATH: 'C:\\Program Files\\NVIDIA Corporation\\NvToolsExt\\',
  OneDrive: 'C:\\Users\\ctan83\\OneDrive - DXC Production',
  OneDriveCommercial: 'C:\\Users\\ctan83\\OneDrive - DXC Production',
  OS: 'Windows_NT',
  Path: 'C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\wbin;C:\\Program Files\\Eclipse Adoptium\\jdk-11.0.13.8-hotspot\\bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Amazon\\AWSCLIV2\\;C:\\Program Files\\TortoiseGit\\bin;C:\\apache-maven-3.6.3\\bin\\;C:\\Program Files\\EmEditor;C:\\ProgramData\\chocolatey\\bin;C:\\Users\\ctan83\\.dnx\\bin;C:\\Program Files\\Microsoft DNX\\Dnvm\\;C:\\Program Files\\Microsoft SQL Server\\120\\Tools\\Binn\\;C:\\Program Files\\dotnet\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\150\\DTS\\Binn\\;C:\\Program Files\\Azure Data Studio\\bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\nodejs\\;C:\\Program Files\\PowerShell\\7\\;C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\;C:\\Program Files (x86)\\Symantec\\VIP Access Client\\;C:\\Python\\Python39\\Scripts\\;C:\\Python\\Python39\\;C:\\Python\\Python310\\Scripts\\;C:\\Python\\Python310\\;C:\\Users\\ctan83\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\ctan83\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\ctan83\\.dotnet\\tools;C:\\Program Files\\Azure Data Studio\\bin;C:\\Program Files\\PostgreSQL\\13\\bin;C:\\Users\\ctan83\\AppData\\Roaming\\npm',
  PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
  POSTGIS_ENABLE_OUTDB_RASTERS: '1',
  POSTGIS_GDAL_ENABLED_DRIVERS: 'GTiff PNG JPEG GIF XYZ DTED USGSDEM AAIGrid',
  POWERSHELL_DISTRIBUTION_CHANNEL: 'MSI:Windows 10 Enterprise',
  PROCESSOR_ARCHITECTURE: 'AMD64',
  PROCESSOR_IDENTIFIER: 'AMD64 Family 23 Model 24 Stepping 1, AuthenticAMD',
  PROCESSOR_LEVEL: '23',
  PROCESSOR_REVISION: '1801',
  ProgramData: 'C:\\ProgramData',
  ProgramFiles: 'C:\\Program Files',
  'ProgramFiles(x86)': 'C:\\Program Files (x86)',
  ProgramW6432: 'C:\\Program Files',
  PROJ_LIB: 'C:\\Program Files\\PostgreSQL\\13\\share\\contrib\\postgis-3.1\\proj',
  PROMPT: '$P$G',
  PSModulePath: 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\windows\\system32\\WindowsPowerShell\\v1.0\\Modules;C:\\Program Files\\Microsoft Monitoring Agent\\Agent\\PowerShell\\;C:\\Program Files\\Microsoft Monitoring Agent\\Agent\\AzureAutomation\\7.3.1296.0',
  PUBLIC: 'C:\\Users\\Public',
  SESSIONNAME: 'Console',
  SOEDataPartition: 'D:',
  SOESystemPartitionLabel: 'W10E64SCCM',
  SystemDrive: 'C:',
  SystemRoot: 'C:\\WINDOWS',
  TEMP: 'C:\\Users\\ctan83\\AppData\\Local\\Temp',
  TMP: 'C:\\Users\\ctan83\\AppData\\Local\\Temp',
  USERDNSDOMAIN: 'ead.csc.com',
  USERDOMAIN: 'EAD',
  USERDOMAIN_ROAMINGPROFILE: 'EAD',
  USERNAME: 'ctan83',
  USERPROFILE: 'C:\\Users\\ctan83',
  VS140COMNTOOLS: 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\',
  windir: 'C:\\WINDOWS',
  WXDRIVE_START_ARGS: '--wxdrive-setting=0 --disable-gpu --disable-software-rasterizer --enable-features=NetworkServiceInProcess'
}
2022-04-09T06:36:29.813Z composer:electron production environment detected.
2022-04-09T06:36:29.823Z composer:electron Run completed
2022-04-09T06:36:29.873Z composer:electron App ready
2022-04-09T06:36:29.873Z composer:electron Loading latest known locale
2022-04-09T06:36:29.881Z composer:electron:electron-window Raw screen dimensions: 824 x 1536
2022-04-09T06:36:29.881Z composer:electron:electron-window Electron window dimensions: 741 x 988
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
2022-04-09T06:36:29.907Z composer:electron:electron-window Rendered Electron window dimensions:  [ 989, 743 ]
2022-04-09T06:36:31.149Z composer:electron Creating app data directory...
2022-04-09T06:36:31.150Z composer:electron creating composer app data path at:  C:\Users\ctan83\AppData\Roaming\BotFrameworkComposer
2022-04-09T06:36:31.151Z composer:electron creating local bot runtime publish path:  C:\Users\ctan83\AppData\Roaming\BotFrameworkComposer\hostedBots
2022-04-09T06:36:31.156Z composer:electron Created app data directory.
2022-04-09T06:36:31.156Z composer:electron Starting server...
2022-04-09T06:36:33.329Z composer App Settings: {
  botAdminEndpoint: 'http://localhost:3979',
  botEndpoint: 'http://localhost:3979',
  botsFolder: 'C:\\Users\\ctan83',
  runtimeFrameworkVersion: 'netcoreapp3.1',
  appDataPath: 'C:\\Users\\ctan83\\AppData\\Roaming\\BotFrameworkComposer\\data.json',
  platform: 'win32',
  diskNames: [ 'C:/' ],
  extensions: {
    manifestPath: 'C:\\Users\\ctan83\\AppData\\Roaming\\BotFrameworkComposer\\extensions.json',
    dataDir: 'C:\\Users\\ctan83\\AppData\\Roaming\\BotFrameworkComposer\\extension-data',
    builtinDir: 'C:/Users/ctan83/AppData/Local/Programs/Bot Framework Composer/resources/app.asar/extensions',
    remoteDir: 'C:\\Users\\ctan83\\AppData\\Roaming\\BotFrameworkComposer\\extensions',
    settingsPath: 'C:\\Users\\ctan83\\AppData\\Roaming\\BotFrameworkComposer\\extension-settings.json'
  }
}
2022-04-09T06:36:35.437Z composer:telemetry Setting up App Insights
2022-04-09T06:36:35.452Z composer:telemetry Starting Application Insights
2022-04-09T06:36:35.468Z composer:telemetry Started Application Insights
2022-04-09T06:36:35.775Z composer:electron-auth-provider Initialized.
2022-04-09T06:36:35.775Z composer:auth-service Initialized in Electron context.
2022-04-09T06:36:35.775Z composer:auth-service Production environment detected. Generating CSRF token.
Sat, 09 Apr 2022 06:36:35 GMT express-session deprecated undefined resave option; provide resave option at resources\app.asar\node_modules\@bfc\server\build\server.js:56:17
Sat, 09 Apr 2022 06:36:35 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at resources\app.asar\node_modules\@bfc\server\build\server.js:56:17
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
2022-04-09T06:36:35.918Z composer:extension-manager Loading extensions from C:/Users/ctan83/AppData/Local/Programs/Bot Framework Composer/resources/app.asar/extensions
2022-04-09T06:36:35.931Z composer:extension-manager Loading extensions from C:\Users\ctan83\AppData\Roaming\BotFrameworkComposer\extensions

Composer now running at:

http://localhost:5000

2022-04-09T06:36:35.953Z composer:electron Server started at port: 5000
2022-04-09T06:36:35.953Z composer:electron Rendering application...
(node:12164) UnhandledPromiseRejectionWarning: Error: ERR_CONNECTION_REFUSED (-102) loading 'http://localhost:3000/'
    at rejectAndCleanup (electron/js2c/browser_init.js:6039:21)
    at WebContents.failListener (electron/js2c/browser_init.js:6049:11)
    at WebContents.emit (events.js:210:5)
(node:12164) UnhandledPromiseRejectionWarning: Error: ERR_CONNECTION_REFUSED (-102) loading 'http://localhost:3000/'
    at rejectAndCleanup (electron/js2c/browser_init.js:6039:21)
    at WebContents.failListener (electron/js2c/browser_init.js:6049:11)
    at WebContents.emit (events.js:210:5)
(node:12164) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12164) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12164) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:12164) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by tonyanziano** [comment]
Hi @IcomeIleave ,

From the print out of your currently set environment variables in the log, I noticed: `NODE_ENV` is set to `development`. This is making Composer think that it is running in development mode instead of production mode.

When Composer runs in development mode, it tries to serve the client assets from `localhost:3000`, which will only be running if you are currently running the Web Pack development server, and not when running the packaged desktop application. Composer will also not use our authentication package, which is needed for the PVA integration.

Please make sure if you are setting this `NODE_ENV` variable globally, that you reset it when you try to run Composer so that it runs like it should in production mode.

**Comment by IcomeIleave** [comment]
hi @tonyanziano 
As you said，I reset  environment variable NODE_ENV then run composer successful!
Thank you for your help!
