### ISSUE TITLE
The Bot's not working after publishing to Azure.

### ISSUE THREAD

**Issue by SandeepBhagoji202** [microsoft/BotFramework-Composer#9129]
## Describe the bug

 I have a Bot developed using Bot framework composer and when I deploy this to Azure its not loading in the Webchat but I am able to load the bot locally in Emulator. The webchat issue says "There was an error sending this message to your bot: HTTP status code InternalServerError".

## Version

v2.1.2

## Browser

- [ ] Chrome
- [ ] Edge

## OS

- [ ] Windows

## To Reproduce

1. Go to Azure Portal. 
2. open the web app Bot and test in webchat.
3. Render the conversation

## Expected behavior

The Bot's supposed to work in the webchat and in connected channels. Ii doesn't seem to be working since yesterday when I published the Bot from composer. However, The Bot's working well and good in Emulator.

## Additional context

Here's the Exception I find in App service:

Exception Message:
System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions.

Description:
Application: SampleQnABot.exe
CoreCLR Version: 4.700.22.16002
.NET Core Version: 3.1.24
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.Listen(Int32 backlog)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at SampleQnABot.Program.Main(String[] args) in D:\SampleQnABot\SampleQnABot\Program.cs:line 14

Is it the Bot's unable to handle the Exceptions from Startup file . It was working perfect earlier. 

What exactly might have happened and what necessary steps to reproduce this issue.

Can you Please update.

**Comment by anishprasad01** [comment]
Hi @SandeepBhagoji202,

I need more information from you before I can begin to investigate.

- What have you implemented in your bot?
- Have you tried any troubleshooting steps yourself? If so, what have you tried?
- Does this issue occur if you attempt to publish a [sample bot](https://github.com/microsoft/BotBuilder-Samples/tree/main/composer-samples/csharp_dotnetcore/projects/EchoBot) to Azure?
- Have you tried to restart the App Service?
- Are all of your keys and secrets in your bot project correct?
- Can you provide reproduction steps?

I would hazard a guess from the 500 error that the issue is either in your config, or in your code.

**Comment by anishprasad01** [comment]
Closing this issue due to inactivity. If you still require assistance, please comment and we can reopen the issue.
