### ISSUE TITLE
Pull Request Validation is broken

### ISSUE THREAD

**Issue by BruceHaley** [microsoft/BotFramework-Composer#9194]
## Describe the bug

In [this PR](https://github.com/microsoft/BotFramework-Composer/pull/9193), Pull Request Validation / Conventional PR (pull_request) failed with the error "Error: Cannot find module 'whatwg-url'".

The affected action: https://github.com/microsoft/BotFramework-Composer/tree/main/.github/actions/conventional-pr

The full log:

Run ./.github/actions/conventional-pr
  with:
    repo-token: ***
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'whatwg-url'
Require stack:
- /home/runner/work/BotFramework-Composer/BotFramework-Composer/.github/actions/conventional-pr/node_modules/node-fetch/lib/index.js
- /home/runner/work/BotFramework-Composer/BotFramework-Composer/.github/actions/conventional-pr/node_modules/@octokit/request/dist-node/index.js
- /home/runner/work/BotFramework-Composer/BotFramework-Composer/.github/actions/conventional-pr/node_modules/@octokit/graphql/index.js
- /home/runner/work/BotFramework-Composer/BotFramework-Composer/.github/actions/conventional-pr/node_modules/@actions/github/lib/github.js
- /home/runner/work/BotFramework-Composer/BotFramework-Composer/.github/actions/conventional-pr/lib/conventional-pr.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:[2](https://github.com/microsoft/BotFramework-Composer/runs/6497277310?check_suite_focus=true#step:5:2)7)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/BotFramework-Composer/BotFramework-Composer/.github/actions/conventional-pr/node_modules/node-fetch/lib/index.js:10:[3](https://github.com/microsoft/BotFramework-Composer/runs/6497277310?check_suite_focus=true#step:5:3)3)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:1[4](https://github.com/microsoft/BotFramework-Composer/runs/6497277310?check_suite_focus=true#step:5:5))
    at Module.require (internal/modules/cjs/loader.js:88[7](https://github.com/microsoft/BotFramework-Composer/runs/6497277310?check_suite_focus=true#step:5:8):1[9](https://github.com/microsoft/BotFramework-Composer/runs/6497277310?check_suite_focus=true#step:5:10)) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/BotFramework-Composer/BotFramework-Composer/.github/actions/conventional-pr/node_modules/node-fetch/lib/index.js',
    '/home/runner/work/BotFramework-Composer/BotFramework-Composer/.github/actions/conventional-pr/node_modules/@octokit/request/dist-node/index.js',
    '/home/runner/work/BotFramework-Composer/BotFramework-Composer/.github/actions/conventional-pr/node_modules/@octokit/graphql/index.js',
    '/home/runner/work/BotFramework-Composer/BotFramework-Composer/.github/actions/conventional-pr/node_modules/@actions/github/lib/github.js',
    '/home/runner/work/BotFramework-Composer/BotFramework-Composer/.github/actions/conventional-pr/lib/conventional-pr.js'
  ]
}

**Comment by BruceHaley** [comment]
This issue is apparently specific only to the one PR. Abandoning the PR and closing this. Will revisit this if it recurs.
