### ISSUE TITLE
Parse Failed. Unexpected String

### ISSUE THREAD

**Issue by ganogs** [microsoft/BotFramework-Composer#9215]
Parse failed at Rakuten_FAQ_Bot.dialog: SyntaxError: Unexpected string in JSON at position 6893

**Comment by ganogs** [comment]
SyntaxError: Unexpected string in JSON at position 6893
    at JSON.parse (<anonymous>)
    at ConfigurationResourceExporer.loadType (/Users/ar-s.ganapathysubram/Rakuten_FAQ_Bot/Rakuten_FAQ_Bot/node_modules/botbuilder-dialogs-declarative/lib/resources/resourceExplorer.js:201:29)
    at new CoreBot (/Users/ar-s.ganapathysubram/Rakuten_FAQ_Bot/Rakuten_FAQ_Bot/node_modules/botbuilder-dialogs-adaptive-runtime/lib/coreBot.js:22:45)
    at /Users/ar-s.ganapathysubram/Rakuten_FAQ_Bot/Rakuten_FAQ_Bot/node_modules/botbuilder-dialogs-adaptive-runtime/lib/index.js:211:16
    at /Users/ar-s.ganapathysubram/Rakuten_FAQ_Bot/Rakuten_FAQ_Bot/node_modules/botbuilder-dialogs-adaptive-runtime-core/lib/serviceCollection.js:129:67
    at Array.reduce (<anonymous>)
    at /Users/ar-s.ganapathysubram/Rakuten_FAQ_Bot/Rakuten_FAQ_Bot/node_modules/botbuilder-dialogs-adaptive-runtime-core/lib/serviceCollection.js:129:40
    at Array.reduce (<anonymous>)
    at ServiceCollection.buildNodes (/Users/ar-s.ganapathysubram/Rakuten_FAQ_Bot/Rakuten_FAQ_Bot/node_modules/botbuilder-dialogs-adaptive-runtime-core/lib/serviceCollection.js:114:32)
    at ServiceCollection.makeInstances (/Users/ar-s.ganapathysubram/Rakuten_FAQ_Bot/Rakuten_FAQ_Bot/node_modules/botbuilder-dialogs-adaptive-runtime-core/lib/serviceCollection.js:171:21)

**Comment by anishprasad01** [comment]
Hi @ganogs,

In order to investigate this, I need you to provide a lot more information. 

- What platform are you on?
- What version of Composer?
- What language is this bot made in?
- How are you hosting the bot?
- How are you testing the bot?
- What is the bot doing in the dialog where this error occurs?
- Where is the offending JSON coming from?
- What objects does this JSON describe?
- Can you provide an example?

The error message suggests a syntax error in some JSON. Have you attempted to debug the bot and check the specified JSON for errors?

**Comment by anishprasad01** [comment]
Closing this issue due to inactivity. If you still require assistance, please comment and we can reopen the issue.
