### ISSUE TITLE
Published bot in Azure cannot access the QnA Maker Knowledge Bases

### ISSUE THREAD

**Issue by deetwo-id** [microsoft/BotFramework-Composer#9349]
## Describe the bug

I am working with the bot framework Composer and I currently want to add the QnA Maker service. Locally in Composer I can access the added knowledge base, however when I test the bot in Azure an error message appears.

The error message indicates the following: `Response status code does not indicate success: 400 (Bad Request).`

## Version

Version:  2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [X] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Build a bot using the Bot framework Composer and a "Core Bot with Language" template
2. Set the bot to german language
3. Add the QnA Maker to the bot and add a Knowledge Base
4. Publish the bot to Azure from the Bot Framework Composer
5. Try to trigger the QnA Maker via the "Test in Webchat" Page in Azure

## Expected behavior

- The bot should answer with a message defined in the triggered QnA Knowledge Base

## Screenshots

![MicrosoftTeams-image](https://user-images.githubusercontent.com/39704877/184844480-14d9c2b8-0c84-47c8-8940-f322ea1e5ffc.png)

![image](https://user-images.githubusercontent.com/39704877/184844589-0968480f-98bd-4c8f-8d48-a7695f976df5.png)

![Screenshot 2022-08-16 112111](https://user-images.githubusercontent.com/39704877/184845044-5abd0e2c-e5dd-4cd0-8ed0-22dbe14f91d2.png)

![image](https://user-images.githubusercontent.com/39704877/184845222-febda18e-f03e-4908-a1a3-77b893e911b6.png)

![image](https://user-images.githubusercontent.com/39704877/184845346-acb78d92-14f9-419e-a4e6-6b4fa6db6141.png)

## Additional ressources

`System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.Bot.Builder.AI.QnA.HttpRequestUtils.ExecuteHttpRequestAsync(String requestUrl, String payloadBody, QnAMakerEndpoint endpoint)
   at Microsoft.Bot.Builder.AI.QnA.GenerateAnswerUtils.QueryQnaServiceAsync(Activity messageActivity, QnAMakerOptions options)
   at Microsoft.Bot.Builder.AI.QnA.GenerateAnswerUtils.GetAnswersRawAsync(ITurnContext turnContext, IMessageActivity messageActivity, QnAMakerOptions options)
   at Microsoft.Bot.Builder.AI.QnA.QnAMaker.GetAnswersRawAsync(ITurnContext turnContext, QnAMakerOptions options, Dictionary`2 telemetryProperties, Dictionary`2 telemetryMetrics)
   at Microsoft.Bot.Builder.AI.QnA.Dialogs.QnAMakerDialog.OnPreBubbleEventAsync(DialogContext dc, DialogEvent e, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Dialog.OnDialogEventAsync(DialogContext dc, DialogEvent e, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.EmitEventAsync(String name, Object value, Boolean bubble, Boolean fromLeaf, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogExtensions.InternalRunAsync(ITurnContext turnContext, String dialogId, DialogContext dialogContext, DialogStateManagerConfiguration stateConfiguration, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.DialogExtensions.RunAsync(Dialog dialog, ITurnContext turnContext, IStatePropertyAccessor`1 accessor, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Dialogs.Adaptive.AdaptiveDialogBot.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.SetSpeakMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.TelemetryLoggerMiddleware.OnTurnAsync(ITurnContext context, NextDelegate nextTurn, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.TelemetryInitializerMiddleware.OnTurnAsync(ITurnContext context, NextDelegate nextTurn, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)`

**Comment by ramfattah** [comment]
Hi @deetwo-id, I'm investigating this issue.

**Comment by ramfattah** [comment]
Hi @deetwo-id, thanks for reaching out to us and reporting this issue.

I was not able to reproduce. After publishing to Azure, the bot was able to receive answers from QnA.

Environment:
* Composer 2.1.2
* Template: `Core Bot with Language` version 1.4.1 
* Language: C#

Tested in Webchat after publish:
![image](https://user-images.githubusercontent.com/38049078/185542951-04d87a12-dc4d-4483-97cc-f3c4e4a4326d.png)

Sharing the steps I took:
1. Created a fresh Composer "Core Bot with Language" template
2. Created a QnA Maker knowledge base, followed this doc [here](https://docs.microsoft.com/en-us/composer/how-to-create-qna-kb?tabs=v2x#:~:text=Create%20a%20QnA%20Maker%20knowledge%20base,-Article)
3. Added a knowledge base from the [Knowledge base page](https://docs.microsoft.com/en-us/composer/how-to-create-qna-kb?tabs=v2x#add-knowledge-base-from-the-knowledge-qna-page) in Composer
4. Added German `de-de` multilingual support, docs [here](https://docs.microsoft.com/en-us/composer/how-to-use-multiple-language?tabs=v2x)
5. Published to Azure


#

@deetwo-id, Let me know if you'd like me to try additional steps to attempt to reproduce the issue. 
Thanks.

**Comment by ramfattah** [comment]
Hi @deetwo-id, thanks for reaching out.

I was not able to reproduce this issue. After publishing the bot to Azure, I was able to receive the answers from QnA.

Environment:
* Composer 2.1.2
* Template: `Core Bot with Language` version 1.4.1 
* Language: C#

Tested in Webchat after publish:
![image](https://user-images.githubusercontent.com/38049078/185542951-04d87a12-dc4d-4483-97cc-f3c4e4a4326d.png)

Sharing the steps I took:
1. Created a fresh Composer "Core Bot with Language" template
2. Created a QnA Maker knowledge base, followed this doc [here](https://docs.microsoft.com/en-us/composer/how-to-create-qna-kb?tabs=v2x#:~:text=Create%20a%20QnA%20Maker%20knowledge%20base,-Article)
3. Added a knowledge base from the [Knowledge base page](https://docs.microsoft.com/en-us/composer/how-to-create-qna-kb?tabs=v2x#add-knowledge-base-from-the-knowledge-qna-page) in Composer
4. Added German `de-de` multilingual support, docs [here](https://docs.microsoft.com/en-us/composer/how-to-use-multiple-language?tabs=v2x)
5. Published to Azure


#

@deetwo-id, Let me know if you'd like me to try additional steps to attempt to reproduce the issue. 
Thanks.

**Comment by ramfattah** [comment]
Closing due to inactivity. @deetwo-id, please re-open if needed.

**Comment by Butcheva** [comment]
having the same issue
