### ISSUE TITLE
Node Core Bot With Language failed to deploy to Linux

### ISSUE THREAD

**Issue by BruceHaley** [microsoft/BotFramework-Composer#9384]
## Describe the bug

My bot made from Node template "Core Bot With Language" deployed OK to Azure Windows, but errored deploying to Azure Linux.

## To Reproduce

Using Composer 2.1.2 in Windows, I created a bot using the Node template "Core Bot With Language".

I chose a LUIS region of West US.

Creating a publishing profile, I chose:
- App Service: Linux
- Resource region: West US 2
- LUIS region: West Europe

Publishing with that profile, the process ran for more than an hour, then errored with:

```
"{"name":"DEPLOY_ZIP_ERROR","message":"There was a problem publishing bot assets (zip deploy). "Getting status of zip upload processing failed. {"stack":"Error: Request failed with status code 403
    at createError (C:\Program Files\Bot Framework Composer\resources\app.asar.unpacked\extensions\azurePublish\dist\extension.js:105969:17)
    at settle (C:\Program Files\Bot Framework Composer\resources\app.asar.unpacked\extensions\azurePublish\dist\extension.js:105983:14)
    at IncomingMessage.handleStreamEnd (C:\Program Files\Bot Framework Composer\resources\app.asar.unpacked\extensions\azurePublish\dist\extension.js:106970:13)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)","message":"Request failed with status code 403","config":{}}"","stack":"Error
    at new CustomizeError (C:\Program Files\Bot Framework Composer\resources\app.asar.unpacked\extensions\azurePublish\dist\extension.js:276830:25)
    at createCustomizeError (C:\Program Files\Bot Framework Composer\resources\app.asar.unpacked\extensions\azurePublish\dist\extension.js:276835:10)
    at BotProjectDeploy.deployZip (C:\Program Files\Bot Framework Composer\resources\app.asar.unpacked\extensions\azurePublish\dist\extension.js:277366:13)"}"

```
Publishing with this profile got the same error:
- App Service: Linux
- Resource region: West US
- LUIS region: West US

Publishing with this profile succeeded:
- App Service: Windows
- Resource region: West US
- LUIS region: West US

## Suggested fix:

The guys here say that Composer deploys to Linux for all types of bots are broken, not just this one.

If the fix for this is not too difficult and is low risk, we suggest fixing it. Otherwise, the Composer Linux deploy option ought to be disabled.

**Comment by dmvtech** [comment]
Linking other issues:

https://github.com/microsoft/BotFramework-Composer/issues/8890
https://github.com/microsoft/BotFramework-Composer/issues/9360
