### ISSUE TITLE
SyntaxError - Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by twalker45106** [microsoft/BotFramework-Composer#9397]
## Describe the bug
I'm using the Bot Framework Composer to create a bot. The bot works without issues on my local computer, and I was able to eventually get the bot to Azure after a bunch of tries initially. It then had some issues, so I tried deleting the publishing profile and re-create it. I've deleted and re-created resources multiple times, which there are no issues with creating the publishing profile. When I click the "Publish selected  bots" button, I get the following error:

```txt
{message: "SyntaxError - Unexpected token u in JSON at position 0",…}
message: "SyntaxError - Unexpected token u in JSON at position 0"
log: "---↵"Accepted for publishing..."↵---↵↵---↵"Abs settings incomplete, skip linking bot with webapp ..."↵---↵↵---↵"appPasswordHint incomplete, return ..."↵---↵↵---↵"Building the bot app..."↵---↵↵---↵"Build succeeded!"↵---↵↵---↵"start publish luis"↵---↵↵---↵"{\"stack\":\"Error: Request failed with status code 401\\n    at createError (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:105969:17)\\n    at settle (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:105983:14)\\n    at IncomingMessage.handleStreamEnd (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:106970:13)\\n    at IncomingMessage.emit (events.js:215:7)\\n    at endReadableNT (_stream_readable.js:1183:12)\\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\",\"message\":\"Request failed with status code 401\",\"config\":{}}"↵---↵↵---↵"{\"stack\":\"SyntaxError: Unexpected token u in JSON at position 0\\n    at JSON.parse (<anonymous>)\\n    at publishLuisToPrediction (C:\\\\Program Files\\\\Bot Framework Composer\\\\resources\\\\app.asar.unpacked\\\\extensions\\\\azurePublish\\\\dist\\\\extension.js:276545:28)\",\"message\":\"Unexpected token u in JSON at position 0\"}"↵---↵↵---↵"SyntaxError - Unexpected token u in JSON at position 0"↵---↵"
comment: ""
time: "Wed Oct 05 2022 00:25:21 GMT-0400 (Eastern Daylight Time)"
id: "b47f751e-44b8-432d-a69d-59c4a0c1404e"
status: 500
```

See above

## Version
Release: 2.1.2
SDK runtime packages: 4.12.0

Not sure where to find that

## Browser

- [ ] Electron distribution
- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

See above

## Expected behavior
Should be able to successfully publish to Azure without errors.

## Additional context

![image](https://user-images.githubusercontent.com/47398704/193981748-c2c7f67d-a3ef-4c10-b805-87fa41df0be3.png)

**Comment by anishprasad01** [comment]
Hi @twalker45106,

A cursory glance at the error trace you posted reveals both a 401 error and that this error appears to be occurring when Composer tries to publish the LUIS resource. Have you checked and verified that all of the IDs and keys in your bot settings are correct?

When you deleted the publish profile and created a new one, did you also go into the Azure Portal and delete all of the resources created by that old profile?

**Comment by anishprasad01** [comment]
Closing this issue due to inactivity. If you still require assistance, please comment and we can reopen the issue.
