### ISSUE TITLE
Can't host Composer on Virtual Machine

### ISSUE THREAD

**Issue by pong-ekarin** [microsoft/BotFramework-Composer#9560]
## Describe the bug

Can't host Composer on Azure Virtual Machine - Linux (Ubuntu 20.04).
Tried 2 methods.
1. Followed instruction on https://learn.microsoft.com/en-us/composer/how-to-host-composer of using yarn.
2. Used docker build.

## Version

Composer 2.1.2

## Browser

SSH

## OS

Ubuntu 20.04

## To Reproduce

1. Create Azure VM.
2. Set Networking inbound port rule to allow SSH.
3. Connect via SSH

------- Using Yarn -------
4. sudo apt update && sudo apt upgrade
5. sudo apt install curl
6. curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
7. sudo apt-get install -y nodejs
8. sudo npm install -g yarn
9. wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && sudo dpkg -i packages-microsoft-prod.deb
10. sudo apt-get update; sudo apt-get install -y apt-transport-https && sudo apt-get update && sudo apt-get install -y dotnet-sdk-3.1
11. git clone https://github.com/microsoft/BotFramework-Composer.git BotFramework-Composer
12. cd BotFramework-Composer
/* This step is performed to fix browserlist warning.*/
13. nano .yarnrc.yml
	- lockfileFilename: yarn-berry.lock -> lockfileFilename: yarn.lock
14. nano .yarnrc.prod.yml
	- lockfileFilename: "yarn-berry.lock" -> lockfileFilename: "yarn.lock"
15. cd Composer
16. mv yarn-berry.lock yarn.lock
17. npx browserslist@latest --update-db
18. yarn up -R caniuse-lite
19. mv yarn.lock yarn-berry.lock
20. cd ..
21. nano .yarnrc.yml
	- lockfileFilename: yarn.lock -> lockfileFilename: yarn-berry.lock
22. nano .yarnrc.prod.yml
	- lockfileFilename: "yarn.lock" -> lockfileFilename: "yarn-berry.lock"
/* End of fix browserlist warning.*/
23. cd Composer
24. yarn install
25. yarn build
/* This step is performed to fix Cannot find module in BotFramework-Composer/Composer/packages/server/build/init.js if run yarn start now.*/
26. cd packages/server
27. yarn build
28. cd /home/fkmgrhpowejih/BotFramework-Composer/Composer
/* End of fix Cannot find module in BotFramework-Composer/Composer/packages/server/build/init.js if run yarn start now.*/
26. yarn start
27. Error here
Error occurred while starting server:  Error: Cannot find module '/home/fkmgrhpowejih/BotFramework-Composer/Composer/node_modules/@bfc/client/build/public/index.ejs'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:349:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:562:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:917:27)
    at Function.resolve (internal/modules/cjs/helpers.js:113:19)
    at Object.<anonymous> (/home/fkmgrhpowejih/BotFramework-Composer/Composer/packages/server/build/server.js:50:64)
    at Generator.next (<anonymous>)
    at /home/fkmgrhpowejih/BotFramework-Composer/Composer/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/fkmgrhpowejih/BotFramework-Composer/Composer/node_modules/tslib/tslib.js:114:16)
    at Object.start (/home/fkmgrhpowejih/BotFramework-Composer/Composer/packages/server/build/server.js:44:20) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/fkmgrhpowejih/BotFramework-Composer/Composer/node_modules/@bfc/client/package.json',
  requestPath: '@bfc/client'
}

------- Using Docker -------
4. sudo apt install docker.io
5. sudo docker build /home/fkmgrhpowejih/BotFramework-Composer
6. Error here
[webRoute] yarn install
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 1s 122ms
➤ YN0000: Done in 1s 301ms
[webRoute] compiling
[webRoute] cleaning dist
Restoring /src/extensions/package.json and /src/extensions/yarn-berry.lock
Successfully restored.
fatal: not a git repository (or any of the parent directories): .git
Creating an optimized production build. This may take a few minutes..
[esbuild-loader] ESBuildPlugin is no longer required for usage and will be removed in the next major release. Please refer to the docs and release notes for more info.
The command '/bin/sh -c yarn build:prod $YARN_ARGS' returned a non-zero code: 1

## Expected behavior

Successfully start Composer and can access with localhost:3000 and http://<IP ADDRESS OF VM>:3000.

## Additional context

I'm new to web development, npm, yarn and docker. So mistakes on my part could be very obvious. Thank you for your help!

**Comment by pong-ekarin** [comment]
Apparently my allocated RAM is not enough, causing failure.
