### ISSUE TITLE
Unable to publish Node Azure Bot from Bot Framework Composer

### ISSUE THREAD

**Issue by pckyn** [microsoft/BotFramework-Composer#9583]
Hi Team,

We have created a Node Azure bot and unable to publish in azure.. Please help on this.

"{\"name\":\"DEPLOY_ZIP_ERROR\",\"message\":\"There was a problem publishing bot assets (zip deploy). {\\\"stack\\\":\\\"Error: write EPIPE\\\\n    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:16)[\\\",\\\"message\\\":\\\"write](https://github.com/%22,/%22message/%22:/%22write) EPIPE\\\",\\\"code\\\":\\\"EPIPE\\\",\\\"config\\\":{}}\",\"stack\":\"Error[\\n](https://github.com/n)    at new CustomizeError (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/dist/extension.js:276418:25)[\\n](https://github.com/n)    at createCustomizeError (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/dist/extension.js:276423:10)\\n    at BotProjectDeploy.deployZip (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/dist/extension.js:276954:13)\"}"
---
 
---
"DEPLOY_ZIP_ERROR - There was a problem publishing bot assets (zip deploy). {\"stack\":\"Error: write EPIPE\\n    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:16)\",\"message\":\"write EPIPE\",\"code\":\"EPIPE\",\"config\":{}}"

![image](https://github.com/microsoft/BotFramework-Services/assets/126873481/91f9f4c3-9113-433d-bc0d-cca9ab031feb)

![image](https://github.com/microsoft/BotFramework-Services/assets/126873481/5e7afd9e-be42-4164-a972-8842437d03a9)

Thanks,
Prashant

**Comment by ramfattah** [comment]
Related #9577

**Comment by ramfattah** [comment]
Hi @pckyn,

This issue has been resolved after installing and using the latest Composer Nightly build:
https://github.com/microsoft/BotFramework-Composer-Nightlies/releases 

 

Could you please install Composer [nightly build c72cfea](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v2.1.2-nightly.352230.c72cfea) or new version to see if it addresses this issue?

 

Note, the initial publishing attempt failed as the resources were not fully ready after provisioning. Then after trying again, the second attempt of deployment was successful.
![image](https://github.com/microsoft/BotFramework-Composer/assets/38049078/decc0bf7-694c-400c-8bf4-f80759e52585)

**Comment by pckyn** [comment]
Hi @ramfattah - I am unable to open the bot composer app, downloaded from nightlies in mac. 
However, I am able to open the bot composer app in my mac by downloading the BotFramework-Composer-2.1.2-mac. Please have a look.

**Comment by ramfattah** [comment]
Hi @pckyn, 

A workaround for now is to clone [BotFramework-Composer](https://github.com/microsoft/BotFramework-Composer) project repository and Build Composer Locally.

Build and run the Composer project locally from main branch as a web application, clone the source code from Github and build the application using the following [instructions](https://github.com/Microsoft/BotFramework-Composer#build-composer-locally) to your local machine. Then please attempt to publish the bot again.

**Comment by pckyn** [comment]
Hi @ramfattah - Tried to follow the steps..but it's throwing errors...please suggest if missing anything..

![image](https://github.com/microsoft/BotFramework-Composer/assets/126873481/b261116e-0202-4f84-9be6-95217d0a9f35)

**Comment by ramfattah** [comment]
Hi @pckyn, 

What Node version are you using? 
Could you please try with Node version 14?

**Comment by ramfattah** [comment]
Hi @pckyn, closing this due to inactivity.
