### ISSUE TITLE
Unable to publish bot with error of 404 (it can't find something?)

### ISSUE THREAD

**Issue by pra-navi** [microsoft/BotFramework-Composer#9763]
## Describe the bug
I am trying to deploy my bot using 'Import Resources'.

When JSON of existing resources is:
{
  "name": "abc",
  "environment": "dev",
  "tenantId": "abc",
  "hostname": "abc",
  "runtimeIdentifier": "win-x64",
  "resourceGroup": "abc",
  "botName": "abc",
  "subscriptionId": "abc",
  "region": "westeurope",
  "appServiceOperatingSystem": "linux",
  "scmHostDomain": "azurewebsites.net",
  "luisResource": "",
  "settings": {
    "applicationInsights": {
      "InstrumentationKey": "",
      "connectionString": ""
    },
    "cosmosDb": {
      "cosmosDBEndpoint": "",
      "authKey": "",
      "databaseId": "",
      "containerId": ""
    },
    "blobStorage": {
      "connectionString": "",
      "container": ""
    },
    "luis": {
      "authoringKey": "",
      "authoringEndpoint": "",
      "endpointKey": "",
      "endpoint": "",
      "region": ""
    },
    "qna": {
      "subscriptionKey": "",
      "endpoint": ""
    },
    "MicrosoftAppId": "abc",
    "MicrosoftAppPassword": "abc"
  }
}

I get the following error message:
![image](https://github.com/user-attachments/assets/f485b8b7-391b-472e-9c8f-0cb76bececb8)
![image](https://github.com/user-attachments/assets/e4763539-f3c8-4105-b37f-c8c649e2d71c)

If i change scmHostDomain to 'scm.azurewebsites.net' or ''
then the error changes to:
![image](https://github.com/user-attachments/assets/df9ce701-b314-4c10-815c-cba66f5c8060)

## Version

I am using v2.1.2. I did not code this I am just using the interface.

## Browser

- [ ] Electron distribution
- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## Expected behavior

I just needed it to publish the bot, I have pressed publish and it gives me this error message

## Screenshots

Given above

## Additional context

I am using Windows but I have set up the Microsoft Azure to use linux. I have also set up Microsoft Azure to be nodejs because when i first created this bot on botframework composer i had two options of nodejs or .NET and i chose nodejs.

**Comment by pra-navi** [comment]
i have tried both a windows app service and a linux app service as the hostname and the messaging endpoint of the azure bot and i get the same problem

**Comment by stevkan** [comment]
@pra-navi - I'll be taking a look at this and will let you know what I find. I probably won't have a response until next week, fyi. However, here are a few things you can try:

- Comparing your manifest to a generated one I have in a project of my own, everything looks to be the same with the exception of the `scmHostDomain` property value in which mine has an empty string. Can you try removing that value and trying again?
    - I suspect this to be the issue since the error message your posted above shows `ENOTFOUND` with a URL that includes the value you included.
- Check the `WEBSITE_NODE_DEFAULT_VERSION` environment variable exists in the service app and that it is set to v14.x (e.g., v14.17.0).
- Try the Composer 'nightly' version, available [here](https://github.com/microsoft/BotFramework-Composer-Nightlies/releases/tag/v2.1.3-nightly.364675.1a93f21). This version includes some updates that have yet to be published in an official release, including some in the Azure publish process and an expired certificate error related to downloading certain packages thru the Package Manager.
    - I'm not convinced this is a bonified Composer error as much as it is a configuration error, but it wouldn't hurt to try it out. Simply uninstall the current version and download and install the nightly version. This won't affect the bot your built. If you want to revert, just uninstall the nightly and reinstall the latest release, again.

Let me know if any of these unblock you.

**Comment by pra-navi** [comment]
Also I have exported my project from the Bot Framework Composer and published it to github so that I can deploy it on my Microsoft Web App > Deployment > Deployment Center through github actions. So now while I can open up the feature 'Test in Web Chat', none of my messages are prompting a response from my bot. So essentially the logic that worked within the Bot Framework composer is no longer working now.

2024-08-02T06:55:11.3463689Z [onTurnError] unhandled error DialogContextError: user.data is not a list or array.
2024-08-02T06:55:11.3464506Z     at /home/site/wwwroot/node_modules/botbuilder-dialogs/lib/dialogContext.js:40:19
2024-08-02T06:55:11.3464567Z     at Generator.throw (<anonymous>)
2024-08-02T06:55:11.3464895Z     at rejected (/home/site/wwwroot/node_modules/botbuilder-dialogs/lib/dialogContext.js:6:65)
2024-08-02T06:55:11.3464934Z     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
2024-08-02T06:55:11.3464967Z   error: 'user.data is not a list or array.',
2024-08-02T06:55:11.3465004Z   dialogContext: {
2024-08-02T06:55:11.3465037Z     activeDialog: 'SetProperty[=`user.data`]2',
2024-08-02T06:55:11.3465097Z     parent: 'BotName',
2024-08-02T06:55:11.3465129Z     stack: [ [Object], [Object], [Object] ]
2024-08-02T06:55:11.3465156Z   }
2024-08-02T06:55:11.3465205Z }

when i check the logs on my Web App portal > Log Stream, i get the above everytime I try to send a message. Not sure what is causing the error considering I am using the same files that work within the Bot Framework Composer.

**Comment by pra-navi** [comment]
@stevkan 
For context, 

            {
              "$kind": "Microsoft.SetProperty",
              "$designer": {
                "id": "zVb1j6"
              },
              "property": "user.data",
              "value": [
                {
                  "role": "user",
                  "message": "${turn.activity.text}"
                }
              ]
            }
            
            this is my first action regarding user.data in my BotName.dialog file

**Comment by pra-navi** [comment]
@stevkan

When I restart the chat, it is supposed to send an Activity Greeting:

server listening on port 8080
2024-08-02T07:28:03.2280750Z Terminated
2024-08-02T07:28:08.6482331Z [onTurnError] unhandled error DialogContextError: The clientSecret parameter is required.
2024-08-02T07:28:08.6483143Z     at /home/site/wwwroot/node_modules/botbuilder-dialogs/lib/dialogContext.js:40:19
2024-08-02T07:28:08.6483273Z     at Generator.throw (<anonymous>)
2024-08-02T07:28:08.6483321Z     at rejected (/home/site/wwwroot/node_modules/botbuilder-dialogs/lib/dialogContext.js:6:65)
2024-08-02T07:28:08.6483363Z     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
2024-08-02T07:28:08.6483401Z   error: Error: The clientSecret parameter is required.
2024-08-02T07:28:08.6483438Z       at Object.validateStringParameter (/home/site/wwwroot/node_modules/adal-node/lib/argument.js:37:13)
2024-08-02T07:28:08.6483477Z       at AuthenticationContext.acquireTokenWithClientCredentials (/home/site/wwwroot/node_modules/adal-node/lib/authentication-context.js:282:14)
2024-08-02T07:28:08.6483511Z       at /home/site/wwwroot/node_modules/botframework-connector/lib/auth/microsoftAppCredentials.js:49:48
2024-08-02T07:28:08.6483566Z       at new Promise (<anonymous>)
2024-08-02T07:28:08.6483600Z       at MicrosoftAppCredentials.<anonymous> (/home/site/wwwroot/node_modules/botframework-connector/lib/auth/microsoftAppCredentials.js:48:40)
2024-08-02T07:28:08.6483628Z       at Generator.next (<anonymous>)
2024-08-02T07:28:08.6483659Z       at /home/site/wwwroot/node_modules/botframework-connector/lib/auth/microsoftAppCredentials.js:15:71
2024-08-02T07:28:08.6483687Z       at new Promise (<anonymous>)
2024-08-02T07:28:08.6483719Z       at __awaiter (/home/site/wwwroot/node_modules/botframework-connector/lib/auth/microsoftAppCredentials.js:11:12)
2024-08-02T07:28:08.6483752Z       at MicrosoftAppCredentials.refreshToken (/home/site/wwwroot/node_modules/botframework-connector/lib/auth/microsoftAppCredentials.js:46:16),
2024-08-02T07:28:08.6483785Z   dialogContext: {
2024-08-02T07:28:08.6483831Z     activeDialog: 'SendActivity[${SendActivity_Greeting()}]',
2024-08-02T07:28:08.6483861Z     parent: 'TestHaleriumBot',
2024-08-02T07:28:08.6483892Z     stack: [ [Object], [Object], [Object], [Object] ]
2024-08-02T07:28:08.6483920Z   }
2024-08-02T07:28:08.6483949Z }

**Comment by pra-navi** [comment]
what is the expected output that i should see on Log Stream (on verbose mode on Azure Web App portal) after 1) starting the web chat, 2) sending my first message

**Comment by pra-navi** [comment]
@stevkan

not sure what I changed (i only added and then removed npm install from the configurations on azure portal)

but now for every restart it creates, starts and stops a container then it just records no trace no matter what message i send (still no response from bot and not sure how to debug to find out what the bot is reading and if it is even calling the api that i have connected to it in the bot framework composer)

2024-08-02T12:50:25  Welcome, you are now connected to log-streaming service.Starting Log Tail -n 10 of existing logs ----/home/LogFiles/kudu/trace/appnamebo_kudu_0fe155a77e-6701f2b9-7095-4b82-b808-2123beb01e34.txt  (https://appname.scm.germanywestcentral-01.azurewebsites.net/api/vfs/LogFiles/kudu/trace/appnamebo_kudu_0fe155a77e-6701f2b9-7095-4b82-b808-2123beb01e34.txt)
2024-08-01T08:37:01  Startup Request, url: /api/deployments/?api-version=2022-03-01, method: GET, type: request, pid: 80,1,17, ScmType: None/home/LogFiles/kudu/trace/appnamebo_kudu_280dd5d8c1-ff6afa2e-d69a-462d-9680-365eabaa8c31.txt  (https://appname.scm.germanywestcentral-01.azurewebsites.net/api/vfs/LogFiles/kudu/trace/appnamebo_kudu_280dd5d8c1-ff6afa2e-d69a-462d-9680-365eabaa8c31.txt)
2024-08-01T08:37:54  Startup Request, url: /api/settings, method: GET, type: request, pid: 80,1,7, ScmType: GitHubAction/home/LogFiles/kudu/trace/appnamebo_kudu_3e67927eef-53d282df-005e-41d2-b8d4-c262071943ce.txt  (https://appname.scm.germanywestcentral-01.azurewebsites.net/api/vfs/LogFiles/kudu/trace/haleriumbo_kudu_3e67927eef-53d282df-005e-41d2-b8d4-c262071943ce.txt)
2024-08-02T11:47:53  Startup Request, url: /api/deployments/?api-version=2022-03-01, method: GET, type: request, pid: 80,1,7, ScmType: GitHubAction/home/LogFiles/kudu/trace/appnamebo_kudu_7a2a67fba8-0c427add-2f0c-4d42-b418-310451666747.txt  (https://appname.scm.germanywestcentral-01.azurewebsites.net/api/vfs/LogFiles/kudu/trace/appnamebo_kudu_7a2a67fba8-0c427add-2f0c-4d42-b418-310451666747.txt)
2024-08-02T12:20:29  Startup Request, url: /api/deployments/?api-version=2022-03-01, method: GET, type: request, pid: 80,1,7, ScmType: GitHubAction/home/LogFiles/kudu/trace/appnamebo_kudu_b5226cc9a8-ac61fee3-1b89-412a-a9b3-2c77d8c3f30e.txt  (https://appname.scm.germanywestcentral-01.azurewebsites.net/api/vfs/LogFiles/kudu/trace/appnamebo_kudu_b5226cc9a8-ac61fee3-1b89-412a-a9b3-2c77d8c3f30e.txt)
2024-08-01T13:16:02  Startup Request, url: /api/deployments/?api-version=2022-03-01, method: GET, type: request, pid: 85,1,5, ScmType: GitHubAction/home/LogFiles/kudu/trace/appnamebo_kudu_c4cdb4e553-be9a5814-2d87-46ae-b277-754118b1be04.txt  (https://appname.scm.germanywestcentral-01.azurewebsites.net/api/vfs/LogFiles/kudu/trace/appnamebo_kudu_c4cdb4e553-be9a5814-2d87-46ae-b277-754118b1be04.txt)
2024-08-02T07:33:43  Startup Request, url: /api/deployments/?api-version=2022-03-01, method: GET, type: request, pid: 85,1,5, ScmType: GitHubAction/home/LogFiles/kudu/trace/appnamebo_kudu_c698a59f09-aee58239-3923-4c83-981a-149f6017a8c4.txt  (https://appname.scm.germanywestcentral-01.azurewebsites.net/api/vfs/LogFiles/kudu/trace/haleriumbo_kudu_c698a59f09-aee58239-3923-4c83-981a-149f6017a8c4.txt)
2024-07-30T13:42:49  Startup Request, url: /api/deployments/?$orderby=ReceivedTime%20desc&$top=20&api-version=2022-03-01, method: GET, type: request, pid: 87,1,14, ScmType: None/home/LogFiles/kudu/trace/appnamebo_kudu_d578820763-dbc130c8-ebb3-400b-b9e1-3f196b7b4587.txt  (https://appname.scm.germanywestcentral-01.azurewebsites.net/api/vfs/LogFiles/kudu/trace/appnamebo_kudu_d578820763-dbc130c8-ebb3-400b-b9e1-3f196b7b4587.txt)
2024-08-02T11:42:58  Startup Request, url: /api/deployments/?api-version=2022-03-01, method: GET, type: request, pid: 85,1,86, ScmType: GitHubAction/home/LogFiles/kudu/trace/appnamebo_kudu_d6b32a20fa-b44338c9-273d-40fc-9c75-d3a4ab7fd75c.txt  (https://appname.scm.germanywestcentral-01.azurewebsites.net/api/vfs/LogFiles/kudu/trace/appnamebo_kudu_d6b32a20fa-b44338c9-273d-40fc-9c75-d3a4ab7fd75c.txt)
2024-08-02T07:44:05  Startup Request, url: /api/deployments/?api-version=2022-03-01, method: GET, type: request, pid: 80,1,14, ScmType: GitHubAction/home/LogFiles/kudu/trace/appnamebo_kudu_e6a6052c5d-65cfe703-ff05-4763-9e08-2e32fe0e167c.txt  (https://appname.scm.germanywestcentral-01.azurewebsites.net/api/vfs/LogFiles/kudu/trace/appnamebo_kudu_e6a6052c5d-65cfe703-ff05-4763-9e08-2e32fe0e167c.txt)
2024-08-01T18:59:44  Startup Request, url: /api/deployments/?api-version=2022-03-01, method: GET, type: request, pid: 79,1,14, ScmType: GitHubAction/home/LogFiles/kudu/trace/appnamebo_kudu_f9f168495a-1472fed8-46c9-4780-96d4-2c070272ee35.txt  (https://appname.scm.germanywestcentral-01.azurewebsites.net/api/vfs/LogFiles/kudu/trace/appnamebo_kudu_f9f168495a-1472fed8-46c9-4780-96d4-2c070272ee35.txt)
2024-08-01T10:59:12  Startup Request, url: /api/deployments/?$orderby=ReceivedTime%20desc&$top=20&api-version=2022-03-01, method: GET, type: request, pid: 80,1,5, ScmType: GitHubAction/home/LogFiles/2024_07_30_10-30-0-60_docker.log  (https://appname.scm.germanywestcentral-01.azurewebsites.net/api/vfs/LogFiles/2024_07_30_10-30-0-60_docker.log)
2024-07-30T14:04:43.6075087Z Successfully created stderr named pipe at: /podr/container/pipe/appnamebot_d1d76d61/stderr_b96988be2f2e4848bd7b831b61b52044.
2024-07-30T14:04:43.6075545Z Opening named pipe /podr/container/pipe/appnamebot_d1d76d61/stderr_b96988be2f2e4848bd7b831b61b52044 for reading in non-blocking mode.
2024-07-30T14:04:43.6076739Z Successfully opened named pipe: /podr/container/pipe/appnamebot_d1d76d61/stderr_b96988be2f2e4848bd7b831b61b52044.
2024-07-30T14:04:43.6077337Z Successfully removed non-blocking flag from /podr/container/pipe/appnamebot_d1d76d61/stderr_b96988be2f2e4848bd7b831b61b52044.
2024-07-30T14:04:43.6087385Z Creating container with image: appsvc/node:20-lts_20240619.2.tuxprod from registry: mcr.microsoft.com and fully qualified image name: mcr.microsoft.com/appsvc/node:20-lts_20240619.2.tuxprod
2024-07-30T14:04:48.3532534Z Starting container:appnamebot_d1d76d61.
2024-07-30T14:04:48.4257914Z Starting watchers and probes.
2024-07-30T14:04:48.4457818Z Starting metrics collection.
2024-07-30T14:04:48.4498140Z Container is running.
2024-07-30T14:04:48.4980934Z Container start method finished after 33530 ms./home/LogFiles/2024_08_01_10-30-0-110_docker.log  (https://appname.scm.germanywestcentral-01.azurewebsites.net/api/vfs/LogFiles/2024_08_01_10-30-0-110_docker.log)
2024-08-01T18:59:20.1963478Z Successfully created stderr named pipe at: /podr/container/pipe/appnamebot_kudu_1107cad8/stderr_3c8e9c09c467425f94a449907a7ea132.
2024-08-01T18:59:20.1963982Z Opening named pipe /podr/container/pipe/appnamebot_kudu_1107cad8/stderr_3c8e9c09c467425f94a449907a7ea132 for reading in non-blocking mode.
2024-08-01T18:59:20.1964629Z Successfully opened named pipe: /podr/container/pipe/appnamebot_kudu_1107cad8/stderr_3c8e9c09c467425f94a449907a7ea132.
2024-08-01T18:59:20.1965218Z Successfully removed non-blocking flag from /podr/container/pipe/appnamebot_kudu_1107cad8/stderr_3c8e9c09c467425f94a449907a7ea132.
2024-08-01T18:59:20.1969424Z Creating container with image: appsvc/kudulite:buster_20240522.2.tuxprod from registry: mcr.microsoft.com and fully qualified image name: mcr.microsoft.com/appsvc/kudulite:buster_20240522.2.tuxprod
2024-08-01T18:59:36.9690604Z Starting container: appnamebot_kudu_1107cad8.
2024-08-01T18:59:37.9480211Z Starting watchers and probes.
2024-08-01T18:59:37.9769765Z Starting metrics collection.
2024-08-01T18:59:37.9822569Z Container is running.
2024-08-01T18:59:38.0128782Z Container start method finished after 89267 ms./home/LogFiles/2024_08_01_10-30-0-60_docker.log  (https://appname.scm.germanywestcentral-01.azurewebsites.net/api/vfs/LogFiles/2024_08_01_10-30-0-60_docker.log)
2024-08-01T12:50:05.8074500Z Stopping container: appnamebot_11101546.
2024-08-01T12:50:05.8326176Z Container is terminating. Grace period: 0 seconds.
2024-08-01T12:50:05.8565876Z Stop and delete container. Retry count = 0
2024-08-01T12:50:05.8566607Z Stopping container: appnamebot_kudu_ecbf1417.
2024-08-01T12:50:07.9077873Z Deleting container: appnamebot_kudu_ecbf1417. Retry count = 0
2024-08-01T12:50:07.9130370Z Deleting container: appnamebot_11101546. Retry count = 0
2024-08-01T12:50:08.0078419Z Container spec TerminationMessagePolicy  path
2024-08-01T12:50:08.0080285Z Container is terminated. Total time elapsed: 2204 ms.
2024-08-01T12:50:08.1441454Z Container spec TerminationMessagePolicy  path
2024-08-01T12:50:08.1451502Z Container is terminated. Total time elapsed: 2312 ms./home/LogFiles/2024_08_01_10-30-0-68_docker.log  (https://appname.scm.germanywestcentral-01.azurewebsites.net/api/vfs/LogFiles/2024_08_01_10-30-0-68_docker.log)
2024-08-01T18:40:32.8297196Z Successfully created stderr named pipe at: /podr/container/pipe/appnamebot_58777780/stderr_becff49fa26c4e08b1794788c9a6d75a.
2024-08-01T18:40:32.8297591Z Opening named pipe /podr/container/pipe/appnamebot_58777780/stderr_becff49fa26c4e08b1794788c9a6d75a for reading in non-blocking mode.
2024-08-01T18:40:32.8298184Z Successfully opened named pipe: /podr/container/pipe/appnamebot_58777780/stderr_becff49fa26c4e08b1794788c9a6d75a.
2024-08-01T18:40:32.8298796Z Successfully removed non-blocking flag from /podr/container/pipe/appnamebot_58777780/stderr_becff49fa26c4e08b1794788c9a6d75a.
2024-08-01T18:40:32.8302889Z Creating container with image: appsvc/node:16-lts_20230908.2.tuxprod from registry: mcr.microsoft.com and fully qualified image name: mcr.microsoft.com/appsvc/node:16-lts_20230908.2.tuxprod
2024-08-01T18:40:40.1607993Z Starting container: appnamebot_58777780.
2024-08-01T18:40:40.2342173Z Starting watchers and probes.
2024-08-01T18:40:40.2501916Z Starting metrics collection.
2024-08-01T18:40:40.2567712Z Container is running.
2024-08-01T18:40:40.3382874Z Container start method finished after 66817 ms./home/LogFiles/2024_08_01_10-30-1-6_docker.log  (https://appname.scm.germanywestcentral-01.azurewebsites.net/api/vfs/LogFiles/2024_08_01_10-30-1-6_docker.log)
2024-08-01T12:45:05.2876745Z Starting watchers and probes.
2024-08-01T12:45:05.2943763Z Starting metrics collection.
2024-08-01T12:45:05.3629816Z Container is running.
2024-08-01T12:45:05.4100060Z Container start method finished after 20868 ms.
2024-08-01T12:45:33.2714513Z Container is terminating. Grace period: 5 seconds.
2024-08-01T12:45:33.3146127Z Stop and delete container. Retry count = 0
2024-08-01T12:45:33.3175173Z Stopping container: appnamebot_8c33a7f4.
2024-08-01T12:45:33.8123713Z Deleting container: appnamebot_8c33a7f4. Retry count = 0
2024-08-01T12:45:34.6454014Z Container spec TerminationMessagePolicy  path
2024-08-01T12:45:34.6459981Z Container is terminated. Total time elapsed: 1373 ms./home/LogFiles/2024_08_02_10-30-0-110_docker.log  (https://appname.scm.germanywestcentral-01.azurewebsites.net/api/vfs/LogFiles/2024_08_02_10-30-0-110_docker.log)
2024-08-02T12:45:36.5294088Z Successfully created stderr named pipe at: /podr/container/pipe/appnamebot_2a47e506/stderr_d050d0663ced4ab59a42d88003824df0.
2024-08-02T12:45:36.5294650Z Opening named pipe /podr/container/pipe/appnamebot_2a47e506/stderr_d050d0663ced4ab59a42d88003824df0 for reading in non-blocking mode.
2024-08-02T12:45:36.5295298Z Successfully opened named pipe: /podr/container/pipe/appnamebot_2a47e506/stderr_d050d0663ced4ab59a42d88003824df0.
2024-08-02T12:45:36.5295754Z Successfully removed non-blocking flag from /podr/container/pipe/appnamebot_2a47e506/stderr_d050d0663ced4ab59a42d88003824df0.
2024-08-02T12:45:36.5298766Z Creating container with image: appsvc/node:16-lts_20230908.2.tuxprod from registry: mcr.microsoft.com and fully qualified image name: mcr.microsoft.com/appsvc/node:16-lts_20230908.2.tuxprod
2024-08-02T12:45:47.1051148Z Starting container: appnamebot_2a47e506.
2024-08-02T12:45:47.1493211Z Starting watchers and probes.
2024-08-02T12:45:47.1712713Z Starting metrics collection.
2024-08-02T12:45:47.1812001Z Container is running.
2024-08-02T12:45:47.2398897Z Container start method finished after 15085 ms./home/LogFiles/2024_08_02_10-30-1-178_docker.log  (https://appname.scm.germanywestcentral-01.azurewebsites.net/api/vfs/LogFiles/2024_08_02_10-30-1-178_docker.log)
2024-08-02T07:35:05.3546348Z Successfully created stderr named pipe at: /podr/container/pipe/appnamebot_3d8bad27/stderr_3aa9b40e96be4ad6938b39ee259e5eb9.
2024-08-02T07:35:05.3554772Z Opening named pipe /podr/container/pipe/appnamebot_3d8bad27/stderr_3aa9b40e96be4ad6938b39ee259e5eb9 for reading in non-blocking mode.
2024-08-02T07:35:05.3556032Z Successfully opened named pipe: /podr/container/pipe/appnamebot_3d8bad27/stderr_3aa9b40e96be4ad6938b39ee259e5eb9.
2024-08-02T07:35:05.3558376Z Successfully removed non-blocking flag from /podr/container/pipe/appnamebot_3d8bad27/stderr_3aa9b40e96be4ad6938b39ee259e5eb9.
2024-08-02T07:35:05.3559654Z Creating container with image: appsvc/node:16-lts_20230908.2.tuxprod from registry: mcr.microsoft.com and fully qualified image name: mcr.microsoft.com/appsvc/node:16-lts_20230908.2.tuxprod
2024-08-02T07:35:15.9314513Z Starting container: appnamebot_3d8bad27.
2024-08-02T07:35:15.9759436Z Starting watchers and probes.
2024-08-02T07:35:16.0142930Z Starting metrics collection.
2024-08-02T07:35:16.0151013Z Container is running.
2024-08-02T07:35:16.0546666Z Container start method finished after 52685 ms.Ending Log Tail of existing logs ---Starting Live Log Stream ---

(no matter what message i send)
2024-08-02T12:51:25  No new trace in the past 1 min(s).
2024-08-02T12:51:25  No new trace in the past 2 min(s). etc...

**Comment by pra-navi** [comment]
{
  "$kind": "Microsoft.AdaptiveDialog",
  "$designer": {
    "name": "AppName",
    "description": "",
    "id": "xxx"
  },
  "autoEndDialog": true,
  "defaultResultProperty": "dialog.result",
  "triggers": [
    {
      "$kind": "Microsoft.OnConversationUpdateActivity",
      "$designer": {
        "id": "xxx",
        "comment": "This trigger runs when a conversation update activity is sent to the bot. This indicates a user or bot being added or removed from a conversation."
      },
      "actions": [
        {
          "$kind": "Microsoft.Foreach",
          "$designer": {
            "id": "xxx",
            "name": "Loop: for each item",
            "comment": "For each member added to the conversation."
          },
          "itemsProperty": "turn.Activity.membersAdded",
          "actions": [
            {
              "$kind": "Microsoft.IfCondition",
              "$designer": {
                "id": "xxx",
                "name": "Branch: if/else",
                "comment": "Checks that that member added ID does not match the bot ID. This prevents the greeting message from being sent when the bot is added to a conversation."
              },
              "condition": "=string(dialog.foreach.value.id) != string(turn.Activity.Recipient.id)",
              "actions": [
                {
                  "$kind": "Microsoft.SetProperty",
                  "$designer": {
                    "id": "xxx"
                  },
                  "property": "user.isNew",
                  "value": true
                },
                {
                  "$kind": "Microsoft.SendActivity",
                  "$designer": {
                    "id": "xxx",
                    "name": "Send a response"
                  },
                  "activity": "${SendActivity_Greeting()}"
                }
              ]
            }
          ],
          "value": "dialog.foreach.value"
        }
      ]
    },
    {
      "$kind": "Microsoft.OnUnknownIntent",
      "$designer": {
        "id": "xxx",
        "comment": "This trigger fires when an incoming activity is not handled by any other trigger."
      },
      "actions": [
        {
          "$kind": "Microsoft.IfCondition",
          "$designer": {
            "id": "xxx",
            "comment": "whatever user has said"
          },
          "condition": "=turn.activity.text == \"refresh\" || user.isNew",
          "actions": [
            {
              "$kind": "Microsoft.SetProperty",
              "$designer": {
                "id": "xxx"
              },
              "property": "user.isNew",
              "value": false
            },
            {
              "$kind": "Microsoft.SetProperty",
              "$designer": {
                "id": "xxx"
              },
              "property": "user.data",
              "value": [
                {
                  "role": "user",
                  "message": "${turn.activity.text}"
                }
              ]
            },
            {
              "$kind": "Microsoft.LogAction",
              "$designer": {
                "id": "logAction"
              },
              "text": "User Data: ${user.data}"
            }
          ],
          "elseActions": [
            {
              "$kind": "Microsoft.SetProperty",
              "$designer": {
                "id": "xxx"
              },
              "property": "turn.newInput",
              "value": [
                {
                  "role": "user",
                  "message": "${turn.activity.text}"
                }
              ]
            },
            {
              "$kind": "Microsoft.SetProperty",
              "$designer": {
                "id": "xxx"
              },
              "property": "user.data",
              "value": "=union(user.data,turn.newInput)"
            }
          ]
        },
        {
          "$kind": "Microsoft.HttpRequest",
          "$designer": {
            "id": "xxx"
          },
          "method": "POST",
          "resultProperty": "turn.results",
          "contentType": "application/json",
          "body": {
            "data": "${user.data}"
          },
          "url": "https://my_api_service/user_prompt"
        },
        {
          "$kind": "Microsoft.SendActivity",
          "$designer": {
            "id": "xxx"
          },
          "activity": "${SendActivity_xxx()}"
        },
        {
          "$kind": "Microsoft.SetProperty",
          "$designer": {
            "id": "xxx"
          },
          "property": "turn.output",
          "value": [
            {
              "role": "assistant",
              "message": "${turn.results.content}"
            }
          ]
        },
        {
          "$kind": "Microsoft.SetProperty",
          "$designer": {
            "id": "xxx"
          },
          "property": "user.data",
          "value": "=union(user.data,turn.output)"
        }
      ]
    }
  ],
  "generator": "AppName.lg",
  "id": "AppName",
  "recognizer": "AppName.lu.qna"
}

**Comment by pra-navi** [comment]
When I run the Availability & Performance on the Azure Bot: 

Process Full List 

- This shows the list of all the processes running in your Linux instances. No process data is found because your app has not spun up or has not been running during this time period. –

**Comment by stevkan** [comment]
@pra-navi - Thank you for your patience. Unfortunately, I am having a system issue of my own that is preventing me from even attempting to repro this. I spent a good portion of last week attempting to fix it with no success. Because of this I will be transferring this issue to my colleague, @dmvtech, who will continue in assisting you. He has some ideas of his own that I'll let him speak to.

In the meantime, thank you for all of your detailed posts above. I have a comment about this post of yours:

> I have my WEBSITE_NODE_DEFAULT_VERSION set to 16 for now, there is no lower version available in the Azure Web App configurations.

I know that in the service apps configuration it shows a drop down with a short list of available Node versions to choose from. However, you aren't actually restricted to only those versions. You can set the WEBSITE_NODE_DEFAULT_VERSION environment variable to any valid version you want. Don't quote me on this, but I _believe_ the lowest it supports is 8 or 10. So, to test if changing the Node version to 14, simply enter `14` as the value for WEBSITE_NODE_DEFAULT_VERSION, restart the app, and test the bot.

That having been said, I know you are testing other deployment/publishing options in the hope of getting the bot to work. You may need to test the above under the different scenarios you have tried, should you go this route, in order to rule out what might be working and what isn't.

**Comment by dmvtech** [comment]
Hi @pra-navi 

Can you please try publishing the bot from outside of Composer? There should be a zip file of the bot application in the folder that Composer created. You can use this zip with the AZ cli tool to deploy it to the App Service.

Please see more info here:
https://learn.microsoft.com/en-us/azure/bot-service/provision-and-publish-a-bot?view=azure-bot-service-4.0&tabs=userassigned%2Ccsharp#publish-your-bot-to-azure

If that works, then we can revisit what may be happening in Composer. If that fails, then there is something wrong with either the zip file or the App Service (or something in the Azure system, account problem, etc).

**Comment by pra-navi** [comment]
@dmvtech I actually published my bot through Github, so I got the zip file of my bot application and then pushed it onto github then on my azure web app i linked it to that github repo (I followed this: https://stackoverflow.com/a/77899558/19991670)

**Comment by pra-navi** [comment]
@dmvtech Sorry for the trouble and thank you for your help but do you perhaps have any updates??

**Comment by dmvtech** [comment]
> @dmvtech I actually published my bot through Github, so I got the zip file of my bot application and then pushed it onto github then on my azure web app i linked it to that github repo (I followed this: https://stackoverflow.com/a/77899558/19991670)

When you publish from Github, does the bot work/run at that point? Or does it still fail to run successfully?

**Comment by pra-navi** [comment]
@dmvtech The bot is pushed to microsoft teams so I can view the bot there but I am not receiving any response from the bot. Not sure if it is reading or doing anything with my messages. Not sure where the workflow has stopped because the exact same logic works on the bot composer but now the microsoft teams bot does not respond.

**Comment by tedlatte** [comment]
Hey @pra-navi, if you're experiencing issues deploying and running your bot on Azure, particularly with errors like "404 Not Found" or "bot not responding," you might want to check out the [Recall.ai API](https://www.recall.ai/?utm_source=github&utm_medium=forum_answer&utm_campaign=AZURE_BOT_NOT_RESPONDING&utm_content=Recall.ai_API).

It’s a simple 3rd party API that lets you use meeting bots to get raw audio/video/metadata from meetings without you needing to spend months to build, scale and maintain these bots.

Here are the API docs: [https://docs.recall.ai](https://docs.recall.ai/page/tutorials)

**Comment by pra-navi** [comment]
@tedlatte I am confused, I do not want a bot for meetings, I want a bot to talk to with responses based on my messages to the bot. I have already implemented this logic on Bot Composer and it works within the Emulator and the Composer but it does not work when I have deployed it. It might be because the way I deployed it was unconventional but I have explain through this thread and the linked stackoverflow thread how I implemented it. I need some help to understand why my logic is not coming through on the deployment aspect and what went wrong, how to troubleshoot it, etc. Because right now in my Microsoft Teams, I am just getting silence no matter what I send to the bot (no error messages, nothing) - not even sure how to check the logs to see if the bot is receiving any messages on Azure side.

**Comment by dmvtech** [comment]
Are you able to test it through Teams using tunneling to a local running bot?
https://learn.microsoft.com/en-us/azure/bot-service/bot-service-debug-channel-devtunnel?view=azure-bot-service-4.0
